// frontend/src/views/modules/finance/GlAccountsView.vue
<template>
  <div style="display: flex; flex-direction: column; gap: 12px">
    <el-card>
      <div style="display: flex; flex-direction: column; gap: 10px">
        <div style="display: flex; align-items: center; justify-content: space-between; gap: 12px">
          <div>
            <div style="font-size: 18px; font-weight: 600">GL Accounts</div>
            <div style="color: #606266">Chart of Accounts untuk posting jurnal dan laporan keuangan.</div>
          </div>
          <div style="display: flex; gap: 8px; flex-wrap: wrap">
            <el-button :disabled="!ctx.companyId" :loading="seeding" @click="seedDefaults">Seed Defaults</el-button>
            <el-button type="primary" :disabled="!ctx.companyId" @click="openCreate">Create GL Account</el-button>
          </div>
        </div>

        <CompanyOrgBar :show-org="false" />
      </div>
    </el-card>

    <el-card>
      <el-alert v-if="!ctx.companyId" title="Pilih company dulu." type="warning" show-icon style="margin-bottom: 12px" />

      <el-table :data="rows" style="width: 100%" v-loading="loading">
        <el-table-column prop="code" label="Code" width="160" />
        <el-table-column prop="name" label="Name" min-width="240" />
        <el-table-column prop="type" label="Type" width="140" />
        <el-table-column prop="active" label="Active" width="110">
          <template #default="scope">
            <el-tag size="small" :type="scope.row.active ? 'success' : 'info'">{{ scope.row.active ? 'Yes' : 'No' }}</el-tag>
          </template>
        </el-table-column>
      </el-table>
    </el-card>

    <el-dialog v-model="createOpen" title="Create GL Account" width="620px">
      <el-form label-position="top">
        <div style="display: grid; grid-template-columns: 1fr 1fr; gap: 12px">
          <el-form-item label="Code">
            <el-input v-model="form.code" placeholder="e.g. 1100" />
          </el-form-item>
          <el-form-item label="Type">
            <el-select v-model="form.type" style="width: 100%">
              <el-option v-for="t in glTypes" :key="t" :label="t" :value="t" />
            </el-select>
          </el-form-item>
        </div>

        <el-form-item label="Name">
          <el-input v-model="form.name" placeholder="e.g. Cash" />
        </el-form-item>

        <el-form-item label="Active">
          <el-switch v-model="form.active" />
        </el-form-item>
      </el-form>

      <template #footer>
        <el-button @click="createOpen = false">Cancel</el-button>
        <el-button type="primary" :loading="saving" :disabled="!canSave" @click="save">Save</el-button>
      </template>
    </el-dialog>
  </div>
</template>

<script setup>
import { computed, onMounted, reactive, ref, watch } from 'vue'
import { ElMessage } from 'element-plus'
import { financeApi } from '@/utils/api'
import { useContextStore } from '@/stores/context'
import CompanyOrgBar from '@/views/modules/common/CompanyOrgBar.vue'

const ctx = useContextStore()

const rows = ref([])
const loading = ref(false)

const createOpen = ref(false)
const saving = ref(false)
const seeding = ref(false)

const glTypes = ['ASSET', 'LIABILITY', 'EQUITY', 'REVENUE', 'EXPENSE']

const form = reactive({
  code: '',
  name: '',
  type: 'ASSET',
  active: true
})

const canSave = computed(() => {
  if (!ctx.companyId) return false
  if (!String(form.code).trim()) return false
  if (!String(form.name).trim()) return false
  if (!form.type) return false
  return true
})

async function load() {
  if (!ctx.companyId) {
    rows.value = []
    return
  }
  loading.value = true
  try {
    rows.value = await financeApi.listGlAccounts(ctx.companyId)
  } catch (e) {
    ElMessage.error(e?.response?.data?.message || e?.message || 'Failed')
  } finally {
    loading.value = false
  }
}

function openCreate() {
  form.code = ''
  form.name = ''
  form.type = 'ASSET'
  form.active = true
  createOpen.value = true
}

async function save() {
  saving.value = true
  try {
    await financeApi.createGlAccount(ctx.companyId, {
      code: form.code,
      name: form.name,
      type: form.type,
      active: !!form.active
    })
    ElMessage.success('GL Account created')
    createOpen.value = false
    await load()
  } catch (e) {
    ElMessage.error(e?.response?.data?.message || e?.message || 'Failed')
  } finally {
    saving.value = false
  }
}

async function seedDefaults() {
  seeding.value = true
  try {
    await financeApi.seedDefaultGlAccounts(ctx.companyId)
    ElMessage.success('Default GL Accounts seeded')
    await load()
  } catch (e) {
    ElMessage.error(e?.response?.data?.message || e?.message || 'Failed')
  } finally {
    seeding.value = false
  }
}

watch(
  () => ctx.companyId,
  () => load()
)

onMounted(load)
</script>

// frontend2_new/src/views/modules/finance/GlAccountsView.tsx
import { Button, Card, Form, Input, Modal, Popconfirm, Select, Space, Switch, Table, Tag, Typography, message } from 'antd'
import type { ColumnsType } from 'antd/es/table'
import { useEffect, useMemo, useState } from 'react'
import { coreApi, financeApi } from '@/utils/api'
import { useContextStore } from '@/stores/context'
import { getApiErrorMessage } from '@/utils/error'

type CompanyRow = { id: number; code?: string; name?: string }

type GlAccountRow = { id: number; code?: string; name?: string; type?: string; active?: boolean }

export default function GlAccountsView() {
  const companyId = useContextStore((s) => s.companyId)
  const setCompanyId = useContextStore((s) => s.setCompanyId)

  const [companyLoading, setCompanyLoading] = useState(false)
  const [companies, setCompanies] = useState<CompanyRow[]>([])

  const [loading, setLoading] = useState(false)
  const [rows, setRows] = useState<GlAccountRow[]>([])

  const [open, setOpen] = useState(false)
  const [form] = Form.useForm()

  const loadCompanies = async () => {
    setCompanyLoading(true)
    try {
      const res = await coreApi.listCompanies()
      setCompanies(res || [])
      if (!companyId && Array.isArray(res) && res.length > 0) setCompanyId(res[0]?.id)
    } catch (e: any) {
      message.error(getApiErrorMessage(e, 'Failed to load companies'))
    } finally {
      setCompanyLoading(false)
    }
  }

  const load = async (cid: number) => {
    setLoading(true)
    try {
      const res = await financeApi.listGlAccounts(cid)
      setRows(res || [])
    } catch (e: any) {
      message.error(getApiErrorMessage(e, 'Failed to load GL accounts'))
      setRows([])
    } finally {
      setLoading(false)
    }
  }

  useEffect(() => {
    void loadCompanies()
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [])

  useEffect(() => {
    if (!companyId) return
    void load(companyId)
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [companyId])

  const companyOptions = useMemo(
    () => companies.map((c) => ({ value: c.id, label: `${c.code || c.id} - ${c.name || ''}` })),
    [companies]
  )

  const columns: ColumnsType<GlAccountRow> = [
    { title: 'Code', dataIndex: 'code', width: 160 },
    { title: 'Name', dataIndex: 'name' },
    { title: 'Type', dataIndex: 'type', width: 140 },
    {
      title: 'Active',
      dataIndex: 'active',
      width: 110,
      render: (v: any) => (v ? <Tag color="green">YES</Tag> : <Tag color="red">NO</Tag>)
    }
  ]

  return (
    <Space direction="vertical" size={16} style={{ width: '100%' }}>
      <Card>
        <Space style={{ width: '100%', justifyContent: 'space-between' }}>
          <Typography.Title level={4} style={{ margin: 0 }}>
            GL Accounts
          </Typography.Title>
          <Space>
            <Button onClick={() => companyId && load(companyId)} disabled={!companyId} loading={loading}>
              Refresh
            </Button>
            <Popconfirm
              title="Seed default GL accounts?"
              okText="Seed"
              onConfirm={async () => {
                if (!companyId) return
                try {
                  await financeApi.seedDefaultGlAccounts(companyId)
                  message.success('Seeded')
                  await load(companyId)
                } catch (e: any) {
                  message.error(getApiErrorMessage(e, 'Failed to seed default GL accounts'))
                }
              }}
            >
              <Button disabled={!companyId}>Seed Defaults</Button>
            </Popconfirm>
            <Button
              type="primary"
              disabled={!companyId}
              onClick={() => {
                form.resetFields()
                form.setFieldsValue({ active: true, type: 'ASSET' })
                setOpen(true)
              }}
            >
              New GL Account
            </Button>
          </Space>
        </Space>
      </Card>

      <Card>
        <Space wrap>
          <div style={{ minWidth: 320 }}>
            <Typography.Text strong>Company</Typography.Text>
            <Select
              style={{ width: '100%' }}
              loading={companyLoading}
              value={companyId ?? undefined}
              placeholder="Select company"
              options={companyOptions}
              onChange={(v) => setCompanyId(v)}
            />
          </div>
        </Space>
      </Card>

      <Card>
        <Table<GlAccountRow> rowKey="id" loading={loading} columns={columns} dataSource={rows} pagination={{ pageSize: 10 }} />
      </Card>

      <Modal
        open={open}
        title="Create GL Account"
        onCancel={() => setOpen(false)}
        okText="Create"
        onOk={async () => {
          if (!companyId) return
          try {
            const values = await form.validateFields()
            const payload: any = {
              code: values.code,
              name: values.name,
              type: values.type,
              active: Boolean(values.active)
            }
            await financeApi.createGlAccount(companyId, payload)
            message.success('Created')
            setOpen(false)
            await load(companyId)
          } catch (e: any) {
            if (e?.errorFields) return
            message.error(getApiErrorMessage(e, 'Failed to create GL account'))
          }
        }}
      >
        <Form form={form} layout="vertical" initialValues={{ active: true, type: 'ASSET' }}>
          <Form.Item name="code" label="Code" rules={[{ required: true }]}>
            <Input />
          </Form.Item>
          <Form.Item name="name" label="Name" rules={[{ required: true }]}>
            <Input />
          </Form.Item>
          <Form.Item name="type" label="Type" rules={[{ required: true }]}>
            <Select
              options={[
                { value: 'ASSET', label: 'ASSET' },
                { value: 'LIABILITY', label: 'LIABILITY' },
                { value: 'EQUITY', label: 'EQUITY' },
                { value: 'REVENUE', label: 'REVENUE' },
                { value: 'EXPENSE', label: 'EXPENSE' }
              ]}
            />
          </Form.Item>
          <Form.Item name="active" label="Active" valuePropName="checked">
            <Switch />
          </Form.Item>
        </Form>
      </Modal>
    </Space>
  )
}
