// frontend2/src/views/modules/finance/PeriodsView.tsx
import { Button, Card, DatePicker, Form, InputNumber, Modal, Space, Table, Tag, Typography, message } from 'antd'
import type { ColumnsType } from 'antd/es/table'
import dayjs from 'dayjs'
import { useEffect, useState } from 'react'
import { financeApi } from '@/utils/api'
import { useContextStore } from '@/stores/context'
import CompanyOrgBar from '@/views/modules/common/CompanyOrgBar'

type FiscalYearRow = {
  id: number
  year?: number
  startDate?: string
  endDate?: string
  status?: 'OPEN' | 'CLOSED'
}

type PeriodRow = {
  id: number
  fiscalYearId?: number
  periodNo?: number
  startDate?: string
  endDate?: string
  status?: 'OPEN' | 'CLOSED'
}

function toLocalDateString(d: any): string {
  if (!d) return ''
  return dayjs(d).format('YYYY-MM-DD')
}

export default function PeriodsView() {
  const companyId = useContextStore((s) => s.companyId)

  const [fyLoading, setFyLoading] = useState(false)
  const [fiscalYears, setFiscalYears] = useState<FiscalYearRow[]>([])
  const [selectedFyId, setSelectedFyId] = useState<number | null>(null)

  const [periodLoading, setPeriodLoading] = useState(false)
  const [periods, setPeriods] = useState<PeriodRow[]>([])

  const [createOpen, setCreateOpen] = useState(false)
  const [saving, setSaving] = useState(false)
  const [createForm] = Form.useForm()

  async function loadFiscalYears() {
    if (!companyId) {
      setFiscalYears([])
      setSelectedFyId(null)
      return
    }
    setFyLoading(true)
    try {
      const list = ((await financeApi.listFiscalYears(companyId)) || []) as FiscalYearRow[]
      setFiscalYears(list)
      if (!selectedFyId && list.length > 0) setSelectedFyId(list[0].id)
    } catch (e: any) {
      message.error(e?.response?.data?.message || e?.message || 'Failed to load fiscal years')
      setFiscalYears([])
      setSelectedFyId(null)
    } finally {
      setFyLoading(false)
    }
  }

  async function loadPeriods(fiscalYearId: number) {
    if (!companyId) {
      setPeriods([])
      return
    }
    setPeriodLoading(true)
    try {
      setPeriods(((await financeApi.listPeriods(companyId, fiscalYearId)) || []) as PeriodRow[])
    } catch (e: any) {
      message.error(e?.response?.data?.message || e?.message || 'Failed to load periods')
      setPeriods([])
    } finally {
      setPeriodLoading(false)
    }
  }

  useEffect(() => {
    void loadFiscalYears()
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [companyId])

  useEffect(() => {
    if (!companyId || !selectedFyId) {
      setPeriods([])
      return
    }
    void loadPeriods(selectedFyId)
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [companyId, selectedFyId])

  const fyColumns: ColumnsType<FiscalYearRow> = [
    { title: 'Year', dataIndex: 'year', width: 120 },
    { title: 'Start', dataIndex: 'startDate', width: 140 },
    { title: 'End', dataIndex: 'endDate', width: 140 },
    {
      title: 'Status',
      dataIndex: 'status',
      width: 120,
      render: (v: any) => (String(v) === 'OPEN' ? <Tag color="green">OPEN</Tag> : <Tag color="red">CLOSED</Tag>)
    },
    {
      title: 'Actions',
      key: 'actions',
      width: 220,
      render: (_, r) => {
        const status = String(r.status || '')
        return (
          <Space>
            <Button
              size="small"
              disabled={!companyId || status !== 'OPEN'}
              onClick={async () => {
                if (!companyId) return
                try {
                  await financeApi.closeFiscalYear(companyId, r.id)
                  message.success('Closed')
                  await loadFiscalYears()
                } catch (e: any) {
                  message.error(e?.response?.data?.message || e?.message || 'Failed to close fiscal year')
                }
              }}
            >
              Close
            </Button>
            <Button
              size="small"
              disabled={!companyId || status !== 'CLOSED'}
              onClick={async () => {
                if (!companyId) return
                try {
                  await financeApi.openFiscalYear(companyId, r.id)
                  message.success('Opened')
                  await loadFiscalYears()
                } catch (e: any) {
                  message.error(e?.response?.data?.message || e?.message || 'Failed to open fiscal year')
                }
              }}
            >
              Open
            </Button>
          </Space>
        )
      }
    }
  ]

  const periodColumns: ColumnsType<PeriodRow> = [
    { title: 'Period No', dataIndex: 'periodNo', width: 120 },
    { title: 'Start', dataIndex: 'startDate', width: 140 },
    { title: 'End', dataIndex: 'endDate', width: 140 },
    {
      title: 'Status',
      dataIndex: 'status',
      width: 120,
      render: (v: any) => (String(v) === 'OPEN' ? <Tag color="green">OPEN</Tag> : <Tag color="red">CLOSED</Tag>)
    },
    {
      title: 'Actions',
      key: 'actions',
      width: 220,
      render: (_, r) => {
        const status = String(r.status || '')
        return (
          <Space>
            <Button
              size="small"
              disabled={!companyId || status !== 'OPEN'}
              onClick={async () => {
                if (!companyId) return
                try {
                  await financeApi.closePeriod(companyId, r.id)
                  message.success('Closed')
                  if (selectedFyId) await loadPeriods(selectedFyId)
                } catch (e: any) {
                  message.error(e?.response?.data?.message || e?.message || 'Failed to close period')
                }
              }}
            >
              Close
            </Button>
            <Button
              size="small"
              disabled={!companyId || status !== 'CLOSED'}
              onClick={async () => {
                if (!companyId) return
                try {
                  await financeApi.openPeriod(companyId, r.id)
                  message.success('Opened')
                  if (selectedFyId) await loadPeriods(selectedFyId)
                } catch (e: any) {
                  message.error(e?.response?.data?.message || e?.message || 'Failed to open period')
                }
              }}
            >
              Open
            </Button>
          </Space>
        )
      }
    }
  ]

  return (
    <Space direction="vertical" size={16} style={{ width: '100%' }}>
      <Card>
        <Space style={{ width: '100%', justifyContent: 'space-between' }}>
          <div>
            <Typography.Title level={4} style={{ margin: 0 }}>
              Periods
            </Typography.Title>
            <Typography.Text type="secondary">Fiscal Years dan Accounting Periods.</Typography.Text>
          </div>
          <Space>
            <Button onClick={() => void loadFiscalYears()} disabled={!companyId} loading={fyLoading}>
              Refresh
            </Button>
            <Button
              type="primary"
              disabled={!companyId}
              onClick={() => {
                createForm.resetFields()
                const y = dayjs().year()
                createForm.setFieldsValue({ year: y, startDate: dayjs(`${y}-01-01`), endDate: dayjs(`${y}-12-31`) })
                setCreateOpen(true)
              }}
            >
              New Fiscal Year
            </Button>
          </Space>
        </Space>
      </Card>

      <Card>
        <CompanyOrgBar showOrg={false} />
      </Card>

      <div style={{ display: 'grid', gridTemplateColumns: '1fr 1.1fr', gap: 16 }}>
        <Card title="Fiscal Years">
          <Table<FiscalYearRow>
            rowKey="id"
            size="small"
            loading={fyLoading}
            columns={fyColumns}
            dataSource={fiscalYears}
            pagination={{ pageSize: 8 }}
            onRow={(r) => ({
              onClick: () => setSelectedFyId(r.id)
            })}
          />
        </Card>

        <Card title="Accounting Periods">
          <Table<PeriodRow>
            rowKey="id"
            size="small"
            loading={periodLoading}
            columns={periodColumns}
            dataSource={periods}
            pagination={{ pageSize: 10 }}
          />
        </Card>
      </div>

      <Modal
        open={createOpen}
        title="Create Fiscal Year"
        onCancel={() => setCreateOpen(false)}
        okText="Create"
        confirmLoading={saving}
        onOk={async () => {
          if (!companyId) return
          try {
            const v = await createForm.validateFields()
            setSaving(true)
            await financeApi.createFiscalYear(companyId, {
              year: v.year,
              startDate: toLocalDateString(v.startDate),
              endDate: toLocalDateString(v.endDate)
            })
            message.success('Created')
            setCreateOpen(false)
            await loadFiscalYears()
          } catch (e: any) {
            if (e?.errorFields) return
            message.error(e?.response?.data?.message || e?.message || 'Failed to create fiscal year')
          } finally {
            setSaving(false)
          }
        }}
      >
        <Form form={createForm} layout="vertical">
          <Form.Item name="year" label="Year" rules={[{ required: true }]}>
            <InputNumber style={{ width: '100%' }} min={1900} max={3000} />
          </Form.Item>
          <Form.Item name="startDate" label="Start Date" rules={[{ required: true }]}>
            <DatePicker style={{ width: '100%' }} />
          </Form.Item>
          <Form.Item name="endDate" label="End Date" rules={[{ required: true }]}>
            <DatePicker style={{ width: '100%' }} />
          </Form.Item>
        </Form>
      </Modal>
    </Space>
  )
}

// frontend/src/views/modules/finance/PeriodsView.vue
<template>
  <div style="display: flex; flex-direction: column; gap: 12px">
    <el-card>
      <div style="display: flex; flex-direction: column; gap: 10px">
        <div style="display: flex; align-items: center; justify-content: space-between; gap: 12px">
          <div>
            <div style="font-size: 18px; font-weight: 600">Fiscal Year & Periods</div>
            <div style="color: #606266">Setup periode akuntansi untuk laporan (open/close).</div>
          </div>
          <el-button type="primary" :disabled="!ctx.companyId" @click="openCreate">Create Fiscal Year</el-button>
        </div>

        <CompanyOrgBar :show-org="false" />
      </div>
    </el-card>

    <el-card>
      <el-alert v-if="!ctx.companyId" title="Pilih company dulu." type="warning" show-icon style="margin-bottom: 12px" />

      <div style="display: grid; grid-template-columns: 1fr 1fr; gap: 12px">
        <div>
          <div style="font-weight: 600; margin-bottom: 8px">Fiscal Years</div>
          <el-table :data="fiscalYears" size="small" style="width: 100%" v-loading="fyLoading" @row-click="onSelectFy">
            <el-table-column prop="year" label="Year" width="100" />
            <el-table-column prop="startDate" label="Start" width="120" />
            <el-table-column prop="endDate" label="End" width="120" />
            <el-table-column prop="status" label="Status" width="110">
              <template #default="scope">
                <el-tag size="small" :type="scope.row.status === 'OPEN' ? 'success' : 'info'">{{ scope.row.status }}</el-tag>
              </template>
            </el-table-column>
            <el-table-column label="Actions" width="150">
              <template #default="scope">
                <el-button size="small" :disabled="scope.row.status !== 'OPEN'" @click.stop="closeFy(scope.row)">Close</el-button>
                <el-button size="small" :disabled="scope.row.status !== 'CLOSED'" @click.stop="openFy(scope.row)">Open</el-button>
              </template>
            </el-table-column>
          </el-table>
        </div>

        <div>
          <div style="display: flex; align-items: center; justify-content: space-between; margin-bottom: 8px">
            <div style="font-weight: 600">Periods</div>
            <el-tag v-if="selectedFy" type="info">FY: {{ selectedFy.year }}</el-tag>
          </div>

          <el-alert v-if="!selectedFy" title="Klik fiscal year untuk melihat periods." type="info" show-icon style="margin-bottom: 12px" />

          <el-table v-else :data="periods" size="small" style="width: 100%" v-loading="pLoading">
            <el-table-column prop="periodNo" label="#" width="70" />
            <el-table-column prop="startDate" label="Start" width="120" />
            <el-table-column prop="endDate" label="End" width="120" />
            <el-table-column prop="status" label="Status" width="110">
              <template #default="scope">
                <el-tag size="small" :type="scope.row.status === 'OPEN' ? 'success' : 'info'">{{ scope.row.status }}</el-tag>
              </template>
            </el-table-column>
            <el-table-column label="Actions" width="150">
              <template #default="scope">
                <el-button size="small" :disabled="scope.row.status !== 'OPEN'" @click="closePeriod(scope.row)">Close</el-button>
                <el-button size="small" :disabled="scope.row.status !== 'CLOSED'" @click="openPeriod(scope.row)">Open</el-button>
              </template>
            </el-table-column>
          </el-table>
        </div>
      </div>
    </el-card>

    <el-dialog v-model="createOpen" title="Create Fiscal Year" width="640px">
      <el-form label-position="top">
        <div style="display: grid; grid-template-columns: 1fr 1fr 1fr; gap: 12px">
          <el-form-item label="Year">
            <el-input v-model="form.year" placeholder="e.g. 2026" />
          </el-form-item>
          <el-form-item label="Start Date">
            <el-date-picker v-model="form.startDate" type="date" value-format="YYYY-MM-DD" style="width: 220px" />
          </el-form-item>
          <el-form-item label="End Date">
            <el-date-picker v-model="form.endDate" type="date" value-format="YYYY-MM-DD" style="width: 220px" />
          </el-form-item>
        </div>
      </el-form>

      <template #footer>
        <el-button @click="createOpen = false">Cancel</el-button>
        <el-button type="primary" :loading="saving" :disabled="!canSave" @click="save">Save</el-button>
      </template>
    </el-dialog>
  </div>
</template>

<script setup>
import { computed, onMounted, reactive, ref, watch } from 'vue'
import { ElMessage } from 'element-plus'
import { financeApi } from '@/utils/api'
import { useContextStore } from '@/stores/context'
import CompanyOrgBar from '@/views/modules/common/CompanyOrgBar.vue'

const ctx = useContextStore()

const fiscalYears = ref([])
const fyLoading = ref(false)

const selectedFy = ref(null)

const periods = ref([])
const pLoading = ref(false)

const createOpen = ref(false)
const saving = ref(false)

const form = reactive({
  year: '',
  startDate: '',
  endDate: ''
})

const canSave = computed(() => {
  if (!ctx.companyId) return false
  const y = Number(form.year)
  if (!Number.isFinite(y) || y <= 0) return false
  if (!form.startDate || !form.endDate) return false
  return true
})

async function loadFiscalYears() {
  if (!ctx.companyId) {
    fiscalYears.value = []
    selectedFy.value = null
    periods.value = []
    return
  }
  fyLoading.value = true
  try {
    fiscalYears.value = await financeApi.listFiscalYears(ctx.companyId)
  } catch (e) {
    ElMessage.error(e?.response?.data?.message || e?.message || 'Failed')
  } finally {
    fyLoading.value = false
  }
}

async function loadPeriods() {
  if (!ctx.companyId || !selectedFy.value?.id) {
    periods.value = []
    return
  }
  pLoading.value = true
  try {
    periods.value = await financeApi.listPeriods(ctx.companyId, selectedFy.value.id)
  } catch (e) {
    ElMessage.error(e?.response?.data?.message || e?.message || 'Failed')
  } finally {
    pLoading.value = false
  }
}

function onSelectFy(row) {
  selectedFy.value = row
  loadPeriods()
}

function openCreate() {
  const now = new Date()
  form.year = String(now.getFullYear())
  form.startDate = `${now.getFullYear()}-01-01`
  form.endDate = `${now.getFullYear()}-12-31`
  createOpen.value = true
}

async function save() {
  saving.value = true
  try {
    await financeApi.createFiscalYear(ctx.companyId, {
      year: Number(form.year),
      startDate: form.startDate,
      endDate: form.endDate
    })
    ElMessage.success('Fiscal year created')
    createOpen.value = false
    await loadFiscalYears()
  } catch (e) {
    ElMessage.error(e?.response?.data?.message || e?.message || 'Failed')
  } finally {
    saving.value = false
  }
}

async function closeFy(row) {
  try {
    await financeApi.closeFiscalYear(ctx.companyId, row.id)
    ElMessage.success('Fiscal year closed')
    await loadFiscalYears()
    if (selectedFy.value?.id === row.id) {
      selectedFy.value = fiscalYears.value.find((x) => x.id === row.id) || selectedFy.value
      await loadPeriods()
    }
  } catch (e) {
    ElMessage.error(e?.response?.data?.message || e?.message || 'Failed')
  }
}

async function openFy(row) {
  try {
    await financeApi.openFiscalYear(ctx.companyId, row.id)
    ElMessage.success('Fiscal year opened')
    await loadFiscalYears()
    if (selectedFy.value?.id === row.id) {
      selectedFy.value = fiscalYears.value.find((x) => x.id === row.id) || selectedFy.value
      await loadPeriods()
    }
  } catch (e) {
    ElMessage.error(e?.response?.data?.message || e?.message || 'Failed')
  }
}

async function closePeriod(row) {
  try {
    await financeApi.closePeriod(ctx.companyId, row.id)
    ElMessage.success('Period closed')
    await loadPeriods()
  } catch (e) {
    ElMessage.error(e?.response?.data?.message || e?.message || 'Failed')
  }
}

async function openPeriod(row) {
  try {
    await financeApi.openPeriod(ctx.companyId, row.id)
    ElMessage.success('Period opened')
    await loadPeriods()
  } catch (e) {
    ElMessage.error(e?.response?.data?.message || e?.message || 'Failed')
  }
}

watch(
  () => ctx.companyId,
  async () => {
    await loadFiscalYears()
    await loadPeriods()
  }
)

onMounted(loadFiscalYears)
</script>
