// frontend2/src/views/modules/finance/ReportsView.tsx
import { Button, Card, DatePicker, Form, Select, Space, Table, Tabs, Typography, message } from 'antd'
import type { ColumnsType } from 'antd/es/table'
import dayjs from 'dayjs'
import { useEffect, useMemo, useState } from 'react'
import { financeApi } from '@/utils/api'
import { useContextStore } from '@/stores/context'
import CompanyOrgBar from '@/views/modules/common/CompanyOrgBar'

type AgingRow = {
  businessPartnerId?: number
  businessPartnerName?: string
  bucket0To30?: any
  bucket31To60?: any
  bucket61To90?: any
  bucketOver90?: any
  totalOpen?: any
}

type GlSummaryRow = { accountCode?: any; debitTotal?: any; creditTotal?: any; balance?: any }

type TrialBalanceRow = { accountCode?: string; accountName?: string; accountType?: string; debitTotal?: any; creditTotal?: any; balance?: any }

type ProfitLossRow = { accountCode?: string; accountName?: string; accountType?: string; amount?: any }

type BalanceSheetRow = { accountCode?: string; accountName?: string; accountType?: string; amount?: any }

function toLocalDateString(d: any): string {
  if (!d) return ''
  return dayjs(d).format('YYYY-MM-DD')
}

export default function ReportsView() {
  const companyId = useContextStore((s) => s.companyId)

  const [agingLoading, setAgingLoading] = useState(false)
  const [agingRows, setAgingRows] = useState<AgingRow[]>([])
  const [agingTotals, setAgingTotals] = useState<any>(null)
  const [agingForm] = Form.useForm()

  const [glSummaryLoading, setGlSummaryLoading] = useState(false)
  const [glSummaryRows, setGlSummaryRows] = useState<GlSummaryRow[]>([])
  const [glSummaryTotals, setGlSummaryTotals] = useState<any>(null)
  const [glSummaryForm] = Form.useForm()

  const [trialLoading, setTrialLoading] = useState(false)
  const [trialRows, setTrialRows] = useState<TrialBalanceRow[]>([])
  const [trialTotals, setTrialTotals] = useState<any>(null)
  const [trialForm] = Form.useForm()

  const [plLoading, setPlLoading] = useState(false)
  const [plRows, setPlRows] = useState<ProfitLossRow[]>([])
  const [plTotals, setPlTotals] = useState<any>(null)
  const [plForm] = Form.useForm()

  const [bsLoading, setBsLoading] = useState(false)
  const [bsRows, setBsRows] = useState<BalanceSheetRow[]>([])
  const [bsTotals, setBsTotals] = useState<any>(null)
  const [bsForm] = Form.useForm()

  useEffect(() => {
    setAgingRows([])
    setAgingTotals(null)
    setGlSummaryRows([])
    setGlSummaryTotals(null)
    setTrialRows([])
    setTrialTotals(null)
    setPlRows([])
    setPlTotals(null)
    setBsRows([])
    setBsTotals(null)
  }, [companyId])

  const agingColumns: ColumnsType<AgingRow> = [
    { title: 'Partner', dataIndex: 'businessPartnerName' },
    { title: '0-30', dataIndex: 'bucket0To30', width: 120 },
    { title: '31-60', dataIndex: 'bucket31To60', width: 120 },
    { title: '61-90', dataIndex: 'bucket61To90', width: 120 },
    { title: '>90', dataIndex: 'bucketOver90', width: 120 },
    { title: 'Total Open', dataIndex: 'totalOpen', width: 140 }
  ]

  const glSummaryColumns: ColumnsType<GlSummaryRow> = [
    { title: 'Account Code', dataIndex: 'accountCode' },
    { title: 'Debit', dataIndex: 'debitTotal', width: 140 },
    { title: 'Credit', dataIndex: 'creditTotal', width: 140 },
    { title: 'Balance', dataIndex: 'balance', width: 140 }
  ]

  const trialColumns: ColumnsType<TrialBalanceRow> = [
    { title: 'Account Code', dataIndex: 'accountCode', width: 140 },
    { title: 'Account Name', dataIndex: 'accountName' },
    { title: 'Type', dataIndex: 'accountType', width: 120 },
    { title: 'Debit', dataIndex: 'debitTotal', width: 140 },
    { title: 'Credit', dataIndex: 'creditTotal', width: 140 },
    { title: 'Balance', dataIndex: 'balance', width: 140 }
  ]

  const plColumns: ColumnsType<ProfitLossRow> = [
    { title: 'Account Code', dataIndex: 'accountCode', width: 140 },
    { title: 'Account Name', dataIndex: 'accountName' },
    { title: 'Type', dataIndex: 'accountType', width: 120 },
    { title: 'Amount', dataIndex: 'amount', width: 160 }
  ]

  const bsColumns: ColumnsType<BalanceSheetRow> = [
    { title: 'Account Code', dataIndex: 'accountCode', width: 140 },
    { title: 'Account Name', dataIndex: 'accountName' },
    { title: 'Type', dataIndex: 'accountType', width: 120 },
    { title: 'Amount', dataIndex: 'amount', width: 160 }
  ]

  const totalsText = useMemo(() => {
    const fmt = (v: any) => (v == null ? '-' : String(v))
    return {
      aging: {
        t0: fmt(agingTotals?.total0To30),
        t1: fmt(agingTotals?.total31To60),
        t2: fmt(agingTotals?.total61To90),
        t3: fmt(agingTotals?.totalOver90),
        t4: fmt(agingTotals?.totalOpen)
      },
      gl: {
        debit: fmt(glSummaryTotals?.totalDebit),
        credit: fmt(glSummaryTotals?.totalCredit)
      },
      trial: {
        debit: fmt(trialTotals?.totalDebit),
        credit: fmt(trialTotals?.totalCredit)
      },
      pl: {
        revenue: fmt(plTotals?.totalRevenue),
        expense: fmt(plTotals?.totalExpense),
        net: fmt(plTotals?.netIncome)
      },
      bs: {
        assets: fmt(bsTotals?.totalAssets),
        liabilities: fmt(bsTotals?.totalLiabilities),
        equity: fmt(bsTotals?.totalEquity)
      }
    }
  }, [agingTotals, bsTotals, glSummaryTotals, plTotals, trialTotals])

  const runAging = async () => {
    if (!companyId) return
    try {
      const v = await agingForm.validateFields()
      setAgingLoading(true)
      const res = await financeApi.agingReport(companyId, {
        invoiceType: v.invoiceType,
        asOfDate: v.asOfDate ? toLocalDateString(v.asOfDate) : undefined
      })
      setAgingRows(res?.partners || [])
      setAgingTotals(res)
    } catch (e: any) {
      if (e?.errorFields) return
      message.error(e?.response?.data?.message || e?.message || 'Failed to load aging report')
      setAgingRows([])
      setAgingTotals(null)
    } finally {
      setAgingLoading(false)
    }
  }

  const runGlSummary = async () => {
    if (!companyId) return
    try {
      const v = await glSummaryForm.validateFields()
      setGlSummaryLoading(true)
      const res = await financeApi.glSummaryReport(companyId, {
        fromDate: toLocalDateString(v.fromDate),
        toDate: toLocalDateString(v.toDate)
      })
      setGlSummaryRows(res?.rows || [])
      setGlSummaryTotals(res)
    } catch (e: any) {
      if (e?.errorFields) return
      message.error(e?.response?.data?.message || e?.message || 'Failed to load GL summary report')
      setGlSummaryRows([])
      setGlSummaryTotals(null)
    } finally {
      setGlSummaryLoading(false)
    }
  }

  const runTrial = async () => {
    if (!companyId) return
    try {
      const v = await trialForm.validateFields()
      setTrialLoading(true)
      const res = await financeApi.trialBalanceReport(companyId, {
        fromDate: toLocalDateString(v.fromDate),
        toDate: toLocalDateString(v.toDate)
      })
      setTrialRows(res?.rows || [])
      setTrialTotals(res)
    } catch (e: any) {
      if (e?.errorFields) return
      message.error(e?.response?.data?.message || e?.message || 'Failed to load trial balance report')
      setTrialRows([])
      setTrialTotals(null)
    } finally {
      setTrialLoading(false)
    }
  }

  const runPL = async () => {
    if (!companyId) return
    try {
      const v = await plForm.validateFields()
      setPlLoading(true)
      const res = await financeApi.profitLossReport(companyId, {
        fromDate: toLocalDateString(v.fromDate),
        toDate: toLocalDateString(v.toDate)
      })
      setPlRows(res?.rows || [])
      setPlTotals(res)
    } catch (e: any) {
      if (e?.errorFields) return
      message.error(e?.response?.data?.message || e?.message || 'Failed to load profit/loss report')
      setPlRows([])
      setPlTotals(null)
    } finally {
      setPlLoading(false)
    }
  }

  const runBS = async () => {
    if (!companyId) return
    try {
      const v = await bsForm.validateFields()
      setBsLoading(true)
      const res = await financeApi.balanceSheetReport(companyId, {
        asOfDate: v.asOfDate ? toLocalDateString(v.asOfDate) : undefined
      })
      setBsRows(res?.rows || [])
      setBsTotals(res)
    } catch (e: any) {
      if (e?.errorFields) return
      message.error(e?.response?.data?.message || e?.message || 'Failed to load balance sheet report')
      setBsRows([])
      setBsTotals(null)
    } finally {
      setBsLoading(false)
    }
  }

  return (
    <Space direction="vertical" size={16} style={{ width: '100%' }}>
      <Card>
        <Typography.Title level={4} style={{ margin: 0 }}>
          Finance Reports
        </Typography.Title>
      </Card>

      <Card>
        <CompanyOrgBar showOrg={false} />
      </Card>

      <Card>
        <Tabs
          items={[
            {
              key: 'aging',
              label: 'Aging',
              children: (
                <Space direction="vertical" style={{ width: '100%' }}>
                  <Form form={agingForm} layout="vertical" initialValues={{ invoiceType: 'AR', asOfDate: dayjs() }}>
                    <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr auto', gap: 12, alignItems: 'end' }}>
                      <Form.Item name="invoiceType" label="Invoice Type" rules={[{ required: true }]}>
                        <Select options={[{ value: 'AR', label: 'AR' }, { value: 'AP', label: 'AP' }]} />
                      </Form.Item>
                      <Form.Item name="asOfDate" label="As Of Date (optional)">
                        <DatePicker style={{ width: '100%' }} />
                      </Form.Item>
                      <Button type="primary" onClick={() => void runAging()} disabled={!companyId} loading={agingLoading}>
                        Run
                      </Button>
                    </div>
                  </Form>

                  <Card size="small">
                    <Space wrap>
                      <div>Total 0-30: {totalsText.aging.t0}</div>
                      <div>Total 31-60: {totalsText.aging.t1}</div>
                      <div>Total 61-90: {totalsText.aging.t2}</div>
                      <div>Total &gt;90: {totalsText.aging.t3}</div>
                      <div>Total Open: {totalsText.aging.t4}</div>
                    </Space>
                  </Card>

                  <Table<AgingRow>
                    rowKey={(r) => String(r.businessPartnerId)}
                    loading={agingLoading}
                    columns={agingColumns}
                    dataSource={agingRows}
                    pagination={{ pageSize: 10 }}
                  />
                </Space>
              )
            },
            {
              key: 'glSummary',
              label: 'GL Summary',
              children: (
                <Space direction="vertical" style={{ width: '100%' }}>
                  <Form
                    form={glSummaryForm}
                    layout="vertical"
                    initialValues={{ fromDate: dayjs().startOf('month'), toDate: dayjs().endOf('month') }}
                  >
                    <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr auto', gap: 12, alignItems: 'end' }}>
                      <Form.Item name="fromDate" label="From" rules={[{ required: true }]}>
                        <DatePicker style={{ width: '100%' }} />
                      </Form.Item>
                      <Form.Item name="toDate" label="To" rules={[{ required: true }]}>
                        <DatePicker style={{ width: '100%' }} />
                      </Form.Item>
                      <Button type="primary" onClick={() => void runGlSummary()} disabled={!companyId} loading={glSummaryLoading}>
                        Run
                      </Button>
                    </div>
                  </Form>

                  <Card size="small">
                    <Space wrap>
                      <div>Total Debit: {totalsText.gl.debit}</div>
                      <div>Total Credit: {totalsText.gl.credit}</div>
                    </Space>
                  </Card>

                  <Table<GlSummaryRow>
                    rowKey={(r, idx) => String(r.accountCode || idx)}
                    loading={glSummaryLoading}
                    columns={glSummaryColumns}
                    dataSource={glSummaryRows}
                    pagination={{ pageSize: 10 }}
                  />
                </Space>
              )
            },
            {
              key: 'trial',
              label: 'Trial Balance',
              children: (
                <Space direction="vertical" style={{ width: '100%' }}>
                  <Form form={trialForm} layout="vertical" initialValues={{ fromDate: dayjs().startOf('month'), toDate: dayjs().endOf('month') }}>
                    <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr auto', gap: 12, alignItems: 'end' }}>
                      <Form.Item name="fromDate" label="From" rules={[{ required: true }]}>
                        <DatePicker style={{ width: '100%' }} />
                      </Form.Item>
                      <Form.Item name="toDate" label="To" rules={[{ required: true }]}>
                        <DatePicker style={{ width: '100%' }} />
                      </Form.Item>
                      <Button type="primary" onClick={() => void runTrial()} disabled={!companyId} loading={trialLoading}>
                        Run
                      </Button>
                    </div>
                  </Form>

                  <Card size="small">
                    <Space wrap>
                      <div>Total Debit: {totalsText.trial.debit}</div>
                      <div>Total Credit: {totalsText.trial.credit}</div>
                    </Space>
                  </Card>

                  <Table<TrialBalanceRow>
                    rowKey={(r, idx) => String(r.accountCode || idx)}
                    loading={trialLoading}
                    columns={trialColumns}
                    dataSource={trialRows}
                    pagination={{ pageSize: 10 }}
                  />
                </Space>
              )
            },
            {
              key: 'pl',
              label: 'Profit & Loss',
              children: (
                <Space direction="vertical" style={{ width: '100%' }}>
                  <Form form={plForm} layout="vertical" initialValues={{ fromDate: dayjs().startOf('month'), toDate: dayjs().endOf('month') }}>
                    <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr auto', gap: 12, alignItems: 'end' }}>
                      <Form.Item name="fromDate" label="From" rules={[{ required: true }]}>
                        <DatePicker style={{ width: '100%' }} />
                      </Form.Item>
                      <Form.Item name="toDate" label="To" rules={[{ required: true }]}>
                        <DatePicker style={{ width: '100%' }} />
                      </Form.Item>
                      <Button type="primary" onClick={() => void runPL()} disabled={!companyId} loading={plLoading}>
                        Run
                      </Button>
                    </div>
                  </Form>

                  <Card size="small">
                    <Space wrap>
                      <div>Total Revenue: {totalsText.pl.revenue}</div>
                      <div>Total Expense: {totalsText.pl.expense}</div>
                      <div>Net Income: {totalsText.pl.net}</div>
                    </Space>
                  </Card>

                  <Table<ProfitLossRow>
                    rowKey={(r, idx) => String(r.accountCode || idx)}
                    loading={plLoading}
                    columns={plColumns}
                    dataSource={plRows}
                    pagination={{ pageSize: 10 }}
                  />
                </Space>
              )
            },
            {
              key: 'bs',
              label: 'Balance Sheet',
              children: (
                <Space direction="vertical" style={{ width: '100%' }}>
                  <Form form={bsForm} layout="vertical" initialValues={{ asOfDate: dayjs() }}>
                    <div style={{ display: 'grid', gridTemplateColumns: '1fr auto', gap: 12, alignItems: 'end' }}>
                      <Form.Item name="asOfDate" label="As Of Date (optional)">
                        <DatePicker style={{ width: '100%' }} />
                      </Form.Item>
                      <Button type="primary" onClick={() => void runBS()} disabled={!companyId} loading={bsLoading}>
                        Run
                      </Button>
                    </div>
                  </Form>

                  <Card size="small">
                    <Space wrap>
                      <div>Total Assets: {totalsText.bs.assets}</div>
                      <div>Total Liabilities: {totalsText.bs.liabilities}</div>
                      <div>Total Equity: {totalsText.bs.equity}</div>
                    </Space>
                  </Card>

                  <Table<BalanceSheetRow>
                    rowKey={(r, idx) => String(r.accountCode || idx)}
                    loading={bsLoading}
                    columns={bsColumns}
                    dataSource={bsRows}
                    pagination={{ pageSize: 10 }}
                  />
                </Space>
              )
            }
          ]}
        />
      </Card>
    </Space>
  )
}

// frontend/src/views/modules/finance/ReportsView.vue
<template>
  <div style="display: flex; flex-direction: column; gap: 12px">
    <el-card>
      <div style="display: flex; flex-direction: column; gap: 10px">
        <div style="display: flex; align-items: center; justify-content: space-between; gap: 12px">
          <div>
            <div style="font-size: 18px; font-weight: 600">Finance Reports</div>
            <div style="color: #606266">Aging, GL Summary, Trial Balance, Profit/Loss, Balance Sheet.</div>
          </div>
          <el-button :disabled="!ctx.companyId" @click="runActive">Run</el-button>
        </div>

        <CompanyOrgBar :show-org="false" />
      </div>
    </el-card>

    <el-card>
      <el-alert v-if="!ctx.companyId" title="Pilih company dulu." type="warning" show-icon style="margin-bottom: 12px" />

      <div style="display: flex; gap: 12px; flex-wrap: wrap; margin-bottom: 12px">
        <el-radio-group v-model="active" size="small">
          <el-radio-button label="aging">Aging</el-radio-button>
          <el-radio-button label="gl">GL Summary</el-radio-button>
          <el-radio-button label="tb">Trial Balance</el-radio-button>
          <el-radio-button label="pl">Profit/Loss</el-radio-button>
          <el-radio-button label="bs">Balance Sheet</el-radio-button>
        </el-radio-group>
      </div>

      <div v-if="active === 'aging'" style="display: flex; flex-direction: column; gap: 12px">
        <div style="display: flex; gap: 12px; flex-wrap: wrap; align-items: end">
          <div style="min-width: 220px">
            <div style="color: #606266; font-size: 12px; margin-bottom: 6px">Invoice Type</div>
            <el-select v-model="agingForm.invoiceType" style="width: 220px">
              <el-option label="AR (Receivable)" value="AR" />
              <el-option label="AP (Payable)" value="AP" />
            </el-select>
          </div>
          <div style="min-width: 220px">
            <div style="color: #606266; font-size: 12px; margin-bottom: 6px">As Of Date (optional)</div>
            <el-date-picker v-model="agingForm.asOfDate" type="date" value-format="YYYY-MM-DD" style="width: 220px" clearable />
          </div>
          <el-button type="primary" :disabled="!ctx.companyId" :loading="loading" @click="runAging">Run Aging</el-button>
        </div>

        <div v-if="agingResult" style="display: flex; gap: 8px; flex-wrap: wrap">
          <el-tag type="info">0-30: {{ agingResult.total0To30 }}</el-tag>
          <el-tag type="info">31-60: {{ agingResult.total31To60 }}</el-tag>
          <el-tag type="info">61-90: {{ agingResult.total61To90 }}</el-tag>
          <el-tag type="info">>90: {{ agingResult.totalOver90 }}</el-tag>
          <el-tag type="success">Total Open: {{ agingResult.totalOpen }}</el-tag>
        </div>

        <el-table v-if="agingResult" :data="agingResult.partners || []" style="width: 100%" size="small">
          <el-table-column prop="businessPartnerName" label="Business Partner" min-width="220" />
          <el-table-column prop="bucket0To30" label="0-30" width="140" />
          <el-table-column prop="bucket31To60" label="31-60" width="140" />
          <el-table-column prop="bucket61To90" label="61-90" width="140" />
          <el-table-column prop="bucketOver90" label=">90" width="140" />
          <el-table-column prop="totalOpen" label="Total" width="140" />
        </el-table>

        <el-empty v-else description="Run Aging untuk melihat data." />
      </div>

      <div v-else-if="active === 'gl'" style="display: flex; flex-direction: column; gap: 12px">
        <div style="display: flex; gap: 12px; flex-wrap: wrap; align-items: end">
          <div>
            <div style="color: #606266; font-size: 12px; margin-bottom: 6px">From</div>
            <el-date-picker v-model="range.fromDate" type="date" value-format="YYYY-MM-DD" style="width: 220px" />
          </div>
          <div>
            <div style="color: #606266; font-size: 12px; margin-bottom: 6px">To</div>
            <el-date-picker v-model="range.toDate" type="date" value-format="YYYY-MM-DD" style="width: 220px" />
          </div>
          <el-button type="primary" :disabled="!canRunRange" :loading="loading" @click="runGl">Run GL Summary</el-button>
        </div>

        <div v-if="glResult" style="display: flex; gap: 8px; flex-wrap: wrap">
          <el-tag type="info">Total Debit: {{ glResult.totalDebit }}</el-tag>
          <el-tag type="info">Total Credit: {{ glResult.totalCredit }}</el-tag>
        </div>

        <el-table v-if="glResult" :data="glResult.rows || []" style="width: 100%" size="small">
          <el-table-column prop="accountCode" label="Account" width="180" />
          <el-table-column prop="debitTotal" label="Debit" width="160" />
          <el-table-column prop="creditTotal" label="Credit" width="160" />
          <el-table-column prop="balance" label="Balance" width="160" />
        </el-table>

        <el-empty v-else description="Run GL Summary untuk melihat data." />
      </div>

      <div v-else-if="active === 'tb'" style="display: flex; flex-direction: column; gap: 12px">
        <div style="display: flex; gap: 12px; flex-wrap: wrap; align-items: end">
          <div>
            <div style="color: #606266; font-size: 12px; margin-bottom: 6px">From</div>
            <el-date-picker v-model="range.fromDate" type="date" value-format="YYYY-MM-DD" style="width: 220px" />
          </div>
          <div>
            <div style="color: #606266; font-size: 12px; margin-bottom: 6px">To</div>
            <el-date-picker v-model="range.toDate" type="date" value-format="YYYY-MM-DD" style="width: 220px" />
          </div>
          <el-button type="primary" :disabled="!canRunRange" :loading="loading" @click="runTb">Run Trial Balance</el-button>
        </div>

        <div v-if="tbResult" style="display: flex; gap: 8px; flex-wrap: wrap">
          <el-tag type="info">Total Debit: {{ tbResult.totalDebit }}</el-tag>
          <el-tag type="info">Total Credit: {{ tbResult.totalCredit }}</el-tag>
        </div>

        <el-table v-if="tbResult" :data="tbResult.rows || []" style="width: 100%" size="small">
          <el-table-column prop="accountCode" label="Code" width="160" />
          <el-table-column prop="accountName" label="Name" min-width="220" />
          <el-table-column prop="accountType" label="Type" width="120" />
          <el-table-column prop="debitTotal" label="Debit" width="160" />
          <el-table-column prop="creditTotal" label="Credit" width="160" />
          <el-table-column prop="balance" label="Balance" width="160" />
        </el-table>

        <el-empty v-else description="Run Trial Balance untuk melihat data." />
      </div>

      <div v-else-if="active === 'pl'" style="display: flex; flex-direction: column; gap: 12px">
        <div style="display: flex; gap: 12px; flex-wrap: wrap; align-items: end">
          <div>
            <div style="color: #606266; font-size: 12px; margin-bottom: 6px">From</div>
            <el-date-picker v-model="range.fromDate" type="date" value-format="YYYY-MM-DD" style="width: 220px" />
          </div>
          <div>
            <div style="color: #606266; font-size: 12px; margin-bottom: 6px">To</div>
            <el-date-picker v-model="range.toDate" type="date" value-format="YYYY-MM-DD" style="width: 220px" />
          </div>
          <el-button type="primary" :disabled="!canRunRange" :loading="loading" @click="runPl">Run Profit/Loss</el-button>
        </div>

        <div v-if="plResult" style="display: flex; gap: 8px; flex-wrap: wrap">
          <el-tag type="success">Total Revenue: {{ plResult.totalRevenue }}</el-tag>
          <el-tag type="warning">Total Expense: {{ plResult.totalExpense }}</el-tag>
          <el-tag type="info">Net Income: {{ plResult.netIncome }}</el-tag>
        </div>

        <el-table v-if="plResult" :data="plResult.rows || []" style="width: 100%" size="small">
          <el-table-column prop="accountCode" label="Code" width="160" />
          <el-table-column prop="accountName" label="Name" min-width="220" />
          <el-table-column prop="accountType" label="Type" width="120" />
          <el-table-column prop="amount" label="Amount" width="160" />
        </el-table>

        <el-empty v-else description="Run Profit/Loss untuk melihat data." />
      </div>

      <div v-else style="display: flex; flex-direction: column; gap: 12px">
        <div style="display: flex; gap: 12px; flex-wrap: wrap; align-items: end">
          <div>
            <div style="color: #606266; font-size: 12px; margin-bottom: 6px">As Of Date (optional)</div>
            <el-date-picker v-model="bsForm.asOfDate" type="date" value-format="YYYY-MM-DD" style="width: 220px" clearable />
          </div>
          <el-button type="primary" :disabled="!ctx.companyId" :loading="loading" @click="runBs">Run Balance Sheet</el-button>
        </div>

        <div v-if="bsResult" style="display: flex; gap: 8px; flex-wrap: wrap">
          <el-tag type="success">Assets: {{ bsResult.totalAssets }}</el-tag>
          <el-tag type="warning">Liabilities: {{ bsResult.totalLiabilities }}</el-tag>
          <el-tag type="info">Equity: {{ bsResult.totalEquity }}</el-tag>
        </div>

        <el-table v-if="bsResult" :data="bsResult.rows || []" style="width: 100%" size="small">
          <el-table-column prop="accountCode" label="Code" width="160" />
          <el-table-column prop="accountName" label="Name" min-width="220" />
          <el-table-column prop="accountType" label="Type" width="120" />
          <el-table-column prop="amount" label="Amount" width="160" />
        </el-table>

        <el-empty v-else description="Run Balance Sheet untuk melihat data." />
      </div>
    </el-card>
  </div>
</template>

<script setup>
import { computed, reactive, ref } from 'vue'
import { ElMessage } from 'element-plus'
import { financeApi } from '@/utils/api'
import { useContextStore } from '@/stores/context'
import CompanyOrgBar from '@/views/modules/common/CompanyOrgBar.vue'

const ctx = useContextStore()

const active = ref('aging')
const loading = ref(false)

const range = reactive({
  fromDate: new Date(new Date().getFullYear(), 0, 1).toISOString().slice(0, 10),
  toDate: new Date().toISOString().slice(0, 10)
})

const agingForm = reactive({
  invoiceType: 'AR',
  asOfDate: ''
})

const bsForm = reactive({
  asOfDate: ''
})

const agingResult = ref(null)
const glResult = ref(null)
const tbResult = ref(null)
const plResult = ref(null)
const bsResult = ref(null)

const canRunRange = computed(() => {
  if (!ctx.companyId) return false
  return !!range.fromDate && !!range.toDate
})

async function runAging() {
  if (!ctx.companyId) return
  loading.value = true
  try {
    agingResult.value = await financeApi.agingReport(ctx.companyId, {
      invoiceType: agingForm.invoiceType,
      asOfDate: agingForm.asOfDate || undefined
    })
    glResult.value = null
    tbResult.value = null
    plResult.value = null
    bsResult.value = null
  } catch (e) {
    ElMessage.error(e?.response?.data?.message || e?.message || 'Failed')
  } finally {
    loading.value = false
  }
}

async function runGl() {
  if (!canRunRange.value) return
  loading.value = true
  try {
    glResult.value = await financeApi.glSummaryReport(ctx.companyId, {
      fromDate: range.fromDate,
      toDate: range.toDate
    })
    agingResult.value = null
    tbResult.value = null
    plResult.value = null
    bsResult.value = null
  } catch (e) {
    ElMessage.error(e?.response?.data?.message || e?.message || 'Failed')
  } finally {
    loading.value = false
  }
}

async function runTb() {
  if (!canRunRange.value) return
  loading.value = true
  try {
    tbResult.value = await financeApi.trialBalanceReport(ctx.companyId, {
      fromDate: range.fromDate,
      toDate: range.toDate
    })
    agingResult.value = null
    glResult.value = null
    plResult.value = null
    bsResult.value = null
  } catch (e) {
    ElMessage.error(e?.response?.data?.message || e?.message || 'Failed')
  } finally {
    loading.value = false
  }
}

async function runPl() {
  if (!canRunRange.value) return
  loading.value = true
  try {
    plResult.value = await financeApi.profitLossReport(ctx.companyId, {
      fromDate: range.fromDate,
      toDate: range.toDate
    })
    agingResult.value = null
    glResult.value = null
    tbResult.value = null
    bsResult.value = null
  } catch (e) {
    ElMessage.error(e?.response?.data?.message || e?.message || 'Failed')
  } finally {
    loading.value = false
  }
}

async function runBs() {
  if (!ctx.companyId) return
  loading.value = true
  try {
    bsResult.value = await financeApi.balanceSheetReport(ctx.companyId, {
      asOfDate: bsForm.asOfDate || undefined
    })
    agingResult.value = null
    glResult.value = null
    tbResult.value = null
    plResult.value = null
  } catch (e) {
    ElMessage.error(e?.response?.data?.message || e?.message || 'Failed')
  } finally {
    loading.value = false
  }
}

function runActive() {
  if (active.value === 'aging') return runAging()
  if (active.value === 'gl') return runGl()
  if (active.value === 'tb') return runTb()
  if (active.value === 'pl') return runPl()
  return runBs()
}
</script>
