// frontend/src/views/modules/masterdata/ProductsView.vue
<template>
  <div style="display: flex; flex-direction: column; gap: 12px">
    <el-card>
      <div style="display: flex; flex-direction: column; gap: 10px">
        <div style="display: flex; align-items: center; justify-content: space-between; gap: 12px">
          <div>
            <div style="font-size: 18px; font-weight: 600">Products</div>
            <div style="color: #606266">Master produk untuk transaksi Purchase/Sales/Manufacturing.</div>
          </div>
          <el-button type="primary" :disabled="!ctx.companyId" @click="openCreate">Create Product</el-button>
        </div>

        <CompanyOrgBar :show-org="false" />
      </div>
    </el-card>

    <el-card>
      <el-alert v-if="!ctx.companyId" title="Pilih company dulu." type="warning" show-icon style="margin-bottom: 12px" />

      <el-table :data="rows" style="width: 100%" v-loading="loading">
        <el-table-column prop="id" label="ID" width="90" />
        <el-table-column prop="code" label="Code" width="160" />
        <el-table-column prop="name" label="Name" />
        <el-table-column prop="uomId" label="UoM" width="160">
          <template #default="scope">
            <span>
              {{ (uoms || []).find((x) => x.id === scope.row.uomId)?.name || (uoms || []).find((x) => x.id === scope.row.uomId)?.code || scope.row.uomId }}
            </span>
          </template>
        </el-table-column>
        <el-table-column prop="active" label="Active" width="100">
          <template #default="scope">
            <el-tag size="small" :type="scope.row.active ? 'success' : 'info'">{{ scope.row.active ? 'Yes' : 'No' }}</el-tag>
          </template>
        </el-table-column>
        <el-table-column label="Action" width="200">
          <template #default="scope">
            <div style="display: flex; gap: 8px">
              <el-button size="small" :disabled="!ctx.companyId" @click="openEdit(scope.row)">Edit</el-button>
              <el-button size="small" type="danger" plain :disabled="!ctx.companyId" @click="onDelete(scope.row)">Delete</el-button>
            </div>
          </template>
        </el-table-column>
      </el-table>
    </el-card>

    <el-dialog v-model="createOpen" title="Create Product" width="600px">
      <el-form label-position="top">
        <el-form-item label="Code">
          <el-input v-model="form.code" placeholder="e.g. PRD-001" />
        </el-form-item>
        <el-form-item label="Name">
          <el-input v-model="form.name" placeholder="e.g. Item A" />
        </el-form-item>
        <el-form-item label="UoM">
          <el-select v-model="form.uomId" filterable placeholder="Select UoM" style="width: 100%" :disabled="uoms.length === 0">
            <el-option v-for="u in uoms" :key="u.id" :label="u.name || u.code || String(u.id)" :value="u.id" />
          </el-select>
          <div v-if="uoms.length === 0" style="color: #909399; font-size: 12px; margin-top: 6px">
            UoM belum ada. Buat UoM dulu di Master Data.
          </div>
        </el-form-item>
      </el-form>

      <template #footer>
        <el-button @click="createOpen = false">Cancel</el-button>
        <el-button type="primary" :loading="saving" :disabled="!ctx.companyId || !form.uomId" @click="save">Save</el-button>
      </template>
    </el-dialog>

    <el-dialog v-model="editOpen" title="Edit Product" width="600px">
      <el-form label-position="top">
        <el-form-item label="Code">
          <el-input v-model="editForm.code" placeholder="e.g. PRD-001" />
        </el-form-item>
        <el-form-item label="Name">
          <el-input v-model="editForm.name" placeholder="e.g. Item A" />
        </el-form-item>
        <el-form-item label="UoM">
          <el-select v-model="editForm.uomId" filterable placeholder="Select UoM" style="width: 100%" :disabled="uoms.length === 0">
            <el-option v-for="u in uoms" :key="u.id" :label="u.name || u.code || String(u.id)" :value="u.id" />
          </el-select>
        </el-form-item>
        <el-form-item label="Active">
          <el-switch v-model="editForm.active" />
        </el-form-item>
      </el-form>

      <template #footer>
        <el-button @click="editOpen = false">Cancel</el-button>
        <el-button type="primary" :loading="editSaving" :disabled="!canEditSave" @click="saveEdit">Save</el-button>
      </template>
    </el-dialog>
  </div>
</template>

<script setup>
import { computed, onMounted, reactive, ref, watch } from 'vue'
import { ElMessage, ElMessageBox } from 'element-plus'
import { masterDataApi } from '@/utils/api'
import { useContextStore } from '@/stores/context'
import CompanyOrgBar from '@/views/modules/common/CompanyOrgBar.vue'

const ctx = useContextStore()

const rows = ref([])
const uoms = ref([])
const loading = ref(false)

const createOpen = ref(false)
const saving = ref(false)

const editOpen = ref(false)
const editSaving = ref(false)
const editingId = ref(null)

const form = reactive({
  code: '',
  name: '',
  uomId: null
})

const editForm = reactive({
  code: '',
  name: '',
  uomId: null,
  active: true
})

const canEditSave = computed(() => Boolean(ctx.companyId && editingId.value && editForm.code.trim() && editForm.name.trim() && editForm.uomId))

async function load() {
  if (!ctx.companyId) {
    rows.value = []
    uoms.value = []
    return
  }
  loading.value = true
  try {
    ;[rows.value, uoms.value] = await Promise.all([masterDataApi.listProducts(ctx.companyId), masterDataApi.listUoms(ctx.companyId)])
  } finally {
    loading.value = false
  }
}

function openCreate() {
  form.code = ''
  form.name = ''
  form.uomId = uoms.value[0]?.id || null
  createOpen.value = true
}

function openEdit(row) {
  if (!row?.id) return
  editingId.value = row.id
  editForm.code = row.code || ''
  editForm.name = row.name || ''
  editForm.uomId = row.uomId || null
  editForm.active = Boolean(row.active)
  editOpen.value = true
}

async function save() {
  saving.value = true
  try {
    await masterDataApi.createProduct(ctx.companyId, { code: form.code, name: form.name, uomId: form.uomId })
    ElMessage.success('Product created')
    createOpen.value = false
    await load()
  } catch (e) {
    ElMessage.error(e?.response?.data?.message || e?.message || 'Failed')
  } finally {
    saving.value = false
  }
}

async function saveEdit() {
  editSaving.value = true
  try {
    await masterDataApi.updateProduct(ctx.companyId, editingId.value, {
      code: editForm.code,
      name: editForm.name,
      uomId: editForm.uomId,
      active: Boolean(editForm.active)
    })
    ElMessage.success('Product updated')
    editOpen.value = false
    await load()
  } catch (e) {
    ElMessage.error(e?.response?.data?.message || e?.message || 'Failed')
  } finally {
    editSaving.value = false
  }
}

async function onDelete(row) {
  if (!row?.id) return
  try {
    await ElMessageBox.confirm(`Delete Product "${row.code}"?`, 'Confirm', {
      type: 'warning',
      confirmButtonText: 'Delete',
      cancelButtonText: 'Cancel'
    })
    await masterDataApi.deleteProduct(ctx.companyId, row.id)
    ElMessage.success('Product deleted')
    await load()
  } catch (e) {
    if (e === 'cancel' || e === 'close') return
    ElMessage.error(e?.response?.data?.message || e?.message || 'Failed')
  }
}

watch(
  () => ctx.companyId,
  () => load()
)

onMounted(load)
</script>

// frontend2_new/src/views/modules/masterdata/ProductsView.tsx
import { Button, Card, Form, Input, Modal, Popconfirm, Select, Space, Switch, Table, Tag, Typography, message } from 'antd'
import type { ColumnsType } from 'antd/es/table'
import { useEffect, useMemo, useState } from 'react'
import { coreApi, masterDataApi } from '@/utils/api'
import { useContextStore } from '@/stores/context'

type CompanyRow = {
  id: number
  code?: string
  name?: string
}

type UomRow = {
  id: number
  code?: string
  name?: string
}

type ProductRow = {
  id: number
  code?: string
  name?: string
  uomId?: number
  active?: boolean
}

export default function ProductsView() {
  const companyId = useContextStore((s) => s.companyId)
  const setCompanyId = useContextStore((s) => s.setCompanyId)

  const [companyLoading, setCompanyLoading] = useState(false)
  const [companies, setCompanies] = useState<CompanyRow[]>([])

  const [uomLoading, setUomLoading] = useState(false)
  const [uoms, setUoms] = useState<UomRow[]>([])

  const [loading, setLoading] = useState(false)
  const [rows, setRows] = useState<ProductRow[]>([])

  const [q, setQ] = useState('')

  const [open, setOpen] = useState(false)
  const [editing, setEditing] = useState<ProductRow | null>(null)
  const [form] = Form.useForm()

  const loadCompanies = async () => {
    setCompanyLoading(true)
    try {
      const res = await coreApi.listCompanies()
      setCompanies((res || []) as CompanyRow[])
      if (!companyId && Array.isArray(res) && res.length > 0) {
        setCompanyId((res[0] as any).id ?? null)
      }
    } catch (e: any) {
      message.error(e?.message || 'Failed to load companies')
    } finally {
      setCompanyLoading(false)
    }
  }

  const loadUoms = async (cid: number) => {
    setUomLoading(true)
    try {
      const res = await masterDataApi.listUoms(cid)
      setUoms((res || []) as UomRow[])
    } catch (e: any) {
      message.error(e?.message || 'Failed to load UoMs')
    } finally {
      setUomLoading(false)
    }
  }

  const load = async (cid: number) => {
    setLoading(true)
    try {
      const res = await masterDataApi.listProducts(cid)
      setRows((res || []) as ProductRow[])
    } catch (e: any) {
      message.error(e?.message || 'Failed to load products')
    } finally {
      setLoading(false)
    }
  }

  useEffect(() => {
    void loadCompanies()
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [])

  useEffect(() => {
    if (!companyId) return
    void loadUoms(companyId)
    void load(companyId)
  }, [companyId])

  const uomLabelById = useMemo(() => {
    const m = new Map<number, string>()
    for (const u of uoms) m.set(u.id, `${u.code || u.id} - ${u.name || ''}`)
    return m
  }, [uoms])

  const filtered = useMemo(() => {
    const qq = q.trim().toLowerCase()
    if (!qq) return rows
    return rows.filter((r) => `${r.code || ''} ${r.name || ''}`.toLowerCase().includes(qq))
  }, [q, rows])

  const columns: ColumnsType<ProductRow> = useMemo(
    () => [
      { title: 'ID', dataIndex: 'id', width: 90 },
      { title: 'Code', dataIndex: 'code', width: 160 },
      { title: 'Name', dataIndex: 'name' },
      {
        title: 'UoM',
        dataIndex: 'uomId',
        width: 220,
        render: (v: number) => uomLabelById.get(v) || v
      },
      {
        title: 'Active',
        dataIndex: 'active',
        width: 100,
        render: (v: boolean) => (v ? <Tag color="green">YES</Tag> : <Tag color="red">NO</Tag>)
      },
      {
        title: 'Actions',
        key: 'actions',
        width: 180,
        render: (_, r) => (
          <Space>
            <Button
              size="small"
              onClick={() => {
                setEditing(r)
                setOpen(true)
                form.setFieldsValue({ code: r.code, name: r.name, uomId: r.uomId, active: r.active })
              }}
            >
              Edit
            </Button>
            <Popconfirm
              title="Delete product?"
              okText="Delete"
              okButtonProps={{ danger: true }}
              onConfirm={async () => {
                if (!companyId) return
                try {
                  await masterDataApi.deleteProduct(companyId, r.id)
                  message.success('Deleted')
                  await load(companyId)
                } catch (e: any) {
                  message.error(e?.message || 'Failed to delete')
                }
              }}
            >
              <Button size="small" danger>
                Delete
              </Button>
            </Popconfirm>
          </Space>
        )
      }
    ],
    [companyId, form, uomLabelById]
  )

  return (
    <Space direction="vertical" size={16} style={{ width: '100%' }}>
      <Card>
        <Space style={{ width: '100%', justifyContent: 'space-between' }}>
          <Typography.Title level={4} style={{ margin: 0 }}>
            Products
          </Typography.Title>
          <Space>
            <Button onClick={() => loadCompanies()} loading={companyLoading}>
              Refresh Companies
            </Button>
            <Button onClick={() => companyId && loadUoms(companyId)} disabled={!companyId} loading={uomLoading}>
              Refresh UoMs
            </Button>
            <Button onClick={() => companyId && load(companyId)} disabled={!companyId} loading={loading}>
              Refresh
            </Button>
            <Button
              type="primary"
              onClick={() => {
                setEditing(null)
                setOpen(true)
                form.setFieldsValue({ active: true })
              }}
              disabled={!companyId}
            >
              New
            </Button>
          </Space>
        </Space>
      </Card>

      <Card>
        <Space direction="vertical" size={12} style={{ width: '100%' }}>
          <Space wrap>
            <div style={{ minWidth: 320 }}>
              <Typography.Text strong>Company</Typography.Text>
              <Select
                style={{ width: '100%' }}
                loading={companyLoading}
                value={companyId ?? undefined}
                placeholder="Select company"
                options={companies.map((c) => ({ value: c.id, label: `${c.code || c.id} - ${c.name || ''}` }))}
                onChange={(v) => setCompanyId(v)}
              />
            </div>

            <div style={{ minWidth: 260 }}>
              <Typography.Text strong>Search</Typography.Text>
              <Input value={q} onChange={(e) => setQ(e.target.value)} placeholder="code/name" allowClear />
            </div>
          </Space>

          <Table<ProductRow> rowKey="id" loading={loading} columns={columns} dataSource={filtered} pagination={{ pageSize: 10 }} />
        </Space>
      </Card>

      <Modal
        title={editing ? 'Edit Product' : 'Create Product'}
        open={open}
        onCancel={() => {
          setOpen(false)
          setEditing(null)
          form.resetFields()
        }}
        onOk={async () => {
          if (!companyId) return
          try {
            const values = await form.validateFields()
            if (editing) {
              await masterDataApi.updateProduct(companyId, editing.id, values)
              message.success('Updated')
            } else {
              await masterDataApi.createProduct(companyId, values)
              message.success('Created')
            }
            setOpen(false)
            setEditing(null)
            form.resetFields()
            await load(companyId)
          } catch (e: any) {
            if (e?.errorFields) return
            message.error(e?.message || 'Save failed')
          }
        }}
        okText={editing ? 'Save' : 'Create'}
      >
        <Form layout="vertical" form={form} initialValues={{ active: true }}>
          <Form.Item name="code" label="Code" rules={[{ required: true, message: 'Code is required' }]}>
            <Input />
          </Form.Item>
          <Form.Item name="name" label="Name" rules={[{ required: true, message: 'Name is required' }]}>
            <Input />
          </Form.Item>
          <Form.Item name="uomId" label="UoM" rules={[{ required: true, message: 'UoM is required' }]}>
            <Select
              loading={uomLoading}
              placeholder="Select UoM"
              options={uoms.map((u) => ({ value: u.id, label: `${u.code || u.id} - ${u.name || ''}` }))}
            />
          </Form.Item>
          <Form.Item name="active" label="Active" valuePropName="checked">
            <Switch />
          </Form.Item>
        </Form>
      </Modal>
    </Space>
  )
}
