// frontend2/src/views/auth/LoginView.tsx
import { Button, Card, Form, Input, Typography } from 'antd'
import { useState } from 'react'
import { useNavigate } from 'react-router-dom'
import { useAuthStore } from '@/stores/auth'

export default function LoginView() {
  const navigate = useNavigate()
  const login = useAuthStore((s) => s.login)
  const [loading, setLoading] = useState(false)

  return (
    <Card style={{ width: 420 }}>
      <Typography.Title level={3} style={{ marginTop: 0 }}>
        Login
      </Typography.Title>

      <Form
        layout="vertical"
        onFinish={async (values) => {
          setLoading(true)
          try {
            await login({ email: values.email, password: values.password })
            navigate('/')
          } finally {
            setLoading(false)
          }
        }}
      >
        <Form.Item name="email" label="Email" rules={[{ required: true }]}>
          <Input />
        </Form.Item>
        <Form.Item name="password" label="Password" rules={[{ required: true }]}>
          <Input.Password />
        </Form.Item>
        <Button type="primary" htmlType="submit" loading={loading} block>
          Sign In
        </Button>
      </Form>
    </Card>
  )
}

// frontend/src/views/auth/LoginView.vue
<template>
  <el-card>
    <div style="font-size: 18px; font-weight: 600; margin-bottom: 12px">Sign in</div>

    <el-form :model="form" label-position="top" @submit.prevent>
      <el-form-item label="Email">
        <el-input v-model="form.email" autocomplete="username" />
      </el-form-item>
      <el-form-item label="Password">
        <el-input v-model="form.password" type="password" autocomplete="current-password" show-password />
      </el-form-item>

      <el-alert v-if="error" :title="error" type="error" show-icon style="margin-bottom: 12px" />

      <el-button type="primary" :loading="loading" style="width: 100%" @click="onSubmit">Login</el-button>
    </el-form>
  </el-card>
</template>

<script setup>
import { reactive, ref } from 'vue'
import { useRouter } from 'vue-router'
import { useAuthStore } from '@/stores/auth'

const router = useRouter()
const auth = useAuthStore()

const form = reactive({
  email: '',
  password: ''
})

const loading = ref(false)
const error = ref('')

async function onSubmit() {
  loading.value = true
  error.value = ''
  try {
    await auth.login({ email: form.email, password: form.password })
    router.push('/')
  } catch (e) {
    error.value = e?.response?.data?.message || e?.message || 'Login failed'
  } finally {
    loading.value = false
  }
}
</script>
