// frontend2_new/src/views/modules/manufacturing/BomsView.tsx
import { Button, Card, Form, InputNumber, Modal, Popconfirm, Select, Space, Switch, Table, Tag, Typography, message } from 'antd'
import type { ColumnsType } from 'antd/es/table'
import { useEffect, useMemo, useState } from 'react'
import { coreApi, manufacturingApi, masterDataApi } from '@/utils/api'
import { useContextStore } from '@/stores/context'
import { getApiErrorMessage } from '@/utils/error'

type CompanyRow = { id: number; code?: string; name?: string }

type OrgRow = { id: number; code?: string; name?: string }

type ProductRow = { id: number; code?: string; name?: string }

type BomLineRow = { id?: number; componentProductId?: number; qty?: any }

type BomRow = {
  id: number
  orgId?: number | null
  productId?: number
  version?: number
  active?: boolean
  lines?: BomLineRow[]
}

export default function BomsView() {
  const companyId = useContextStore((s) => s.companyId)
  const setCompanyId = useContextStore((s) => s.setCompanyId)

  const [companyLoading, setCompanyLoading] = useState(false)
  const [companies, setCompanies] = useState<CompanyRow[]>([])

  const [lookupLoading, setLookupLoading] = useState(false)
  const [orgs, setOrgs] = useState<OrgRow[]>([])
  const [products, setProducts] = useState<ProductRow[]>([])

  const [loading, setLoading] = useState(false)
  const [rows, setRows] = useState<BomRow[]>([])

  const [open, setOpen] = useState(false)
  const [editing, setEditing] = useState<BomRow | null>(null)
  const [form] = Form.useForm()

  const loadCompanies = async () => {
    setCompanyLoading(true)
    try {
      const res = await coreApi.listCompanies()
      setCompanies(res || [])
      if (!companyId && Array.isArray(res) && res.length > 0) setCompanyId(res[0]?.id)
    } catch (e: any) {
      message.error(getApiErrorMessage(e, 'Failed to load companies'))
    } finally {
      setCompanyLoading(false)
    }
  }

  const loadLookups = async (cid: number) => {
    setLookupLoading(true)
    try {
      const [orgRes, prodRes] = await Promise.all([coreApi.listOrgs(cid), masterDataApi.listProducts(cid)])
      setOrgs(orgRes || [])
      setProducts(prodRes || [])
    } catch (e: any) {
      message.error(getApiErrorMessage(e, 'Failed to load lookups'))
      setOrgs([])
      setProducts([])
    } finally {
      setLookupLoading(false)
    }
  }

  const load = async (cid: number) => {
    setLoading(true)
    try {
      const res = await manufacturingApi.listBoms(cid)
      setRows(res || [])
    } catch (e: any) {
      message.error(getApiErrorMessage(e, 'Failed to load BOMs'))
      setRows([])
    } finally {
      setLoading(false)
    }
  }

  useEffect(() => {
    void loadCompanies()
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [])

  useEffect(() => {
    if (!companyId) return
    void loadLookups(companyId)
    void load(companyId)
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [companyId])

  const companyOptions = useMemo(
    () => companies.map((c) => ({ value: c.id, label: `${c.code || c.id} - ${c.name || ''}` })),
    [companies]
  )

  const orgOptions = useMemo(
    () => orgs.map((o) => ({ value: o.id, label: `${o.code || o.id} - ${o.name || ''}` })),
    [orgs]
  )

  const productOptions = useMemo(
    () => products.map((p) => ({ value: p.id, label: `${p.code || p.id} - ${p.name || ''}` })),
    [products]
  )

  const productLabelById = useMemo(() => {
    const m = new Map<number, string>()
    for (const p of products) m.set(p.id, `${p.code || p.id} - ${p.name || ''}`)
    return m
  }, [products])

  const columns: ColumnsType<BomRow> = [
    { title: 'ID', dataIndex: 'id', width: 90 },
    {
      title: 'Product',
      dataIndex: 'productId',
      render: (v: any) => productLabelById.get(Number(v)) || v
    },
    { title: 'Version', dataIndex: 'version', width: 110 },
    {
      title: 'Active',
      dataIndex: 'active',
      width: 110,
      render: (v: any) => (v ? <Tag color="green">YES</Tag> : <Tag color="red">NO</Tag>)
    },
    {
      title: 'Actions',
      key: 'actions',
      width: 260,
      render: (_, r) => (
        <Space>
          <Button
            size="small"
            onClick={async () => {
              if (!companyId) return
              try {
                const full = await manufacturingApi.getBom(companyId, r.id)
                setEditing(full)
                form.resetFields()
                form.setFieldsValue({
                  orgId: full?.orgId ?? null,
                  productId: full?.productId,
                  version: full?.version,
                  active: Boolean(full?.active),
                  lines: (full?.lines || []).map((ln: any) => ({ componentProductId: ln.componentProductId, qty: ln.qty }))
                })
                if (!(full?.lines || []).length) {
                  form.setFieldsValue({ lines: [{ componentProductId: products[0]?.id ?? null, qty: 1 }] })
                }
                setOpen(true)
              } catch (e: any) {
                message.error(getApiErrorMessage(e, 'Failed to load BOM'))
              }
            }}
          >
            Edit
          </Button>
          <Popconfirm
            title="Delete BOM?"
            okText="Delete"
            okButtonProps={{ danger: true }}
            onConfirm={async () => {
              if (!companyId) return
              try {
                await manufacturingApi.deleteBom(companyId, r.id)
                message.success('Deleted')
                await load(companyId)
              } catch (e: any) {
                message.error(getApiErrorMessage(e, 'Failed to delete BOM'))
              }
            }}
          >
            <Button size="small" danger>
              Delete
            </Button>
          </Popconfirm>
          <Button
            size="small"
            onClick={() => {
              Modal.info({
                title: `Lines - BOM ${r.id}`,
                width: 860,
                content: (
                  <Table
                    size="small"
                    rowKey={(x: any, idx) => String(x?.id || idx)}
                    pagination={false}
                    columns={[
                      {
                        title: 'Component',
                        dataIndex: 'componentProductId',
                        render: (v: any) => productLabelById.get(Number(v)) || v
                      },
                      { title: 'Qty', dataIndex: 'qty', width: 160 }
                    ]}
                    dataSource={r.lines || []}
                  />
                )
              })
            }}
          >
            Lines
          </Button>
        </Space>
      )
    }
  ]

  const resetNew = () => {
    setEditing(null)
    form.resetFields()
    form.setFieldsValue({
      orgId: null,
      productId: products[0]?.id ?? null,
      version: 1,
      active: true,
      lines: [{ componentProductId: products[0]?.id ?? null, qty: 1 }]
    })
  }

  return (
    <Space direction="vertical" size={16} style={{ width: '100%' }}>
      <Card>
        <Space style={{ width: '100%', justifyContent: 'space-between' }}>
          <Typography.Title level={4} style={{ margin: 0 }}>
            BOMs
          </Typography.Title>
          <Space>
            <Button onClick={() => companyId && loadLookups(companyId)} disabled={!companyId} loading={lookupLoading}>
              Refresh Lookups
            </Button>
            <Button onClick={() => companyId && load(companyId)} disabled={!companyId} loading={loading}>
              Refresh
            </Button>
            <Button
              type="primary"
              disabled={!companyId}
              onClick={() => {
                resetNew()
                setOpen(true)
              }}
            >
              New BOM
            </Button>
          </Space>
        </Space>
      </Card>

      <Card>
        <Space wrap style={{ width: '100%' }}>
          <div style={{ minWidth: 320 }}>
            <Typography.Text strong>Company</Typography.Text>
            <Select
              style={{ width: '100%' }}
              loading={companyLoading}
              value={companyId ?? undefined}
              placeholder="Select company"
              options={companyOptions}
              onChange={(v) => setCompanyId(v)}
            />
          </div>
        </Space>
      </Card>

      <Card>
        <Table<BomRow> rowKey="id" loading={loading} columns={columns} dataSource={rows} pagination={{ pageSize: 10 }} />
      </Card>

      <Modal
        open={open}
        title={editing ? `Edit BOM - ${editing.id}` : 'Create BOM'}
        width={980}
        onCancel={() => setOpen(false)}
        okText={editing ? 'Update' : 'Create'}
        onOk={async () => {
          if (!companyId) return
          try {
            const values = await form.validateFields()
            const payload: any = {
              orgId: values.orgId ?? null,
              productId: values.productId,
              version: values.version,
              active: Boolean(values.active),
              lines: (values.lines || []).map((l: any) => ({ componentProductId: l.componentProductId, qty: l.qty }))
            }
            if (!payload.orgId) delete payload.orgId

            if (editing) {
              await manufacturingApi.updateBom(companyId, editing.id, payload)
              message.success('Updated')
            } else {
              await manufacturingApi.createBom(companyId, payload)
              message.success('Created')
            }
            setOpen(false)
            await load(companyId)
          } catch (e: any) {
            if (e?.errorFields) return
            message.error(getApiErrorMessage(e, editing ? 'Failed to update BOM' : 'Failed to create BOM'))
          }
        }}
      >
        <Form form={form} layout="vertical" initialValues={{ orgId: null, active: true, version: 1 }}>
          <Space wrap style={{ width: '100%' }}>
            <Form.Item name="orgId" label="Org (optional)" style={{ width: 260 }}>
              <Select allowClear showSearch optionFilterProp="label" loading={lookupLoading} options={orgOptions} />
            </Form.Item>

            <Form.Item name="productId" label="Finished Product" rules={[{ required: true }]} style={{ width: 380 }}>
              <Select showSearch optionFilterProp="label" loading={lookupLoading} options={productOptions} />
            </Form.Item>

            <Form.Item name="version" label="Version" rules={[{ required: true }]} style={{ width: 160 }}>
              <InputNumber style={{ width: '100%' }} min={1} />
            </Form.Item>

            <Form.Item name="active" label="Active" valuePropName="checked" style={{ width: 120 }}>
              <Switch />
            </Form.Item>
          </Space>

          <Typography.Title level={5}>Lines</Typography.Title>
          <Form.List name="lines">
            {(fields, { add, remove }) => (
              <Space direction="vertical" style={{ width: '100%' }} size={8}>
                {fields.map((field) => (
                  <Space key={field.key} align="baseline" wrap style={{ width: '100%' }}>
                    <Form.Item
                      {...field}
                      name={[field.name, 'componentProductId']}
                      label="Component Product"
                      rules={[{ required: true }]}
                      style={{ width: 520 }}
                    >
                      <Select showSearch optionFilterProp="label" loading={lookupLoading} options={productOptions} />
                    </Form.Item>

                    <Form.Item {...field} name={[field.name, 'qty']} label="Qty" rules={[{ required: true }]} style={{ width: 180 }}>
                      <InputNumber style={{ width: '100%' }} min={0.0001} />
                    </Form.Item>

                    <Button danger onClick={() => remove(field.name)} disabled={fields.length <= 1}>
                      Remove
                    </Button>
                  </Space>
                ))}

                <Button onClick={() => add({ componentProductId: products[0]?.id ?? null, qty: 1 })}>Add Line</Button>
              </Space>
            )}
          </Form.List>
        </Form>
      </Modal>
    </Space>
  )
}

// frontend/src/views/modules/manufacturing/BomsView.vue
<template>
  <div style="display: flex; flex-direction: column; gap: 12px">
    <el-card>
      <div style="display: flex; flex-direction: column; gap: 10px">
        <div style="display: flex; align-items: center; justify-content: space-between; gap: 12px">
          <div>
            <div style="font-size: 18px; font-weight: 600">BOMs</div>
            <div style="color: #606266">Bill of Materials untuk produksi (finished good + komponen).</div>
          </div>
          <el-button type="primary" :disabled="!ctx.companyId" @click="openCreate">Create BOM</el-button>
        </div>

        <CompanyOrgBar />
      </div>
    </el-card>

    <el-card>
      <el-alert v-if="!ctx.companyId" title="Pilih company dulu." type="warning" show-icon style="margin-bottom: 12px" />

      <el-table :data="rows" style="width: 100%" v-loading="loading">
        <el-table-column prop="id" label="ID" width="90" />
        <el-table-column label="Finished Product" min-width="260">
          <template #default="scope">
            <span>{{ productLabel(scope.row.productId) }}</span>
          </template>
        </el-table-column>
        <el-table-column prop="version" label="Version" width="110" />
        <el-table-column prop="active" label="Active" width="110">
          <template #default="scope">
            <el-tag size="small" :type="scope.row.active ? 'success' : 'info'">{{ scope.row.active ? 'Yes' : 'No' }}</el-tag>
          </template>
        </el-table-column>
        <el-table-column label="Lines" width="110">
          <template #default="scope">
            <span>{{ (scope.row.lines || []).length }}</span>
          </template>
        </el-table-column>
        <el-table-column label="Action" width="180">
          <template #default="scope">
            <el-button size="small" @click="openEdit(scope.row)" :disabled="!ctx.companyId">Edit</el-button>
            <el-button type="danger" size="small" plain @click="onDelete(scope.row)" :disabled="!ctx.companyId">Delete</el-button>
          </template>
        </el-table-column>
      </el-table>
    </el-card>

    <el-dialog v-model="createOpen" :title="dialogTitle" width="980px">
      <el-form label-position="top">
        <div style="display: grid; grid-template-columns: 1fr 1fr 1fr; gap: 12px">
          <el-form-item label="Finished Product">
            <el-select v-model="form.productId" filterable placeholder="Select product" style="width: 100%" :disabled="products.length === 0">
              <el-option v-for="p in products" :key="p.id" :label="`${p.code} - ${p.name}`" :value="p.id" />
            </el-select>
          </el-form-item>
          <el-form-item label="Version">
            <el-input v-model="form.version" placeholder="e.g. 1" />
          </el-form-item>
          <el-form-item label="Active">
            <el-switch v-model="form.active" />
          </el-form-item>
        </div>

        <el-form-item label="Org">
          <el-input v-model="form.orgId" placeholder="Auto from context" :disabled="true" />
        </el-form-item>

        <div style="display: flex; align-items: center; justify-content: space-between; margin: 12px 0 6px">
          <div style="font-weight: 600">Components</div>
          <el-button size="small" @click="addLine">Add Line</el-button>
        </div>

        <el-table :data="form.lines" size="small" style="width: 100%">
          <el-table-column label="Component Product" min-width="320">
            <template #default="scope">
              <el-select v-model="scope.row.componentProductId" filterable placeholder="Select component" style="width: 100%" :disabled="products.length === 0">
                <el-option v-for="p in products" :key="p.id" :label="`${p.code} - ${p.name}`" :value="p.id" />
              </el-select>
            </template>
          </el-table-column>
          <el-table-column label="Qty" width="180">
            <template #default="scope">
              <el-input v-model="scope.row.qty" placeholder="e.g. 2" />
            </template>
          </el-table-column>
          <el-table-column label="" width="70">
            <template #default="scope">
              <el-button type="danger" plain size="small" @click="removeLine(scope.$index)">X</el-button>
            </template>
          </el-table-column>
        </el-table>

        <el-alert v-if="products.length === 0" title="Product belum ada. Buat Product dulu di Master Data." type="warning" show-icon style="margin-top: 12px" />
      </el-form>

      <template #footer>
        <el-button @click="createOpen = false">Cancel</el-button>
        <el-button type="primary" :loading="saving" :disabled="!canSave" @click="save">Save</el-button>
      </template>
    </el-dialog>
  </div>
</template>

<script setup>
import { computed, onMounted, reactive, ref, watch } from 'vue'
import { ElMessage, ElMessageBox } from 'element-plus'
import { manufacturingApi, masterDataApi } from '@/utils/api'
import { useContextStore } from '@/stores/context'
import CompanyOrgBar from '@/views/modules/common/CompanyOrgBar.vue'

const ctx = useContextStore()

const rows = ref([])
const loading = ref(false)

const products = ref([])

const createOpen = ref(false)
const saving = ref(false)

const editMode = ref('create')
const editingId = ref(null)

const dialogTitle = computed(() => (editMode.value === 'edit' ? 'Edit BOM' : 'Create BOM'))

const form = reactive({
  orgId: null,
  productId: null,
  version: '1',
  active: true,
  lines: []
})

const canSave = computed(() => {
  if (!ctx.companyId) return false
  if (!form.productId) return false
  const v = Number(form.version)
  if (!Number.isFinite(v) || v <= 0) return false
  if (!Array.isArray(form.lines) || form.lines.length === 0) return false
  return form.lines.every((l) => l.componentProductId && String(l.qty).trim())
})

function productLabel(id) {
  if (!id) return ''
  const p = products.value.find((x) => x.id === id)
  if (!p) return String(id)
  return `${p.code} - ${p.name}`
}

function addLine() {
  form.lines.push({
    componentProductId: products.value[0]?.id || null,
    qty: '1'
  })
}

function removeLine(idx) {
  form.lines.splice(idx, 1)
}

async function loadLookups() {
  if (!ctx.companyId) {
    products.value = []
    return
  }
  try {
    products.value = await masterDataApi.listProducts(ctx.companyId)
  } catch {
    products.value = []
  }
}

async function load() {
  if (!ctx.companyId) {
    rows.value = []
    return
  }
  loading.value = true
  try {
    rows.value = await manufacturingApi.listBoms(ctx.companyId)
  } catch (e) {
    ElMessage.error(e?.response?.data?.message || e?.message || 'Failed')
  } finally {
    loading.value = false
  }
}

function openCreate() {
  editMode.value = 'create'
  editingId.value = null
  form.orgId = ctx.orgId
  form.productId = products.value[0]?.id || null
  form.version = '1'
  form.active = true
  form.lines = []
  addLine()
  createOpen.value = true
}

function openEdit(row) {
  if (!row?.id) return
  editMode.value = 'edit'
  editingId.value = row.id
  form.orgId = row.orgId || null
  form.productId = row.productId || null
  form.version = String(row.version ?? '1')
  form.active = !!row.active
  form.lines = (row.lines || []).map((l) => ({
    componentProductId: l.componentProductId,
    qty: String(l.qty ?? '')
  }))
  if (form.lines.length === 0) addLine()
  createOpen.value = true
}

async function save() {
  saving.value = true
  try {
    const payload = {
      orgId: form.orgId || null,
      productId: form.productId,
      version: Number(form.version),
      active: !!form.active,
      lines: form.lines.map((l) => ({
        componentProductId: l.componentProductId,
        qty: l.qty
      }))
    }

    if (editMode.value === 'edit' && editingId.value) {
      await manufacturingApi.updateBom(ctx.companyId, editingId.value, payload)
      ElMessage.success('BOM updated')
    } else {
      await manufacturingApi.createBom(ctx.companyId, payload)
      ElMessage.success('BOM created')
    }
    createOpen.value = false
    await load()
  } catch (e) {
    ElMessage.error(e?.response?.data?.message || e?.message || 'Failed')
  } finally {
    saving.value = false
  }
}

async function onDelete(row) {
  if (!row?.id) return
  try {
    await ElMessageBox.confirm(`Delete BOM #${row.id}?`, 'Confirm', {
      type: 'warning',
      confirmButtonText: 'Delete',
      cancelButtonText: 'Cancel'
    })
    await manufacturingApi.deleteBom(ctx.companyId, row.id)
    ElMessage.success('BOM deleted')
    await load()
  } catch (e) {
    if (e === 'cancel' || e === 'close') return
    ElMessage.error(e?.response?.data?.message || e?.message || 'Failed')
  }
}

watch(
  () => ctx.companyId,
  async () => {
    await loadLookups()
    await load()
  }
)

watch(
  () => ctx.orgId,
  () => {
    form.orgId = ctx.orgId
  }
)

onMounted(async () => {
  await loadLookups()
  await load()
})
</script>
