// frontend2/src/views/modules/masterdata/BusinessPartnersView.tsx
import { Button, Card, Form, Input, Modal, Popconfirm, Select, Space, Switch, Table, Tag, Typography, message } from 'antd'
import type { ColumnsType } from 'antd/es/table'
import { useEffect, useMemo, useState } from 'react'
import { masterDataApi } from '@/utils/api'
import { useContextStore } from '@/stores/context'
import CompanyOrgBar from '@/views/modules/common/CompanyOrgBar'

type PartnerType = 'CUSTOMER' | 'VENDOR' | 'BOTH'

type BusinessPartnerRow = {
  id: number
  code?: string
  name?: string
  type?: PartnerType
  email?: string
  phone?: string
  active?: boolean
}

export default function BusinessPartnersView() {
  const companyId = useContextStore((s) => s.companyId)

  const [loading, setLoading] = useState(false)
  const [rows, setRows] = useState<BusinessPartnerRow[]>([])

  const [q, setQ] = useState('')
  const [typeFilter, setTypeFilter] = useState<PartnerType | undefined>(undefined)

  const [createOpen, setCreateOpen] = useState(false)
  const [saving, setSaving] = useState(false)
  const [createForm] = Form.useForm()

  const [editOpen, setEditOpen] = useState(false)
  const [editSaving, setEditSaving] = useState(false)
  const [editingId, setEditingId] = useState<number | null>(null)
  const [editForm] = Form.useForm()

  async function load() {
    if (!companyId) {
      setRows([])
      return
    }
    setLoading(true)
    try {
      setRows((await masterDataApi.listBusinessPartners(companyId)) || [])
    } catch (e: any) {
      message.error(e?.response?.data?.message || e?.message || 'Failed')
      setRows([])
    } finally {
      setLoading(false)
    }
  }

  useEffect(() => {
    void load()
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [companyId])

  const filtered = useMemo(() => {
    const qq = q.trim().toLowerCase()
    return (rows || []).filter((r) => {
      if (typeFilter && r.type !== typeFilter) return false
      if (!qq) return true
      return (
        String(r.name || '').toLowerCase().includes(qq) ||
        String(r.email || '').toLowerCase().includes(qq) ||
        String(r.phone || '').toLowerCase().includes(qq)
      )
    })
  }, [q, rows, typeFilter])

  function openCreate() {
    createForm.setFieldsValue({ type: 'CUSTOMER', name: '', email: '', phone: '' })
    setCreateOpen(true)
  }

  function openEdit(row: BusinessPartnerRow) {
    if (!row?.id) return
    setEditingId(row.id)
    editForm.setFieldsValue({
      type: row.type || 'CUSTOMER',
      name: row.name || '',
      email: row.email || '',
      phone: row.phone || '',
      active: Boolean(row.active)
    })
    setEditOpen(true)
  }

  async function saveCreate() {
    if (!companyId) return
    const values = await createForm.validateFields()
    setSaving(true)
    try {
      await masterDataApi.createBusinessPartner(companyId, {
        type: values.type,
        name: values.name,
        email: String(values.email || '').trim() || null,
        phone: String(values.phone || '').trim() || null
      })
      message.success('Business Partner created')
      setCreateOpen(false)
      await load()
    } catch (e: any) {
      message.error(e?.response?.data?.message || e?.message || 'Failed')
    } finally {
      setSaving(false)
    }
  }

  async function saveEdit() {
    if (!companyId || !editingId) return
    const values = await editForm.validateFields()
    setEditSaving(true)
    try {
      await masterDataApi.updateBusinessPartner(companyId, editingId, {
        type: values.type,
        name: values.name,
        email: String(values.email || '').trim() || null,
        phone: String(values.phone || '').trim() || null,
        active: Boolean(values.active)
      })
      message.success('Business Partner updated')
      setEditOpen(false)
      await load()
    } catch (e: any) {
      message.error(e?.response?.data?.message || e?.message || 'Failed')
    } finally {
      setEditSaving(false)
    }
  }

  async function onDelete(row: BusinessPartnerRow) {
    if (!companyId || !row?.id) return
    try {
      await masterDataApi.deleteBusinessPartner(companyId, row.id)
      message.success('Business Partner deleted')
      await load()
    } catch (e: any) {
      message.error(e?.response?.data?.message || e?.message || 'Failed')
    }
  }

  const columns: ColumnsType<BusinessPartnerRow> = [
    { title: 'ID', dataIndex: 'id', width: 90 },
    { title: 'Name', dataIndex: 'name', width: 260 },
    {
      title: 'Type',
      dataIndex: 'type',
      width: 120,
      render: (v) => <Tag>{String(v || '')}</Tag>
    },
    { title: 'Email', dataIndex: 'email', width: 240 },
    { title: 'Phone', dataIndex: 'phone', width: 160 },
    {
      title: 'Active',
      dataIndex: 'active',
      width: 100,
      render: (v) => <Tag color={v ? 'green' : 'default'}>{v ? 'Yes' : 'No'}</Tag>
    },
    {
      title: 'Action',
      key: 'action',
      width: 220,
      render: (_, r) => (
        <Space>
          <Button size="small" disabled={!companyId} onClick={() => openEdit(r)}>
            Edit
          </Button>
          <Popconfirm
            title={`Delete Business Partner "${r.name || ''}"?`}
            okText="Delete"
            cancelText="Cancel"
            onConfirm={() => onDelete(r)}
            disabled={!companyId}
          >
            <Button size="small" danger disabled={!companyId}>
              Delete
            </Button>
          </Popconfirm>
        </Space>
      )
    }
  ]

  return (
    <div style={{ display: 'flex', flexDirection: 'column', gap: 12 }}>
      <Card>
        <div style={{ display: 'flex', flexDirection: 'column', gap: 10 }}>
          <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', gap: 12 }}>
            <div>
              <div style={{ fontSize: 18, fontWeight: 600 }}>Business Partners</div>
              <div style={{ color: '#606266' }}>Customer, Vendor, atau keduanya (BOTH).</div>
            </div>
            <Button type="primary" disabled={!companyId} onClick={openCreate}>
              Create Business Partner
            </Button>
          </div>

          <CompanyOrgBar showOrg={false} />
        </div>
      </Card>

      <Card>
        {!companyId ? <Tag color="orange">Pilih company dulu.</Tag> : null}

        <div style={{ display: 'flex', gap: 12, alignItems: 'center', marginBottom: 10, flexWrap: 'wrap' }}>
          <Input
            value={q}
            onChange={(e) => setQ(e.target.value)}
            placeholder="Search name/email/phone"
            allowClear
            style={{ maxWidth: 360 }}
          />
          <Select
            allowClear
            placeholder="Filter type"
            style={{ width: 220 }}
            value={typeFilter}
            options={[
              { label: 'CUSTOMER', value: 'CUSTOMER' },
              { label: 'VENDOR', value: 'VENDOR' },
              { label: 'BOTH', value: 'BOTH' }
            ]}
            onChange={(v) => setTypeFilter(v)}
          />
          <Button onClick={() => void load()} disabled={!companyId}>
            Refresh
          </Button>
        </div>

        <Table rowKey="id" dataSource={filtered} columns={columns} loading={loading} scroll={{ x: 1100 }} />
      </Card>

      <Modal
        open={createOpen}
        title="Create Business Partner"
        width={640}
        onCancel={() => setCreateOpen(false)}
        onOk={() => void saveCreate()}
        okButtonProps={{ loading: saving }}
      >
        <Form form={createForm} layout="vertical">
          <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 12 }}>
            <Form.Item name="type" label="Type" rules={[{ required: true }]}>
              <Select
                options={[
                  { label: 'CUSTOMER', value: 'CUSTOMER' },
                  { label: 'VENDOR', value: 'VENDOR' },
                  { label: 'BOTH', value: 'BOTH' }
                ]}
              />
            </Form.Item>
            <Form.Item name="name" label="Name" rules={[{ required: true }]}>
              <Input placeholder="e.g. PT Vendor A" />
            </Form.Item>
          </div>

          <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 12 }}>
            <Form.Item name="email" label="Email">
              <Input placeholder="optional" />
            </Form.Item>
            <Form.Item name="phone" label="Phone">
              <Input placeholder="optional" />
            </Form.Item>
          </div>
        </Form>
      </Modal>

      <Modal
        open={editOpen}
        title={
          <Space>
            <Typography.Text>Edit Business Partner</Typography.Text>
            {editingId ? <Tag>#{editingId}</Tag> : null}
          </Space>
        }
        width={640}
        onCancel={() => setEditOpen(false)}
        onOk={() => void saveEdit()}
        okButtonProps={{ loading: editSaving }}
      >
        <Form form={editForm} layout="vertical">
          <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 12 }}>
            <Form.Item name="type" label="Type" rules={[{ required: true }]}>
              <Select
                options={[
                  { label: 'CUSTOMER', value: 'CUSTOMER' },
                  { label: 'VENDOR', value: 'VENDOR' },
                  { label: 'BOTH', value: 'BOTH' }
                ]}
              />
            </Form.Item>
            <Form.Item name="name" label="Name" rules={[{ required: true }]}>
              <Input placeholder="e.g. PT Vendor A" />
            </Form.Item>
          </div>

          <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 12 }}>
            <Form.Item name="email" label="Email">
              <Input placeholder="optional" />
            </Form.Item>
            <Form.Item name="phone" label="Phone">
              <Input placeholder="optional" />
            </Form.Item>
          </div>

          <Form.Item name="active" label="Active" valuePropName="checked">
            <Switch />
          </Form.Item>
        </Form>
      </Modal>
    </div>
  )
}

// frontend/src/views/modules/masterdata/BusinessPartnersView.vue
<template>
  <div style="display: flex; flex-direction: column; gap: 12px">
    <el-card>
      <div style="display: flex; flex-direction: column; gap: 10px">
        <div style="display: flex; align-items: center; justify-content: space-between; gap: 12px">
          <div>
            <div style="font-size: 18px; font-weight: 600">Business Partners</div>
            <div style="color: #606266">Customer, Vendor, atau keduanya (BOTH).</div>
          </div>
          <el-button type="primary" :disabled="!ctx.companyId" @click="openCreate">Create Business Partner</el-button>
        </div>

        <CompanyOrgBar :show-org="false" />
      </div>
    </el-card>

    <el-card>
      <el-alert v-if="!ctx.companyId" title="Pilih company dulu." type="warning" show-icon style="margin-bottom: 12px" />

      <div style="display: flex; gap: 12px; align-items: center; margin-bottom: 10px; flex-wrap: wrap">
        <el-input v-model="q" placeholder="Search name/email/phone" clearable style="max-width: 360px" />
        <el-select v-model="typeFilter" placeholder="Filter type" clearable style="width: 220px">
          <el-option label="CUSTOMER" value="CUSTOMER" />
          <el-option label="VENDOR" value="VENDOR" />
          <el-option label="BOTH" value="BOTH" />
        </el-select>
      </div>

      <el-table :data="filtered" style="width: 100%" v-loading="loading">
        <el-table-column prop="id" label="ID" width="90" />
        <el-table-column prop="name" label="Name" min-width="220" />
        <el-table-column prop="type" label="Type" width="120">
          <template #default="scope">
            <el-tag size="small" type="info">{{ scope.row.type }}</el-tag>
          </template>
        </el-table-column>
        <el-table-column prop="email" label="Email" min-width="220" />
        <el-table-column prop="phone" label="Phone" width="160" />
        <el-table-column prop="active" label="Active" width="100">
          <template #default="scope">
            <el-tag size="small" :type="scope.row.active ? 'success' : 'info'">{{ scope.row.active ? 'Yes' : 'No' }}</el-tag>
          </template>
        </el-table-column>
        <el-table-column label="Action" width="200">
          <template #default="scope">
            <div style="display: flex; gap: 8px">
              <el-button size="small" :disabled="!ctx.companyId" @click="openEdit(scope.row)">Edit</el-button>
              <el-button size="small" type="danger" plain :disabled="!ctx.companyId" @click="onDelete(scope.row)">Delete</el-button>
            </div>
          </template>
        </el-table-column>
      </el-table>
    </el-card>

    <el-dialog v-model="createOpen" title="Create Business Partner" width="620px">
      <el-form label-position="top">
        <div style="display: grid; grid-template-columns: 1fr 1fr; gap: 12px">
          <el-form-item label="Type">
            <el-select v-model="form.type" style="width: 100%">
              <el-option label="CUSTOMER" value="CUSTOMER" />
              <el-option label="VENDOR" value="VENDOR" />
              <el-option label="BOTH" value="BOTH" />
            </el-select>
          </el-form-item>
          <el-form-item label="Name">
            <el-input v-model="form.name" placeholder="e.g. PT Vendor A" />
          </el-form-item>
        </div>

        <div style="display: grid; grid-template-columns: 1fr 1fr; gap: 12px">
          <el-form-item label="Email">
            <el-input v-model="form.email" placeholder="optional" />
          </el-form-item>
          <el-form-item label="Phone">
            <el-input v-model="form.phone" placeholder="optional" />
          </el-form-item>
        </div>
      </el-form>

      <template #footer>
        <el-button @click="createOpen = false">Cancel</el-button>
        <el-button type="primary" :loading="saving" :disabled="!canSave" @click="save">Save</el-button>
      </template>
    </el-dialog>

    <el-dialog v-model="editOpen" title="Edit Business Partner" width="620px">
      <el-form label-position="top">
        <div style="display: grid; grid-template-columns: 1fr 1fr; gap: 12px">
          <el-form-item label="Type">
            <el-select v-model="editForm.type" style="width: 100%">
              <el-option label="CUSTOMER" value="CUSTOMER" />
              <el-option label="VENDOR" value="VENDOR" />
              <el-option label="BOTH" value="BOTH" />
            </el-select>
          </el-form-item>
          <el-form-item label="Name">
            <el-input v-model="editForm.name" placeholder="e.g. PT Vendor A" />
          </el-form-item>
        </div>

        <div style="display: grid; grid-template-columns: 1fr 1fr; gap: 12px">
          <el-form-item label="Email">
            <el-input v-model="editForm.email" placeholder="optional" />
          </el-form-item>
          <el-form-item label="Phone">
            <el-input v-model="editForm.phone" placeholder="optional" />
          </el-form-item>
        </div>

        <el-form-item label="Active">
          <el-switch v-model="editForm.active" />
        </el-form-item>
      </el-form>

      <template #footer>
        <el-button @click="editOpen = false">Cancel</el-button>
        <el-button type="primary" :loading="editSaving" :disabled="!canEditSave" @click="saveEdit">Save</el-button>
      </template>
    </el-dialog>
  </div>
</template>

<script setup>
import { computed, onMounted, reactive, ref, watch } from 'vue'
import { ElMessage, ElMessageBox } from 'element-plus'
import { masterDataApi } from '@/utils/api'
import { useContextStore } from '@/stores/context'
import CompanyOrgBar from '@/views/modules/common/CompanyOrgBar.vue'

const ctx = useContextStore()

const rows = ref([])
const loading = ref(false)

const q = ref('')
const typeFilter = ref('')

const createOpen = ref(false)
const saving = ref(false)

const editOpen = ref(false)
const editSaving = ref(false)
const editingId = ref(null)

const form = reactive({
  type: 'CUSTOMER',
  name: '',
  email: '',
  phone: ''
})

const editForm = reactive({
  type: 'CUSTOMER',
  name: '',
  email: '',
  phone: '',
  active: true
})

const canSave = computed(() => Boolean(ctx.companyId && form.name.trim() && form.type))
const canEditSave = computed(() => Boolean(ctx.companyId && editingId.value && editForm.name.trim() && editForm.type))

const filtered = computed(() => {
  const qq = q.value.trim().toLowerCase()
  return (rows.value || []).filter((r) => {
    if (typeFilter.value && r.type !== typeFilter.value) return false
    if (!qq) return true
    return (
      String(r.name || '').toLowerCase().includes(qq) ||
      String(r.email || '').toLowerCase().includes(qq) ||
      String(r.phone || '').toLowerCase().includes(qq)
    )
  })
})

async function load() {
  if (!ctx.companyId) {
    rows.value = []
    return
  }
  loading.value = true
  try {
    rows.value = await masterDataApi.listBusinessPartners(ctx.companyId)
  } finally {
    loading.value = false
  }
}

function openCreate() {
  form.type = 'CUSTOMER'
  form.name = ''
  form.email = ''
  form.phone = ''
  createOpen.value = true
}

function openEdit(row) {
  if (!row?.id) return
  editingId.value = row.id
  editForm.type = row.type || 'CUSTOMER'
  editForm.name = row.name || ''
  editForm.email = row.email || ''
  editForm.phone = row.phone || ''
  editForm.active = Boolean(row.active)
  editOpen.value = true
}

async function save() {
  saving.value = true
  try {
    await masterDataApi.createBusinessPartner(ctx.companyId, {
      type: form.type,
      name: form.name,
      email: form.email || null,
      phone: form.phone || null
    })
    ElMessage.success('Business Partner created')
    createOpen.value = false
    await load()
  } catch (e) {
    ElMessage.error(e?.response?.data?.message || e?.message || 'Failed')
  } finally {
    saving.value = false
  }
}

async function saveEdit() {
  editSaving.value = true
  try {
    await masterDataApi.updateBusinessPartner(ctx.companyId, editingId.value, {
      type: editForm.type,
      name: editForm.name,
      email: String(editForm.email || '').trim() || null,
      phone: String(editForm.phone || '').trim() || null,
      active: Boolean(editForm.active)
    })
    ElMessage.success('Business Partner updated')
    editOpen.value = false
    await load()
  } catch (e) {
    ElMessage.error(e?.response?.data?.message || e?.message || 'Failed')
  } finally {
    editSaving.value = false
  }
}

async function onDelete(row) {
  if (!row?.id) return
  try {
    await ElMessageBox.confirm(`Delete Business Partner "${row.name}"?`, 'Confirm', {
      type: 'warning',
      confirmButtonText: 'Delete',
      cancelButtonText: 'Cancel'
    })
    await masterDataApi.deleteBusinessPartner(ctx.companyId, row.id)
    ElMessage.success('Business Partner deleted')
    await load()
  } catch (e) {
    if (e === 'cancel' || e === 'close') return
    ElMessage.error(e?.response?.data?.message || e?.message || 'Failed')
  }
}

watch(
  () => ctx.companyId,
  () => load()
)

onMounted(load)
</script>
