// frontend2_new/src/views/modules/masterdata/BusinessPartnersView.tsx
import { Button, Card, Form, Input, Modal, Popconfirm, Select, Space, Switch, Table, Tag, Typography, message } from 'antd'
import type { ColumnsType } from 'antd/es/table'
import { useEffect, useMemo, useState } from 'react'
import { coreApi, masterDataApi } from '@/utils/api'
import { useContextStore } from '@/stores/context'
import { getApiErrorMessage } from '@/utils/error'

type PartnerType = 'CUSTOMER' | 'VENDOR' | 'BOTH'

type CompanyRow = {
  id: number
  code?: string
  name?: string
  active?: boolean
}

type BusinessPartnerRow = {
  id: number
  name?: string
  type?: PartnerType
  email?: string
  phone?: string
  active?: boolean
}

export default function BusinessPartnersView() {
  const companyId = useContextStore((s) => s.companyId)
  const setCompanyId = useContextStore((s) => s.setCompanyId)

  const [companyLoading, setCompanyLoading] = useState(false)
  const [companies, setCompanies] = useState<CompanyRow[]>([])

  const [loading, setLoading] = useState(false)
  const [rows, setRows] = useState<BusinessPartnerRow[]>([])

  const [q, setQ] = useState('')
  const [typeFilter, setTypeFilter] = useState<PartnerType | undefined>(undefined)

  const [open, setOpen] = useState(false)
  const [editing, setEditing] = useState<BusinessPartnerRow | null>(null)
  const [form] = Form.useForm()

  const loadCompanies = async () => {
    setCompanyLoading(true)
    try {
      const res = await coreApi.listCompanies()
      setCompanies((res || []) as CompanyRow[])
      if (!companyId && Array.isArray(res) && res.length > 0) {
        setCompanyId((res[0] as any).id ?? null)
      }
    } catch (e: any) {
      message.error(getApiErrorMessage(e, 'Failed to load companies'))
    } finally {
      setCompanyLoading(false)
    }
  }

  const load = async (cid: number) => {
    setLoading(true)
    try {
      const res = await masterDataApi.listBusinessPartners(cid)
      setRows((res || []) as BusinessPartnerRow[])
    } catch (e: any) {
      message.error(getApiErrorMessage(e, 'Failed to load business partners'))
    } finally {
      setLoading(false)
    }
  }

  useEffect(() => {
    void loadCompanies()
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [])

  useEffect(() => {
    if (companyId) void load(companyId)
  }, [companyId])

  const filtered = useMemo(() => {
    const qq = q.trim().toLowerCase()
    return rows.filter((r) => {
      if (typeFilter && r.type !== typeFilter) return false
      if (!qq) return true
      const s = `${r.name || ''} ${r.email || ''} ${r.phone || ''}`.toLowerCase()
      return s.includes(qq)
    })
  }, [q, rows, typeFilter])

  const columns: ColumnsType<BusinessPartnerRow> = useMemo(
    () => [
      { title: 'ID', dataIndex: 'id', width: 90 },
      { title: 'Name', dataIndex: 'name' },
      {
        title: 'Type',
        dataIndex: 'type',
        width: 140,
        render: (v: PartnerType) => {
          if (v === 'CUSTOMER') return <Tag color="blue">CUSTOMER</Tag>
          if (v === 'VENDOR') return <Tag color="purple">VENDOR</Tag>
          return <Tag color="geekblue">BOTH</Tag>
        }
      },
      { title: 'Email', dataIndex: 'email', width: 220 },
      { title: 'Phone', dataIndex: 'phone', width: 160 },
      {
        title: 'Active',
        dataIndex: 'active',
        width: 100,
        render: (v: boolean) => (v ? <Tag color="green">YES</Tag> : <Tag color="red">NO</Tag>)
      },
      {
        title: 'Actions',
        key: 'actions',
        width: 180,
        render: (_, r) => (
          <Space>
            <Button
              size="small"
              onClick={() => {
                setEditing(r)
                setOpen(true)
                form.setFieldsValue({
                  name: r.name,
                  type: r.type,
                  email: r.email,
                  phone: r.phone,
                  active: r.active
                })
              }}
            >
              Edit
            </Button>
            <Popconfirm
              title="Delete business partner?"
              okText="Delete"
              okButtonProps={{ danger: true }}
              onConfirm={async () => {
                if (!companyId) return
                try {
                  await masterDataApi.deleteBusinessPartner(companyId, r.id)
                  message.success('Deleted')
                  await load(companyId)
                } catch (e: any) {
                  message.error(getApiErrorMessage(e, 'Failed to delete'))
                }
              }}
            >
              <Button size="small" danger>
                Delete
              </Button>
            </Popconfirm>
          </Space>
        )
      }
    ],
    [companyId, form]
  )

  return (
    <Space direction="vertical" size={16} style={{ width: '100%' }}>
      <Card>
        <Space style={{ width: '100%', justifyContent: 'space-between' }}>
          <Typography.Title level={4} style={{ margin: 0 }}>
            Business Partners
          </Typography.Title>
          <Space>
            <Button onClick={() => loadCompanies()} loading={companyLoading}>
              Refresh Companies
            </Button>
            <Button onClick={() => companyId && load(companyId)} disabled={!companyId} loading={loading}>
              Refresh
            </Button>
            <Button
              type="primary"
              onClick={() => {
                setEditing(null)
                setOpen(true)
                form.setFieldsValue({ active: true, type: 'CUSTOMER' })
              }}
              disabled={!companyId}
            >
              New
            </Button>
          </Space>
        </Space>
      </Card>

      <Card>
        <Space direction="vertical" size={12} style={{ width: '100%' }}>
          <Space wrap>
            <div style={{ minWidth: 320 }}>
              <Typography.Text strong>Company</Typography.Text>
              <Select
                style={{ width: '100%' }}
                loading={companyLoading}
                value={companyId ?? undefined}
                placeholder="Select company"
                options={companies.map((c) => ({ value: c.id, label: `${c.code || c.id} - ${c.name || ''}` }))}
                onChange={(v) => setCompanyId(v)}
              />
            </div>

            <div style={{ minWidth: 260 }}>
              <Typography.Text strong>Search</Typography.Text>
              <Input value={q} onChange={(e) => setQ(e.target.value)} placeholder="name/email/phone" allowClear />
            </div>

            <div style={{ minWidth: 200 }}>
              <Typography.Text strong>Type</Typography.Text>
              <Select
                value={typeFilter}
                onChange={(v) => setTypeFilter(v)}
                allowClear
                placeholder="All"
                options={[
                  { value: 'CUSTOMER', label: 'CUSTOMER' },
                  { value: 'VENDOR', label: 'VENDOR' },
                  { value: 'BOTH', label: 'BOTH' }
                ]}
                style={{ width: '100%' }}
              />
            </div>
          </Space>

          <Table<BusinessPartnerRow>
            rowKey="id"
            loading={loading}
            columns={columns}
            dataSource={filtered}
            pagination={{ pageSize: 10 }}
          />
        </Space>
      </Card>

      <Modal
        title={editing ? 'Edit Business Partner' : 'Create Business Partner'}
        open={open}
        onCancel={() => {
          setOpen(false)
          setEditing(null)
          form.resetFields()
        }}
        onOk={async () => {
          if (!companyId) return
          try {
            const values = await form.validateFields()
            const payload = {
              name: values.name,
              type: values.type,
              email: values.email,
              phone: values.phone,
              active: values.active ?? true
            }

            if (editing) {
              await masterDataApi.updateBusinessPartner(companyId, editing.id, payload)
              message.success('Updated')
            } else {
              await masterDataApi.createBusinessPartner(companyId, payload)
              message.success('Created')
            }

            setOpen(false)
            setEditing(null)
            form.resetFields()
            await load(companyId)
          } catch (e: any) {
            if (e?.errorFields) return
            message.error(getApiErrorMessage(e, 'Failed to save'))
          }
        }}
        okText={editing ? 'Save' : 'Create'}
      >
        <Form layout="vertical" form={form} initialValues={{ active: true, type: 'CUSTOMER' }}>
          <Form.Item name="name" label="Name" rules={[{ required: true, message: 'Name is required' }]}>
            <Input />
          </Form.Item>

          <Form.Item name="type" label="Type" rules={[{ required: true, message: 'Type is required' }]}>
            <Select
              options={[
                { value: 'CUSTOMER', label: 'CUSTOMER' },
                { value: 'VENDOR', label: 'VENDOR' },
                { value: 'BOTH', label: 'BOTH' }
              ]}
            />
          </Form.Item>

          <Form.Item name="email" label="Email">
            <Input />
          </Form.Item>

          <Form.Item name="phone" label="Phone">
            <Input />
          </Form.Item>

          <Form.Item name="active" label="Active" valuePropName="checked">
            <Switch />
          </Form.Item>
        </Form>
      </Modal>
    </Space>
  )
}

// frontend/src/views/modules/masterdata/BusinessPartnersView.vue
<template>
  <div style="display: flex; flex-direction: column; gap: 12px">
    <el-card>
      <div style="display: flex; flex-direction: column; gap: 10px">
        <div style="display: flex; align-items: center; justify-content: space-between; gap: 12px">
          <div>
            <div style="font-size: 18px; font-weight: 600">Business Partners</div>
            <div style="color: #606266">Customer, Vendor, atau keduanya (BOTH).</div>
          </div>
          <el-button type="primary" :disabled="!ctx.companyId" @click="openCreate">Create Business Partner</el-button>
        </div>

        <CompanyOrgBar :show-org="false" />
      </div>
    </el-card>

    <el-card>
      <el-alert v-if="!ctx.companyId" title="Pilih company dulu." type="warning" show-icon style="margin-bottom: 12px" />

      <div style="display: flex; gap: 12px; align-items: center; margin-bottom: 10px; flex-wrap: wrap">
        <el-input v-model="q" placeholder="Search name/email/phone" clearable style="max-width: 360px" />
        <el-select v-model="typeFilter" placeholder="Filter type" clearable style="width: 220px">
          <el-option label="CUSTOMER" value="CUSTOMER" />
          <el-option label="VENDOR" value="VENDOR" />
          <el-option label="BOTH" value="BOTH" />
        </el-select>
      </div>

      <el-table :data="filtered" style="width: 100%" v-loading="loading">
        <el-table-column prop="id" label="ID" width="90" />
        <el-table-column prop="name" label="Name" min-width="220" />
        <el-table-column prop="type" label="Type" width="120">
          <template #default="scope">
            <el-tag size="small" type="info">{{ scope.row.type }}</el-tag>
          </template>
        </el-table-column>
        <el-table-column prop="email" label="Email" min-width="220" />
        <el-table-column prop="phone" label="Phone" width="160" />
        <el-table-column prop="active" label="Active" width="100">
          <template #default="scope">
            <el-tag size="small" :type="scope.row.active ? 'success' : 'info'">{{ scope.row.active ? 'Yes' : 'No' }}</el-tag>
          </template>
        </el-table-column>
        <el-table-column label="Action" width="200">
          <template #default="scope">
            <div style="display: flex; gap: 8px">
              <el-button size="small" :disabled="!ctx.companyId" @click="openEdit(scope.row)">Edit</el-button>
              <el-button size="small" type="danger" plain :disabled="!ctx.companyId" @click="onDelete(scope.row)">Delete</el-button>
            </div>
          </template>
        </el-table-column>
      </el-table>
    </el-card>

    <el-dialog v-model="createOpen" title="Create Business Partner" width="620px">
      <el-form label-position="top">
        <div style="display: grid; grid-template-columns: 1fr 1fr; gap: 12px">
          <el-form-item label="Type">
            <el-select v-model="form.type" style="width: 100%">
              <el-option label="CUSTOMER" value="CUSTOMER" />
              <el-option label="VENDOR" value="VENDOR" />
              <el-option label="BOTH" value="BOTH" />
            </el-select>
          </el-form-item>
          <el-form-item label="Name">
            <el-input v-model="form.name" placeholder="e.g. PT Vendor A" />
          </el-form-item>
        </div>

        <div style="display: grid; grid-template-columns: 1fr 1fr; gap: 12px">
          <el-form-item label="Email">
            <el-input v-model="form.email" placeholder="optional" />
          </el-form-item>
          <el-form-item label="Phone">
            <el-input v-model="form.phone" placeholder="optional" />
          </el-form-item>
        </div>
      </el-form>

      <template #footer>
        <el-button @click="createOpen = false">Cancel</el-button>
        <el-button type="primary" :loading="saving" :disabled="!canSave" @click="save">Save</el-button>
      </template>
    </el-dialog>

    <el-dialog v-model="editOpen" title="Edit Business Partner" width="620px">
      <el-form label-position="top">
        <div style="display: grid; grid-template-columns: 1fr 1fr; gap: 12px">
          <el-form-item label="Type">
            <el-select v-model="editForm.type" style="width: 100%">
              <el-option label="CUSTOMER" value="CUSTOMER" />
              <el-option label="VENDOR" value="VENDOR" />
              <el-option label="BOTH" value="BOTH" />
            </el-select>
          </el-form-item>
          <el-form-item label="Name">
            <el-input v-model="editForm.name" placeholder="e.g. PT Vendor A" />
          </el-form-item>
        </div>

        <div style="display: grid; grid-template-columns: 1fr 1fr; gap: 12px">
          <el-form-item label="Email">
            <el-input v-model="editForm.email" placeholder="optional" />
          </el-form-item>
          <el-form-item label="Phone">
            <el-input v-model="editForm.phone" placeholder="optional" />
          </el-form-item>
        </div>

        <el-form-item label="Active">
          <el-switch v-model="editForm.active" />
        </el-form-item>
      </el-form>

      <template #footer>
        <el-button @click="editOpen = false">Cancel</el-button>
        <el-button type="primary" :loading="editSaving" :disabled="!canEditSave" @click="saveEdit">Save</el-button>
      </template>
    </el-dialog>
  </div>
</template>

<script setup>
import { computed, onMounted, reactive, ref, watch } from 'vue'
import { ElMessage, ElMessageBox } from 'element-plus'
import { masterDataApi } from '@/utils/api'
import { useContextStore } from '@/stores/context'
import CompanyOrgBar from '@/views/modules/common/CompanyOrgBar.vue'

const ctx = useContextStore()

const rows = ref([])
const loading = ref(false)

const q = ref('')
const typeFilter = ref('')

const createOpen = ref(false)
const saving = ref(false)

const editOpen = ref(false)
const editSaving = ref(false)
const editingId = ref(null)

const form = reactive({
  type: 'CUSTOMER',
  name: '',
  email: '',
  phone: ''
})

const editForm = reactive({
  type: 'CUSTOMER',
  name: '',
  email: '',
  phone: '',
  active: true
})

const canSave = computed(() => Boolean(ctx.companyId && form.name.trim() && form.type))
const canEditSave = computed(() => Boolean(ctx.companyId && editingId.value && editForm.name.trim() && editForm.type))

const filtered = computed(() => {
  const qq = q.value.trim().toLowerCase()
  return (rows.value || []).filter((r) => {
    if (typeFilter.value && r.type !== typeFilter.value) return false
    if (!qq) return true
    return (
      String(r.name || '').toLowerCase().includes(qq) ||
      String(r.email || '').toLowerCase().includes(qq) ||
      String(r.phone || '').toLowerCase().includes(qq)
    )
  })
})

async function load() {
  if (!ctx.companyId) {
    rows.value = []
    return
  }
  loading.value = true
  try {
    rows.value = await masterDataApi.listBusinessPartners(ctx.companyId)
  } finally {
    loading.value = false
  }
}

function openCreate() {
  form.type = 'CUSTOMER'
  form.name = ''
  form.email = ''
  form.phone = ''
  createOpen.value = true
}

function openEdit(row) {
  if (!row?.id) return
  editingId.value = row.id
  editForm.type = row.type || 'CUSTOMER'
  editForm.name = row.name || ''
  editForm.email = row.email || ''
  editForm.phone = row.phone || ''
  editForm.active = Boolean(row.active)
  editOpen.value = true
}

async function save() {
  saving.value = true
  try {
    await masterDataApi.createBusinessPartner(ctx.companyId, {
      type: form.type,
      name: form.name,
      email: form.email || null,
      phone: form.phone || null
    })
    ElMessage.success('Business Partner created')
    createOpen.value = false
    await load()
  } catch (e) {
    ElMessage.error(e?.response?.data?.message || e?.message || 'Failed')
  } finally {
    saving.value = false
  }
}

async function saveEdit() {
  editSaving.value = true
  try {
    await masterDataApi.updateBusinessPartner(ctx.companyId, editingId.value, {
      type: editForm.type,
      name: editForm.name,
      email: String(editForm.email || '').trim() || null,
      phone: String(editForm.phone || '').trim() || null,
      active: Boolean(editForm.active)
    })
    ElMessage.success('Business Partner updated')
    editOpen.value = false
    await load()
  } catch (e) {
    ElMessage.error(e?.response?.data?.message || e?.message || 'Failed')
  } finally {
    editSaving.value = false
  }
}

async function onDelete(row) {
  if (!row?.id) return
  try {
    await ElMessageBox.confirm(`Delete Business Partner "${row.name}"?`, 'Confirm', {
      type: 'warning',
      confirmButtonText: 'Delete',
      cancelButtonText: 'Cancel'
    })
    await masterDataApi.deleteBusinessPartner(ctx.companyId, row.id)
    ElMessage.success('Business Partner deleted')
    await load()
  } catch (e) {
    if (e === 'cancel' || e === 'close') return
    ElMessage.error(e?.response?.data?.message || e?.message || 'Failed')
  }
}

watch(
  () => ctx.companyId,
  () => load()
)

onMounted(load)
</script>
