// frontend2_new/src/views/modules/purchase/PurchaseOrdersView.tsx
import {
  Button,
  Card,
  DatePicker,
  Form,
  Input,
  InputNumber,
  Modal,
  Popconfirm,
  Select,
  Space,
  Table,
  Tag,
  Typography,
  message
} from 'antd'
import type { ColumnsType } from 'antd/es/table'
import dayjs from 'dayjs'
import { useEffect, useMemo, useState } from 'react'
import { coreApi, inventoryApi, masterDataApi, purchaseApi } from '@/utils/api'
import { useContextStore } from '@/stores/context'
import { getApiErrorMessage } from '@/utils/error'

type CompanyRow = {
  id: number
  code?: string
  name?: string
}

type OrgRow = {
  id: number
  code?: string
  name?: string
}

type VendorRow = {
  id: number
  name?: string
  type?: 'CUSTOMER' | 'VENDOR' | 'BOTH'
}

type ProductRow = {
  id: number
  code?: string
  name?: string
}

type PriceListRow = {
  id: number
  name?: string
}

type PriceListVersionRow = {
  id: number
  name?: string
  validFrom?: string
}

type PurchaseOrderLineRow = {
  id?: number
  productId?: number
  uomId?: number
  qty?: number
  price?: number
  lineNet?: number
  receivedQty?: number
}

type PurchaseOrderRow = {
  id: number
  orgId?: number | null
  vendorId?: number
  priceListVersionId?: number
  documentNo?: string
  status?: string
  orderDate?: string
  totalNet?: number
  totalTax?: number
  grandTotal?: number
  lines?: PurchaseOrderLineRow[]
}

type LocatorRow = {
  id: number
  code?: string
  name?: string
}

function toLocalDateString(d: any): string {
  if (!d) return ''
  return dayjs(d).format('YYYY-MM-DD')
}

export default function PurchaseOrdersView() {
  const companyId = useContextStore((s) => s.companyId)
  const setCompanyId = useContextStore((s) => s.setCompanyId)

  const [companyLoading, setCompanyLoading] = useState(false)
  const [companies, setCompanies] = useState<CompanyRow[]>([])

  const [orgLoading, setOrgLoading] = useState(false)
  const [orgs, setOrgs] = useState<OrgRow[]>([])

  const [vendorLoading, setVendorLoading] = useState(false)
  const [vendors, setVendors] = useState<VendorRow[]>([])

  const [productLoading, setProductLoading] = useState(false)
  const [products, setProducts] = useState<ProductRow[]>([])

  const [priceListVersionLoading, setPriceListVersionLoading] = useState(false)
  const [priceListVersions, setPriceListVersions] = useState<PriceListVersionRow[]>([])

  const [loading, setLoading] = useState(false)
  const [rows, setRows] = useState<PurchaseOrderRow[]>([])

  const [open, setOpen] = useState(false)
  const [editing, setEditing] = useState<PurchaseOrderRow | null>(null)
  const [form] = Form.useForm()

  const [receiptOpen, setReceiptOpen] = useState(false)
  const [receiptPo, setReceiptPo] = useState<PurchaseOrderRow | null>(null)
  const [receiptForm] = Form.useForm()
  const [locatorLoading, setLocatorLoading] = useState(false)
  const [locators, setLocators] = useState<LocatorRow[]>([])

  const loadCompanies = async () => {
    setCompanyLoading(true)
    try {
      const res = await coreApi.listCompanies()
      setCompanies((res || []) as CompanyRow[])
      if (!companyId && Array.isArray(res) && res.length > 0) {
        setCompanyId((res[0] as any).id ?? null)
      }
    } catch (e: any) {
      message.error(getApiErrorMessage(e, 'Failed to load companies'))
    } finally {
      setCompanyLoading(false)
    }
  }

  const loadLookups = async (cid: number) => {
    setOrgLoading(true)
    setVendorLoading(true)
    setProductLoading(true)
    try {
      const [orgRes, vendorRes, productRes, priceListRes] = await Promise.all([
        coreApi.listOrgs(cid),
        masterDataApi.listBusinessPartners(cid),
        masterDataApi.listProducts(cid),
        masterDataApi.listPriceLists(cid)
      ])

      setOrgs((orgRes || []) as OrgRow[])

      const vAll = (vendorRes || []) as VendorRow[]
      setVendors(vAll.filter((v) => v.type === 'VENDOR' || v.type === 'BOTH'))

      setProducts((productRes || []) as ProductRow[])
      const pls = (priceListRes || []) as PriceListRow[]

      setPriceListVersionLoading(true)
      try {
        const versionLists = await Promise.all(pls.map((pl: any) => masterDataApi.listPriceListVersions(pl.id)))
        const flat = versionLists.flat().filter(Boolean)
        setPriceListVersions(flat as PriceListVersionRow[])
      } finally {
        setPriceListVersionLoading(false)
      }
    } catch (e: any) {
      message.error(getApiErrorMessage(e, 'Failed to load master data lookups'))
    } finally {
      setOrgLoading(false)
      setVendorLoading(false)
      setProductLoading(false)
    }
  }

  const load = async (cid: number) => {
    setLoading(true)
    try {
      const res = await purchaseApi.listPurchaseOrders(cid)
      setRows((res || []) as PurchaseOrderRow[])
    } catch (e: any) {
      message.error(getApiErrorMessage(e, 'Failed to load purchase orders'))
    } finally {
      setLoading(false)
    }
  }

  const loadLocators = async (cid: number) => {
    setLocatorLoading(true)
    try {
      const res = await inventoryApi.listLocators(cid)
      setLocators((res || []) as LocatorRow[])
    } catch (e: any) {
      message.error(getApiErrorMessage(e, 'Failed to load locators'))
    } finally {
      setLocatorLoading(false)
    }
  }

  useEffect(() => {
    void loadCompanies()
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [])

  useEffect(() => {
    if (!companyId) return
    void loadLookups(companyId)
    void load(companyId)
  }, [companyId])

  const vendorLabelById = useMemo(() => {
    const m = new Map<number, string>()
    for (const v of vendors) m.set(v.id, v.name || String(v.id))
    return m
  }, [vendors])

  const productLabelById = useMemo(() => {
    const m = new Map<number, string>()
    for (const p of products) m.set(p.id, `${p.code || p.id} - ${p.name || ''}`)
    return m
  }, [products])

  const orgLabelById = useMemo(() => {
    const m = new Map<number, string>()
    for (const o of orgs) m.set(o.id, `${o.code || o.id} - ${o.name || ''}`)
    return m
  }, [orgs])

  const columns: ColumnsType<PurchaseOrderRow> = useMemo(
    () => [
      { title: 'Doc No', dataIndex: 'documentNo', width: 160 },
      {
        title: 'Status',
        dataIndex: 'status',
        width: 150,
        render: (v: string) => {
          const s = String(v || '')
          if (s === 'DRAFTED') return <Tag>Drafted</Tag>
          if (s === 'APPROVED') return <Tag color="blue">Approved</Tag>
          if (s === 'PARTIALLY_COMPLETED') return <Tag color="gold">Partially Completed</Tag>
          if (s === 'COMPLETED') return <Tag color="green">Completed</Tag>
          if (s === 'VOIDED') return <Tag color="red">Voided</Tag>
          return <Tag>{s}</Tag>
        }
      },
      { title: 'Order Date', dataIndex: 'orderDate', width: 130 },
      {
        title: 'Vendor',
        dataIndex: 'vendorId',
        render: (v: number) => vendorLabelById.get(v) || v
      },
      {
        title: 'Org',
        dataIndex: 'orgId',
        width: 220,
        render: (v: number | null) => (v ? orgLabelById.get(v) || v : '-')
      },
      {
        title: 'Grand Total',
        dataIndex: 'grandTotal',
        width: 140,
        align: 'right',
        render: (v: any) => (v == null ? '-' : Number(v).toLocaleString())
      },
      {
        title: 'Actions',
        key: 'actions',
        width: 360,
        render: (_, r) => {
          const status = String(r.status || '')
          const canEdit = status === 'DRAFTED'
          const canApprove = status === 'DRAFTED'
          const canDelete = status === 'DRAFTED'
          const canGoodsReceipt = status === 'APPROVED' || status === 'PARTIALLY_COMPLETED'

          return (
            <Space wrap>
              <Button
                size="small"
                disabled={!canEdit}
                onClick={() => {
                  setEditing(r)
                  setOpen(true)

                  form.setFieldsValue({
                    orgId: r.orgId ?? null,
                    vendorId: r.vendorId,
                    orderDate: r.orderDate ? dayjs(r.orderDate) : null,
                    priceListVersionId: r.priceListVersionId,
                    lines: (r.lines || []).map((ln) => ({ productId: ln.productId, qty: ln.qty }))
                  })
                }}
              >
                Edit
              </Button>

              <Popconfirm
                title="Approve purchase order?"
                okText="Approve"
                onConfirm={async () => {
                  if (!companyId) return
                  try {
                    await purchaseApi.approvePurchaseOrder(companyId, r.id)
                    message.success('Approved')
                    await load(companyId)
                  } catch (e: any) {
                    message.error(getApiErrorMessage(e, 'Failed to approve'))
                  }
                }}
                disabled={!canApprove}
              >
                <Button size="small" type="primary" disabled={!canApprove}>
                  Approve
                </Button>
              </Popconfirm>

              <Button
                size="small"
                disabled={!canGoodsReceipt}
                onClick={async () => {
                  setReceiptPo(r)
                  setReceiptOpen(true)
                  receiptForm.resetFields()

                  if (companyId) await loadLocators(companyId)

                  const defaultLines = (r.lines || [])
                    .filter((ln) => {
                      const qty = Number(ln.qty || 0)
                      const received = Number(ln.receivedQty || 0)
                      return qty - received > 0
                    })
                    .map((ln) => {
                      const qty = Number(ln.qty || 0)
                      const received = Number(ln.receivedQty || 0)
                      return {
                        purchaseOrderLineId: ln.id,
                        qty: qty - received
                      }
                    })

                  receiptForm.setFieldsValue({
                    movementDate: dayjs(),
                    description: `Goods Receipt for PO ${r.documentNo || r.id}`,
                    toLocatorId: undefined,
                    lines: defaultLines
                  })
                }}
              >
                Goods Receipt
              </Button>

              <Popconfirm
                title="Delete purchase order?"
                okText="Delete"
                okButtonProps={{ danger: true }}
                onConfirm={async () => {
                  if (!companyId) return
                  try {
                    await purchaseApi.deletePurchaseOrder(companyId, r.id)
                    message.success('Deleted')
                    await load(companyId)
                  } catch (e: any) {
                    message.error(getApiErrorMessage(e, 'Failed to delete'))
                  }
                }}
                disabled={!canDelete}
              >
                <Button size="small" danger disabled={!canDelete}>
                  Delete
                </Button>
              </Popconfirm>
            </Space>
          )
        }
      }
    ],
    [companyId, form, orgLabelById, receiptForm, vendorLabelById]
  )

  return (
    <Space direction="vertical" size={16} style={{ width: '100%' }}>
      <Card>
        <Space style={{ width: '100%', justifyContent: 'space-between' }}>
          <Typography.Title level={4} style={{ margin: 0 }}>
            Purchase Orders
          </Typography.Title>
          <Space>
            <Button onClick={() => loadCompanies()} loading={companyLoading}>
              Refresh Companies
            </Button>
            <Button onClick={() => companyId && loadLookups(companyId)} disabled={!companyId} loading={orgLoading || vendorLoading || productLoading}>
              Refresh Lookups
            </Button>
            <Button onClick={() => companyId && load(companyId)} disabled={!companyId} loading={loading}>
              Refresh
            </Button>
            <Button
              type="primary"
              onClick={() => {
                setEditing(null)
                setOpen(true)
                form.resetFields()
                form.setFieldsValue({
                  orderDate: dayjs(),
                  priceListVersionId: priceListVersions[0]?.id,
                  lines: [{ productId: undefined, qty: 1 }]
                })
              }}
              disabled={!companyId}
            >
              New PO
            </Button>
          </Space>
        </Space>
      </Card>

      <Card>
        <Space direction="vertical" size={8} style={{ width: '100%' }}>
          <Typography.Text strong>Company</Typography.Text>
          <Select
            style={{ width: 420, maxWidth: '100%' }}
            loading={companyLoading}
            value={companyId ?? undefined}
            placeholder="Select company"
            options={companies.map((c) => ({ value: c.id, label: `${c.code || c.id} - ${c.name || ''}` }))}
            onChange={(v) => setCompanyId(v)}
          />
        </Space>
      </Card>

      <Card>
        <Table<PurchaseOrderRow>
          rowKey="id"
          loading={loading}
          columns={columns}
          dataSource={rows}
          pagination={{ pageSize: 10 }}
          expandable={{
            expandedRowRender: (r) => (
              <Table<PurchaseOrderLineRow>
                rowKey={(x) => String(x.id || `${x.productId}-${x.qty}`)}
                size="small"
                pagination={false}
                columns={[
                  {
                    title: 'Product',
                    dataIndex: 'productId',
                    render: (v: number) => productLabelById.get(v) || v
                  },
                  { title: 'Qty', dataIndex: 'qty', width: 120 },
                  { title: 'Received', dataIndex: 'receivedQty', width: 120 },
                  { title: 'Price', dataIndex: 'price', width: 120 },
                  { title: 'Line Net', dataIndex: 'lineNet', width: 140 }
                ]}
                dataSource={r.lines || []}
              />
            )
          }}
        />
      </Card>

      <Modal
        title={editing ? 'Edit Purchase Order' : 'Create Purchase Order'}
        open={open}
        width={860}
        onCancel={() => {
          setOpen(false)
          setEditing(null)
          form.resetFields()
        }}
        onOk={async () => {
          if (!companyId) return
          try {
            const values = await form.validateFields()
            const payload: any = {
              orgId: values.orgId ?? null,
              vendorId: values.vendorId,
              priceListVersionId: values.priceListVersionId,
              orderDate: toLocalDateString(values.orderDate),
              lines: (values.lines || []).map((ln: any) => ({ productId: ln.productId, qty: ln.qty }))
            }
            if (!payload.orgId) delete payload.orgId

            if (editing) {
              await purchaseApi.updatePurchaseOrder(companyId, editing.id, payload)
              message.success('Updated')
            } else {
              await purchaseApi.createPurchaseOrder(companyId, payload)
              message.success('Created')
            }

            setOpen(false)
            setEditing(null)
            form.resetFields()
            await load(companyId)
          } catch (e: any) {
            if (e?.errorFields) return
            message.error(getApiErrorMessage(e, 'Save failed'))
          }
        }}
        okText={editing ? 'Save' : 'Create'}
      >
        <Form layout="vertical" form={form}>
          <Space wrap style={{ width: '100%' }}>
            <Form.Item name="orgId" label="Org (optional)" style={{ width: 260 }}>
              <Select
                allowClear
                loading={orgLoading}
                placeholder="No org"
                options={orgs.map((o) => ({ value: o.id, label: `${o.code || o.id} - ${o.name || ''}` }))}
              />
            </Form.Item>

            <Form.Item name="vendorId" label="Vendor" rules={[{ required: true }]} style={{ width: 260 }}>
              <Select
                loading={vendorLoading}
                placeholder="Select vendor"
                options={vendors.map((v) => ({ value: v.id, label: v.name || String(v.id) }))}
              />
            </Form.Item>

            <Form.Item name="orderDate" label="Order Date" rules={[{ required: true }]} style={{ width: 260 }}>
              <DatePicker style={{ width: '100%' }} />
            </Form.Item>

            <Form.Item name="priceListVersionId" label="Price List Version" rules={[{ required: true }]} style={{ width: 260 }}>
              <Select
                loading={priceListVersionLoading}
                placeholder="Select version"
                options={priceListVersions.map((pv: any) => ({ value: pv.id, label: pv.name || String(pv.id) }))}
              />
            </Form.Item>
          </Space>

          <Typography.Title level={5}>Lines</Typography.Title>

          <Form.List name="lines">
            {(fields, { add, remove }) => (
              <Space direction="vertical" style={{ width: '100%' }} size={8}>
                {fields.map((field) => (
                  <Space key={field.key} align="baseline" wrap style={{ width: '100%' }}>
                    <Form.Item
                      {...field}
                      name={[field.name, 'productId']}
                      label="Product"
                      rules={[{ required: true }]}
                      style={{ width: 420 }}
                    >
                      <Select
                        loading={productLoading}
                        placeholder="Select product"
                        showSearch
                        optionFilterProp="label"
                        options={products.map((p) => ({ value: p.id, label: `${p.code || p.id} - ${p.name || ''}` }))}
                      />
                    </Form.Item>

                    <Form.Item
                      {...field}
                      name={[field.name, 'qty']}
                      label="Qty"
                      rules={[{ required: true }]}
                      style={{ width: 160 }}
                    >
                      <InputNumber style={{ width: '100%' }} min={0.0001} />
                    </Form.Item>

                    <Button danger onClick={() => remove(field.name)} disabled={fields.length <= 1}>
                      Remove
                    </Button>
                  </Space>
                ))}

                <Button onClick={() => add({ qty: 1 })}>Add Line</Button>
              </Space>
            )}
          </Form.List>
        </Form>
      </Modal>

      <Modal
        title={`Goods Receipt${receiptPo?.documentNo ? ` - ${receiptPo.documentNo}` : ''}`}
        open={receiptOpen}
        width={860}
        onCancel={() => {
          setReceiptOpen(false)
          setReceiptPo(null)
          receiptForm.resetFields()
        }}
        onOk={async () => {
          if (!companyId || !receiptPo) return
          try {
            const values = await receiptForm.validateFields()
            const payload: any = {
              toLocatorId: values.toLocatorId,
              movementDate: toLocalDateString(values.movementDate),
              description: values.description,
              lines: (values.lines || []).map((ln: any) => ({
                purchaseOrderLineId: ln.purchaseOrderLineId,
                qty: ln.qty
              }))
            }

            await purchaseApi.createGoodsReceipt(companyId, receiptPo.id, payload)
            message.success('Goods receipt created')

            setReceiptOpen(false)
            setReceiptPo(null)
            receiptForm.resetFields()
            await load(companyId)
          } catch (e: any) {
            if (e?.errorFields) return
            message.error(getApiErrorMessage(e, 'Failed to create goods receipt'))
          }
        }}
        okText="Create"
      >
        <Form layout="vertical" form={receiptForm}>
          <Space wrap style={{ width: '100%' }}>
            <Form.Item name="toLocatorId" label="To Locator" rules={[{ required: true }]} style={{ width: 360 }}>
              <Select
                loading={locatorLoading}
                placeholder="Select locator"
                showSearch
                optionFilterProp="label"
                options={locators.map((l: any) => ({ value: l.id, label: `${l.code || l.id} - ${l.name || ''}` }))}
              />
            </Form.Item>

            <Form.Item name="movementDate" label="Movement Date" rules={[{ required: true }]} style={{ width: 240 }}>
              <DatePicker style={{ width: '100%' }} />
            </Form.Item>
          </Space>

          <Form.Item name="description" label="Description">
            <Input />
          </Form.Item>

          <Typography.Title level={5}>Receipt Lines</Typography.Title>
          <Form.List name="lines">
            {(fields, { remove }) => (
              <Space direction="vertical" style={{ width: '100%' }} size={8}>
                {fields.map((field) => {
                  const polId = receiptForm.getFieldValue(['lines', field.name, 'purchaseOrderLineId'])
                  const poLine = receiptPo?.lines?.find((x) => x.id === polId)
                  const productId = poLine?.productId
                  const label = productId ? productLabelById.get(productId) || productId : polId

                  return (
                    <Space key={field.key} align="baseline" wrap style={{ width: '100%' }}>
                      <Form.Item
                        {...field}
                        name={[field.name, 'purchaseOrderLineId']}
                        label="PO Line"
                        rules={[{ required: true }]}
                        style={{ width: 420 }}
                      >
                        <Select
                          disabled
                          options={[
                            {
                              value: polId,
                              label
                            }
                          ]}
                        />
                      </Form.Item>

                      <Form.Item
                        {...field}
                        name={[field.name, 'qty']}
                        label="Qty"
                        rules={[{ required: true }]}
                        style={{ width: 200 }}
                      >
                        <InputNumber style={{ width: '100%' }} min={0.0001} />
                      </Form.Item>

                      <Button danger onClick={() => remove(field.name)}>
                        Remove
                      </Button>
                    </Space>
                  )
                })}
              </Space>
            )}
          </Form.List>
        </Form>
      </Modal>
    </Space>
  )
}

// frontend/src/views/modules/purchase/PurchaseOrdersView.vue
<template>
  <div style="display: flex; flex-direction: column; gap: 12px">
    <el-card>
      <div style="display: flex; flex-direction: column; gap: 10px">
        <div style="display: flex; align-items: center; justify-content: space-between; gap: 12px">
          <div>
            <div style="font-size: 18px; font-weight: 600">Purchase Orders</div>
            <div style="color: #606266">Buat PO untuk vendor, lalu lanjut Goods Receipt.</div>
          </div>
          <el-button type="primary" :disabled="!ctx.companyId" @click="openCreate">Create PO</el-button>
        </div>

        <CompanyOrgBar />
      </div>
    </el-card>

    <el-card>
      <el-alert v-if="!ctx.companyId" title="Pilih company dulu." type="warning" show-icon style="margin-bottom: 12px" />

      <el-table :data="rows" style="width: 100%" v-loading="loading">
        <el-table-column prop="documentNo" label="Document No" width="180" />
        <el-table-column prop="status" label="Status" width="140" />
        <el-table-column prop="orderDate" label="Order Date" width="140" />
        <el-table-column prop="grandTotal" label="Grand Total" width="140" />
        <el-table-column label="Action" width="260">
          <template #default="scope">
            <el-button size="small" type="success" :disabled="!canApproveRow(scope.row)" @click="onApprove(scope.row)">Approve</el-button>
            <el-button size="small" type="primary" plain :disabled="!canReceiptRow(scope.row)" @click="openGoodsReceipt(scope.row)">
              Goods Receipt
            </el-button>
            <el-button size="small" @click="openEdit(scope.row)" :disabled="!canEditRow(scope.row)">Edit</el-button>
            <el-button type="danger" size="small" plain @click="onDelete(scope.row)" :disabled="!canEditRow(scope.row)">Delete</el-button>
          </template>
        </el-table-column>
      </el-table>
    </el-card>

    <el-dialog v-model="createOpen" :title="dialogTitle" width="860px">
      <el-form label-position="top">
        <el-alert
          v-if="ctx.companyId && (priceLists.length === 0 || priceListVersions.length === 0 || !form.priceListVersionId)"
          title="Price List Version belum dipilih/tersedia. Buat Price List & Version dulu di Master Data, lalu pilih versinya."
          type="warning"
          show-icon
          style="margin-bottom: 12px"
        />

        <el-alert
          v-if="missingPriceProductLabels.length"
          :title="`Harga belum di-setup untuk: ${missingPriceProductLabels.join(', ')}. Isi Product Prices dulu di Master Data > Price Lists.`"
          type="warning"
          show-icon
          style="margin-bottom: 12px"
        />

        <div style="display: grid; grid-template-columns: 1fr 1fr 1fr; gap: 12px">
          <el-form-item label="Org">
            <el-input v-model="form.orgId" placeholder="Auto from context" :disabled="true" />
          </el-form-item>
          <el-form-item label="Vendor">
            <el-select v-model="form.vendorId" filterable placeholder="Select vendor" style="width: 100%" :disabled="vendors.length === 0">
              <el-option v-for="v in vendors" :key="v.id" :label="v.name || v.code || String(v.id)" :value="v.id" />
            </el-select>
          </el-form-item>
          <el-form-item label="Price List Version">
            <el-select v-model="form.priceListVersionId" filterable placeholder="Select version" style="width: 100%" :disabled="priceListVersions.length === 0">
              <el-option v-for="p in priceListVersions" :key="p.id" :label="p.name || p.code || String(p.id)" :value="p.id" />
            </el-select>
          </el-form-item>
        </div>

        <el-form-item label="Order Date">
          <el-date-picker v-model="form.orderDate" type="date" value-format="YYYY-MM-DD" style="width: 220px" />
        </el-form-item>

        <div style="display: flex; align-items: center; justify-content: space-between; margin: 12px 0 6px">
          <div style="font-weight: 600">Lines</div>
          <el-button size="small" @click="addLine">Add Line</el-button>
        </div>

        <el-table :data="form.lines" size="small" style="width: 100%">
          <el-table-column label="Product" min-width="320">
            <template #default="scope">
              <el-select v-model="scope.row.productId" filterable placeholder="Select product" style="width: 100%" :disabled="products.length === 0">
                <el-option v-for="p in products" :key="p.id" :label="`${p.code} - ${p.name}`" :value="p.id" />
              </el-select>
            </template>
          </el-table-column>
          <el-table-column label="Qty" width="180">
            <template #default="scope">
              <el-input v-model="scope.row.qty" />
            </template>
          </el-table-column>
          <el-table-column label="" width="70">
            <template #default="scope">
              <el-button type="danger" plain size="small" @click="removeLine(scope.$index)">X</el-button>
            </template>
          </el-table-column>
        </el-table>

        <el-alert v-if="vendors.length === 0" title="Vendor belum ada. Buat Business Partner (vendor) dulu di Master Data." type="warning" show-icon style="margin-top: 12px" />
        <el-alert v-if="products.length === 0" title="Product belum ada. Buat Product dulu di Master Data." type="warning" show-icon style="margin-top: 12px" />
      </el-form>

      <template #footer>
        <el-button @click="createOpen = false">Cancel</el-button>
        <el-button type="primary" :loading="saving" :disabled="!canSave" @click="save">Save</el-button>
      </template>
    </el-dialog>

    <el-dialog v-model="receiptOpen" title="Goods Receipt" width="980px">
      <el-form label-position="top">
        <el-alert v-if="!ctx.companyId" title="Pilih company dulu." type="warning" show-icon style="margin-bottom: 12px" />

        <div style="display: grid; grid-template-columns: 1fr 1fr 1fr; gap: 12px">
          <el-form-item label="To Locator">
            <el-select v-model="receiptForm.toLocatorId" filterable placeholder="Select locator" style="width: 100%" :disabled="locators.length === 0">
              <el-option v-for="l in locators" :key="l.id" :label="`${l.code} - ${l.name}`" :value="l.id" />
            </el-select>
          </el-form-item>
          <el-form-item label="Receipt Date">
            <el-date-picker v-model="receiptForm.movementDate" type="date" value-format="YYYY-MM-DD" style="width: 220px" />
          </el-form-item>
          <el-form-item label="Description">
            <el-input v-model="receiptForm.description" placeholder="optional" />
          </el-form-item>
        </div>

        <div style="display: flex; align-items: center; justify-content: space-between; margin: 12px 0 6px">
          <div style="font-weight: 600">Lines</div>
        </div>

        <el-table :data="receiptForm.lines" size="small" style="width: 100%">
          <el-table-column label="Product" min-width="320">
            <template #default="scope">
              <span>{{ productLabelById(scope.row.productId) }}</span>
            </template>
          </el-table-column>
          <el-table-column label="Ordered" width="140">
            <template #default="scope">
              <span>{{ scope.row.orderedQty }}</span>
            </template>
          </el-table-column>
          <el-table-column label="Received" width="140">
            <template #default="scope">
              <span>{{ scope.row.receivedQty }}</span>
            </template>
          </el-table-column>
          <el-table-column label="Receive Qty" width="180">
            <template #default="scope">
              <el-input v-model="scope.row.qty" placeholder="e.g. 1" />
            </template>
          </el-table-column>
        </el-table>

        <el-alert v-if="locators.length === 0" title="Locator belum ada. Buat Locator dulu di Inventory > Locators." type="warning" show-icon style="margin-top: 12px" />
      </el-form>

      <template #footer>
        <el-button @click="receiptOpen = false">Cancel</el-button>
        <el-button type="primary" :loading="receiptSaving" :disabled="!canReceiptSave" @click="submitGoodsReceipt">Submit</el-button>
      </template>
    </el-dialog>
  </div>
</template>

<script setup>
import { computed, onMounted, reactive, ref, watch } from 'vue'
import { ElMessage, ElMessageBox } from 'element-plus'
import { inventoryApi, masterDataApi, purchaseApi } from '@/utils/api'
import { useContextStore } from '@/stores/context'
import CompanyOrgBar from '@/views/modules/common/CompanyOrgBar.vue'

const ctx = useContextStore()

const rows = ref([])
const loading = ref(false)

const vendors = ref([])
const products = ref([])
const priceLists = ref([])
const priceListVersions = ref([])
const productPrices = ref([])

const locators = ref([])

const createOpen = ref(false)
const saving = ref(false)

const receiptOpen = ref(false)
const receiptSaving = ref(false)
const receiptPoId = ref(null)

const editMode = ref('create')
const editingId = ref(null)

const dialogTitle = computed(() => (editMode.value === 'edit' ? 'Edit Purchase Order' : 'Create Purchase Order'))

const form = reactive({
  orgId: null,
  vendorId: null,
  priceListVersionId: null,
  orderDate: '',
  lines: []
})

const receiptForm = reactive({
  toLocatorId: null,
  movementDate: '',
  description: '',
  lines: []
})

const canReceiptSave = computed(() => {
  if (!ctx.companyId) return false
  if (!receiptPoId.value) return false
  if (!receiptForm.toLocatorId) return false
  if (!receiptForm.movementDate) return false
  if (!Array.isArray(receiptForm.lines) || receiptForm.lines.length === 0) return false
  return receiptForm.lines.some((l) => {
    const qty = Number(l.qty)
    if (!Number.isFinite(qty) || qty <= 0) return false
    const remaining = Math.max(0, Number(l.orderedQty ?? 0) - Number(l.receivedQty ?? 0))
    return qty <= remaining
  })
})

const canSave = computed(() => {
  if (!ctx.companyId) return false
  if (!form.vendorId) return false
  if (!form.priceListVersionId) return false
  if (!form.orderDate) return false
  if (!Array.isArray(form.lines) || form.lines.length === 0) return false
  if (!form.lines.every((l) => l.productId && String(l.qty).trim())) return false
  // ensure price exists for each selected product
  const priced = new Set((productPrices.value || []).map((pp) => pp.productId))
  return form.lines.every((l) => priced.has(l.productId))
})

const missingPriceProductLabels = computed(() => {
  if (!createOpen.value) return []
  if (!form.priceListVersionId) return []
  const priced = new Set((productPrices.value || []).map((pp) => pp.productId))
  const uniq = new Map()
  for (const l of form.lines || []) {
    if (!l?.productId) continue
    if (priced.has(l.productId)) continue
    const p = (products.value || []).find((x) => x.id === l.productId)
    const label = p ? `${p.code}` : String(l.productId)
    uniq.set(l.productId, label)
  }
  return Array.from(uniq.values())
})

function addLine() {
  form.lines.push({ productId: products.value[0]?.id || null, qty: '1' })
}

function removeLine(idx) {
  form.lines.splice(idx, 1)
}

async function loadLookups() {
  if (!ctx.companyId) {
    vendors.value = []
    products.value = []
    priceLists.value = []
    priceListVersions.value = []
    productPrices.value = []
    locators.value = []
    return
  }

  const [bps, prods, pls] = await Promise.all([
    masterDataApi.listBusinessPartners(ctx.companyId),
    masterDataApi.listProducts(ctx.companyId),
    masterDataApi.listPriceLists(ctx.companyId)
  ])

  vendors.value = (bps || []).filter((x) => x.type === 'VENDOR' || x.type === 'BOTH')
  products.value = prods || []
  priceLists.value = pls || []

  const plId = priceLists.value[0]?.id
  priceListVersions.value = plId ? await masterDataApi.listPriceListVersions(plId) : []

  const plvId = priceListVersions.value[0]?.id
  productPrices.value = plvId ? await masterDataApi.listProductPrices(plvId) : []

  locators.value = await inventoryApi.listLocators(ctx.companyId)
}

async function load() {
  if (!ctx.companyId) {
    rows.value = []
    return
  }
  loading.value = true
  try {
    rows.value = await purchaseApi.listPurchaseOrders(ctx.companyId)
  } finally {
    loading.value = false
  }
}

function openCreate() {
  editMode.value = 'create'
  editingId.value = null
  form.orgId = ctx.orgId
  form.vendorId = vendors.value[0]?.id || null
  form.priceListVersionId = priceListVersions.value[0]?.id || null
  form.orderDate = new Date().toISOString().slice(0, 10)
  form.lines = []
  addLine()
  createOpen.value = true
}

async function openEdit(row) {
  if (!row?.id) return
  editMode.value = 'edit'
  editingId.value = row.id

  form.orgId = row.orgId || null
  form.vendorId = row.vendorId || null
  form.priceListVersionId = row.priceListVersionId || null
  form.orderDate = row.orderDate || new Date().toISOString().slice(0, 10)
  form.lines = (row.lines || []).map((l) => ({
    productId: l.productId,
    qty: String(l.qty ?? '')
  }))
  if (form.lines.length === 0) addLine()

  productPrices.value = form.priceListVersionId ? await masterDataApi.listProductPrices(form.priceListVersionId) : []
  createOpen.value = true
}

function canEditRow(row) {
  return !!ctx.companyId && row?.status === 'DRAFTED'
}

function canApproveRow(row) {
  return !!ctx.companyId && row?.status === 'DRAFTED'
}

function canReceiptRow(row) {
  return !!ctx.companyId && (row?.status === 'APPROVED' || row?.status === 'PARTIALLY_COMPLETED')
}

function productLabelById(productId) {
  const p = (products.value || []).find((x) => x.id === productId)
  return p ? `${p.code} - ${p.name}` : String(productId ?? '')
}

function openGoodsReceipt(row) {
  if (!row?.id) return
  receiptPoId.value = row.id
  receiptForm.toLocatorId = locators.value[0]?.id || null
  receiptForm.movementDate = new Date().toISOString().slice(0, 10)
  receiptForm.description = `Goods Receipt for PO ${row.documentNo}`
  receiptForm.lines = (row.lines || []).map((l) => {
    const ordered = Number(l.qty ?? 0)
    const received = Number(l.receivedQty ?? 0)
    const remaining = Math.max(0, ordered - received)
    return {
      purchaseOrderLineId: l.id,
      productId: l.productId,
      orderedQty: ordered,
      receivedQty: received,
      qty: remaining > 0 ? String(remaining) : '0'
    }
  })
  receiptOpen.value = true
}

async function submitGoodsReceipt() {
  if (!receiptPoId.value) return
  receiptSaving.value = true
  try {
    const invalid = (receiptForm.lines || []).find((l) => {
      const qty = Number(l.qty)
      if (!Number.isFinite(qty) || qty <= 0) return false
      const remaining = Math.max(0, Number(l.orderedQty ?? 0) - Number(l.receivedQty ?? 0))
      return qty > remaining
    })
    if (invalid) {
      const remaining = Math.max(0, Number(invalid.orderedQty ?? 0) - Number(invalid.receivedQty ?? 0))
      throw new Error(`Receive qty exceeds remaining qty (remaining=${remaining})`)
    }

    const lines = (receiptForm.lines || [])
      .map((l) => ({
        purchaseOrderLineId: l.purchaseOrderLineId,
        qty: l.qty
      }))
      .filter((l) => {
        const qty = Number(l.qty)
        return Number.isFinite(qty) && qty > 0
      })

    await purchaseApi.createGoodsReceipt(ctx.companyId, receiptPoId.value, {
      toLocatorId: receiptForm.toLocatorId,
      movementDate: receiptForm.movementDate,
      description: receiptForm.description,
      lines
    })

    ElMessage.success('Goods Receipt created')
    receiptOpen.value = false
    await load()
  } catch (e) {
    ElMessage.error(e?.response?.data?.message || e?.message || 'Failed')
  } finally {
    receiptSaving.value = false
  }
}

async function onApprove(row) {
  if (!row?.id) return
  try {
    await ElMessageBox.confirm(`Approve Purchase Order "${row.documentNo}"?`, 'Confirm', {
      type: 'warning',
      confirmButtonText: 'Approve',
      cancelButtonText: 'Cancel'
    })
    await purchaseApi.approvePurchaseOrder(ctx.companyId, row.id)
    ElMessage.success('Purchase Order approved')
    await load()
  } catch (e) {
    if (e === 'cancel' || e === 'close') return
    ElMessage.error(e?.response?.data?.message || e?.message || 'Failed')
  }
}

watch(
  () => form.priceListVersionId,
  async (v) => {
    if (!createOpen.value) return
    productPrices.value = v ? await masterDataApi.listProductPrices(v) : []
  }
)

async function save() {
  saving.value = true
  try {
    const payload = {
      orgId: form.orgId || null,
      vendorId: form.vendorId,
      priceListVersionId: form.priceListVersionId,
      orderDate: form.orderDate,
      lines: form.lines.map((l) => ({
        productId: l.productId,
        qty: l.qty
      }))
    }

    if (editMode.value === 'edit' && editingId.value) {
      await purchaseApi.updatePurchaseOrder(ctx.companyId, editingId.value, payload)
      ElMessage.success('Purchase Order updated')
    } else {
      await purchaseApi.createPurchaseOrder(ctx.companyId, payload)
      ElMessage.success('Purchase Order created')
    }
    createOpen.value = false
    await load()
  } catch (e) {
    ElMessage.error(e?.response?.data?.message || e?.message || 'Failed')
  } finally {
    saving.value = false
  }
}

async function onDelete(row) {
  if (!row?.id) return
  try {
    await ElMessageBox.confirm(`Delete Purchase Order "${row.documentNo}"?`, 'Confirm', {
      type: 'warning',
      confirmButtonText: 'Delete',
      cancelButtonText: 'Cancel'
    })
    await purchaseApi.deletePurchaseOrder(ctx.companyId, row.id)
    ElMessage.success('Purchase Order deleted')
    await load()
  } catch (e) {
    if (e === 'cancel' || e === 'close') return
    ElMessage.error(e?.response?.data?.message || e?.message || 'Failed')
  }
}

watch(
  () => ctx.companyId,
  async () => {
    await loadLookups()
    await load()
  }
)

watch(
  () => ctx.orgId,
  () => {
    form.orgId = ctx.orgId
  }
)

watch(
  () => priceListVersions.value,
  (v) => {
    if (!createOpen.value) return
    if (form.priceListVersionId) return
    if (Array.isArray(v) && v.length > 0) form.priceListVersionId = v[0].id
  }
)

onMounted(async () => {
  await loadLookups()
  await load()
})
</script>
