// frontend2/src/views/layouts/AppLayout.tsx
import { Layout, Menu } from 'antd'
import type { MenuProps } from 'antd'
import { Outlet, useLocation, useNavigate } from 'react-router-dom'
import { useAuthStore } from '@/stores/auth'

const { Header, Sider, Content } = Layout

export default function AppLayout() {
  const location = useLocation()
  const navigate = useNavigate()
  const logout = useAuthStore((s) => s.logout)

  const items: MenuProps['items'] = [
    { key: '/', label: 'Dashboard' },
    {
      key: 'core',
      label: 'Core',
      children: [
        { key: '/modules/core/companies', label: 'Companies' },
        { key: '/modules/core/orgs', label: 'Orgs' }
      ]
    },
    {
      key: 'masterdata',
      label: 'Master Data',
      children: [
        { key: '/modules/masterdata/uoms', label: 'UOMs' },
        { key: '/modules/masterdata/business-partners', label: 'Business Partners' },
        { key: '/modules/masterdata/currencies', label: 'Currencies' },
        { key: '/modules/masterdata/products', label: 'Products' },
        { key: '/modules/masterdata/price-lists', label: 'Price Lists' },
        { key: '/modules/masterdata/warehouses', label: 'Warehouses' }
      ]
    },
    {
      key: 'inventory',
      label: 'Inventory',
      children: [
        { key: '/modules/inventory/locators', label: 'Locators' },
        { key: '/modules/inventory/onhand', label: 'On-hand' },
        { key: '/modules/inventory/movements', label: 'Movements' },
        { key: '/modules/inventory/adjustments', label: 'Adjustments' }
      ]
    },
    {
      key: 'purchase',
      label: 'Purchase',
      children: [{ key: '/modules/purchase/purchase-orders', label: 'Purchase Orders' }]
    },
    {
      key: 'sales',
      label: 'Sales',
      children: [{ key: '/modules/sales/sales-orders', label: 'Sales Orders' }]
    },
    {
      key: 'manufacturing',
      label: 'Manufacturing',
      children: [
        { key: '/modules/manufacturing/boms', label: 'BOMs' },
        { key: '/modules/manufacturing/work-orders', label: 'Work Orders' },
        { key: '/modules/manufacturing/reports', label: 'Reports' }
      ]
    },
    {
      key: 'finance',
      label: 'Finance',
      children: [
        { key: '/modules/finance/gl-accounts', label: 'GL Accounts' },
        { key: '/modules/finance/periods', label: 'Periods' },
        { key: '/modules/finance/reports', label: 'Reports' }
      ]
    },
    {
      key: 'hr',
      label: 'HR',
      children: [
        { key: '/modules/hr', label: 'Overview' },
        { key: '/modules/hr/departments', label: 'Departments' },
        { key: '/modules/hr/employees', label: 'Employees' }
      ]
    },
    {
      key: 'admin',
      label: 'Admin',
      children: [{ key: '/modules/admin/users', label: 'Users' }]
    },
    {
      key: 'tools',
      label: 'Tools',
      children: [{ key: '/tools/api-explorer', label: 'API Explorer' }]
    }
  ]

  function flattenKeys(input: MenuProps['items']): string[] {
    const out: string[] = []
    const walk = (arr: MenuProps['items']) => {
      ;(arr || []).forEach((it: any) => {
        if (!it) return
        if (typeof it.key === 'string' && it.key.startsWith('/')) out.push(it.key)
        if (it.children) walk(it.children)
      })
    }
    walk(input)
    return out
  }

  const navigableKeys = flattenKeys(items)

  const selectedKey = (() => {
    const path = location.pathname
    const exact = navigableKeys.find((k) => k === path)
    if (exact) return exact
    const prefixes = navigableKeys.filter((k) => k !== '/' && path.startsWith(k))
    if (prefixes.length) {
      prefixes.sort((a, b) => b.length - a.length)
      return prefixes[0]
    }
    if (path === '/') return '/'
    return undefined
  })()

  return (
    <Layout style={{ minHeight: '100vh' }}>
      <Sider theme="light" width={260} style={{ borderRight: '1px solid #f0f0f0' }}>
        <div style={{ padding: 16, fontWeight: 700 }}>ERP</div>
        <Menu
          mode="inline"
          selectedKeys={selectedKey ? [selectedKey] : []}
          items={items}
          onClick={(e) => {
            if (typeof e.key === 'string') navigate(e.key)
          }}
        />
      </Sider>

      <Layout>
        <Header style={{ background: '#fff', borderBottom: '1px solid #f0f0f0', display: 'flex', justifyContent: 'flex-end' }}>
          <a
            onClick={(e) => {
              e.preventDefault()
              logout()
              navigate('/login')
            }}
          >
            Logout
          </a>
        </Header>
        <Content style={{ padding: 16 }}>
          <Outlet />
        </Content>
      </Layout>
    </Layout>
  )
}

// frontend/src/views/layouts/AppLayout.vue
<template>
  <el-container style="min-height: 100vh">
    <el-aside width="260px" style="border-right: 1px solid #ebeef5">
      <div style="height: 56px; display: flex; align-items: center; padding: 0 16px; font-weight: 600">
        ERP
      </div>
      <el-menu :default-active="active" router style="border-right: none">
        <el-menu-item index="/">Dashboard</el-menu-item>
        <el-sub-menu index="/modules">
          <template #title>Modules</template>
          <el-sub-menu index="/modules/core">
            <template #title>Core Setup</template>
            <el-menu-item index="/modules/core/companies">Companies</el-menu-item>
            <el-menu-item index="/modules/core/orgs">Organizations</el-menu-item>
          </el-sub-menu>

          <el-sub-menu index="/modules/masterdata">
            <template #title>Master Data</template>
            <el-menu-item index="/modules/masterdata/uoms">UoM</el-menu-item>
            <el-menu-item index="/modules/masterdata/business-partners">Business Partners</el-menu-item>
            <el-menu-item index="/modules/masterdata/currencies">Currencies</el-menu-item>
            <el-menu-item index="/modules/masterdata/products">Products</el-menu-item>
            <el-menu-item index="/modules/masterdata/warehouses">Warehouses</el-menu-item>
            <el-menu-item index="/modules/masterdata/price-lists">Price Lists</el-menu-item>
          </el-sub-menu>

          <el-sub-menu index="/modules/purchase">
            <template #title>Purchase</template>
            <el-menu-item index="/modules/purchase/purchase-orders">Purchase Orders</el-menu-item>
          </el-sub-menu>

          <el-sub-menu index="/modules/sales">
            <template #title>Sales</template>
            <el-menu-item index="/modules/sales/sales-orders">Sales Orders</el-menu-item>
          </el-sub-menu>

          <el-sub-menu index="/modules/inventory">
            <template #title>Inventory</template>
            <el-menu-item index="/modules/masterdata/warehouses">Warehouses</el-menu-item>
            <el-menu-item index="/modules/inventory/locators">Locators</el-menu-item>
            <el-menu-item index="/modules/inventory/onhand">On-hand</el-menu-item>
            <el-menu-item index="/modules/inventory/movements">Movements</el-menu-item>
            <el-menu-item index="/modules/inventory/adjustments">Adjustments</el-menu-item>
          </el-sub-menu>
          <el-sub-menu index="/modules/manufacturing">
            <template #title>Manufacturing</template>
            <el-menu-item index="/modules/manufacturing">Overview</el-menu-item>
            <el-menu-item index="/modules/manufacturing/boms">BOMs</el-menu-item>
            <el-menu-item index="/modules/manufacturing/work-orders">Work Orders</el-menu-item>
            <el-menu-item index="/modules/manufacturing/reports">Reports</el-menu-item>
          </el-sub-menu>
          <el-sub-menu index="/modules/finance">
            <template #title>Finance</template>
            <el-menu-item index="/modules/finance">Overview</el-menu-item>
            <el-menu-item index="/modules/finance/gl-accounts">GL Accounts</el-menu-item>
            <el-menu-item index="/modules/finance/periods">Periods</el-menu-item>
            <el-menu-item index="/modules/finance/reports">Reports</el-menu-item>
          </el-sub-menu>
          <el-sub-menu index="/modules/hr">
            <template #title>HR</template>
            <el-menu-item index="/modules/hr">Overview</el-menu-item>
            <el-menu-item index="/modules/hr/departments">Departments</el-menu-item>
            <el-menu-item index="/modules/hr/employees">Employees</el-menu-item>
          </el-sub-menu>
          <el-sub-menu index="/modules/admin">
            <template #title>Admin</template>
            <el-menu-item index="/modules/admin">Overview</el-menu-item>
            <el-menu-item index="/modules/admin/users">Users</el-menu-item>
          </el-sub-menu>
        </el-sub-menu>
        <el-sub-menu index="/tools">
          <template #title>Tools</template>
          <el-menu-item index="/tools/api-explorer">API Explorer</el-menu-item>
        </el-sub-menu>
      </el-menu>
    </el-aside>

    <el-container>
      <el-header style="display: flex; align-items: center; justify-content: space-between; border-bottom: 1px solid #ebeef5">
        <div />
        <div style="display: flex; gap: 8px; align-items: center">
          <el-tag v-if="auth.role" type="info">{{ auth.role }}</el-tag>
          <el-button size="small" @click="onLogout">Logout</el-button>
        </div>
      </el-header>

      <el-main style="background: #f5f7fa">
        <router-view />
      </el-main>
    </el-container>
  </el-container>
</template>

<script setup>
import { computed } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import { useAuthStore } from '@/stores/auth'

const route = useRoute()
const router = useRouter()
const auth = useAuthStore()

const active = computed(() => route.path)

function onLogout() {
  auth.logout()
  router.push('/login')
}
</script>
