// frontend/src/views/modules/inventory/LocatorsView.vue
<template>
  <div style="display: flex; flex-direction: column; gap: 12px">
    <el-card>
      <div style="display: flex; flex-direction: column; gap: 10px">
        <div style="display: flex; align-items: center; justify-content: space-between; gap: 12px">
          <div>
            <div style="font-size: 18px; font-weight: 600">Locators</div>
            <div style="color: #606266">Rak/lokasi penyimpanan stok per warehouse.</div>
          </div>
          <el-button type="primary" :disabled="!ctx.companyId" @click="openCreate">Create Locator</el-button>
        </div>

        <CompanyOrgBar />
      </div>
    </el-card>

    <el-card>
      <el-alert v-if="!ctx.companyId" title="Pilih company dulu." type="warning" show-icon style="margin-bottom: 12px" />

      <div style="display: flex; gap: 8px; align-items: center; margin-bottom: 10px">
        <el-select v-model="filters.warehouseId" placeholder="Filter warehouse" clearable style="width: 260px" :disabled="warehouses.length === 0">
          <el-option v-for="w in warehouses" :key="w.id" :label="`${w.code} - ${w.name}`" :value="w.id" />
        </el-select>
        <el-button size="small" :disabled="!ctx.companyId" @click="load">Refresh</el-button>
      </div>

      <el-table :data="rows" style="width: 100%" v-loading="loading">
        <el-table-column prop="code" label="Code" width="160" />
        <el-table-column prop="name" label="Name" />
        <el-table-column prop="active" label="Active" width="120">
          <template #default="scope">
            <el-tag size="small" :type="scope.row.active ? 'success' : 'info'">{{ scope.row.active ? 'Yes' : 'No' }}</el-tag>
          </template>
        </el-table-column>
      </el-table>

      <el-alert
        v-if="ctx.companyId && warehouses.length === 0"
        title="Warehouse belum ada. Buat dulu di Master Data > Warehouses."
        type="warning"
        show-icon
        style="margin-top: 12px"
      />
    </el-card>

    <el-dialog v-model="createOpen" title="Create Locator" width="720px">
      <el-form label-position="top">
        <div style="display: grid; grid-template-columns: 1fr 1fr; gap: 12px">
          <el-form-item label="Warehouse">
            <el-select v-model="form.warehouseId" filterable placeholder="Select warehouse" style="width: 100%" :disabled="warehouses.length === 0">
              <el-option v-for="w in warehouses" :key="w.id" :label="`${w.code} - ${w.name}`" :value="w.id" />
            </el-select>
          </el-form-item>
          <el-form-item label="Org">
            <el-input v-model="form.orgId" placeholder="Auto from context" :disabled="true" />
          </el-form-item>
        </div>
        <div style="display: grid; grid-template-columns: 1fr 1fr; gap: 12px">
          <el-form-item label="Code">
            <el-input v-model="form.code" placeholder="e.g. RACK-A1" />
          </el-form-item>
          <el-form-item label="Name">
            <el-input v-model="form.name" placeholder="e.g. Rack A1" />
          </el-form-item>
        </div>
      </el-form>

      <template #footer>
        <el-button @click="createOpen = false">Cancel</el-button>
        <el-button type="primary" :loading="saving" :disabled="!canSave" @click="save">Save</el-button>
      </template>
    </el-dialog>
  </div>
</template>

<script setup>
import { computed, onMounted, reactive, ref, watch } from 'vue'
import { ElMessage } from 'element-plus'
import { inventoryApi, masterDataApi } from '@/utils/api'
import { useContextStore } from '@/stores/context'
import CompanyOrgBar from '@/views/modules/common/CompanyOrgBar.vue'

const ctx = useContextStore()

const rows = ref([])
const warehouses = ref([])
const loading = ref(false)

const filters = reactive({
  warehouseId: null
})

const createOpen = ref(false)
const saving = ref(false)

const form = reactive({
  warehouseId: null,
  orgId: null,
  code: '',
  name: ''
})

const canSave = computed(() => Boolean(ctx.companyId && form.warehouseId && form.code.trim() && form.name.trim()))

async function loadWarehouses() {
  if (!ctx.companyId) {
    warehouses.value = []
    return
  }
  try {
    warehouses.value = await masterDataApi.listWarehouses(ctx.companyId)
  } catch {
    warehouses.value = []
  }
}

async function load() {
  if (!ctx.companyId) {
    rows.value = []
    return
  }
  loading.value = true
  try {
    rows.value = await inventoryApi.listLocators(ctx.companyId, filters.warehouseId ? { warehouseId: filters.warehouseId } : undefined)
  } catch (e) {
    ElMessage.error(e?.response?.data?.message || e?.message || 'Failed')
  } finally {
    loading.value = false
  }
}

function openCreate() {
  form.warehouseId = warehouses.value[0]?.id || null
  form.orgId = ctx.orgId
  form.code = ''
  form.name = ''
  createOpen.value = true
}

async function save() {
  saving.value = true
  try {
    await inventoryApi.createLocator(ctx.companyId, {
      warehouseId: form.warehouseId,
      orgId: ctx.orgId || null,
      code: form.code,
      name: form.name
    })
    ElMessage.success('Locator created')
    createOpen.value = false
    await load()
  } catch (e) {
    ElMessage.error(e?.response?.data?.message || e?.message || 'Failed')
  } finally {
    saving.value = false
  }
}

watch(
  () => ctx.companyId,
  async () => {
    await loadWarehouses()
    await load()
  }
)

watch(
  () => filters.warehouseId,
  () => load()
)

watch(
  () => ctx.orgId,
  () => {
    form.orgId = ctx.orgId
  }
)

onMounted(async () => {
  await loadWarehouses()
  await load()
})
</script>

// frontend2_new/src/views/modules/inventory/LocatorsView.tsx
import { Button, Card, Form, Input, Modal, Select, Space, Table, Tag, Typography, message } from 'antd'
import type { ColumnsType } from 'antd/es/table'
import { useEffect, useMemo, useState } from 'react'
import { coreApi, inventoryApi, masterDataApi } from '@/utils/api'
import { useContextStore } from '@/stores/context'
import { getApiErrorMessage } from '@/utils/error'

type CompanyRow = { id: number; code?: string; name?: string }

type OrgRow = { id: number; code?: string; name?: string }

type WarehouseRow = { id: number; code?: string; name?: string }

type LocatorRow = { id: number; code?: string; name?: string; active?: boolean; warehouse?: any; org?: any }

export default function LocatorsView() {
  const companyId = useContextStore((s) => s.companyId)
  const setCompanyId = useContextStore((s) => s.setCompanyId)

  const [companyLoading, setCompanyLoading] = useState(false)
  const [companies, setCompanies] = useState<CompanyRow[]>([])

  const [lookupLoading, setLookupLoading] = useState(false)
  const [orgs, setOrgs] = useState<OrgRow[]>([])
  const [warehouses, setWarehouses] = useState<WarehouseRow[]>([])

  const [loading, setLoading] = useState(false)
  const [rows, setRows] = useState<LocatorRow[]>([])

  const [warehouseFilterId, setWarehouseFilterId] = useState<number | undefined>(undefined)

  const [open, setOpen] = useState(false)
  const [form] = Form.useForm()

  const loadCompanies = async () => {
    setCompanyLoading(true)
    try {
      const res = await coreApi.listCompanies()
      setCompanies(res || [])
      if (!companyId && Array.isArray(res) && res.length > 0) setCompanyId(res[0]?.id)
    } catch (e: any) {
      message.error(getApiErrorMessage(e, 'Failed to load companies'))
    } finally {
      setCompanyLoading(false)
    }
  }

  const loadLookups = async (cid: number) => {
    setLookupLoading(true)
    try {
      const [orgRes, whRes] = await Promise.all([coreApi.listOrgs(cid), masterDataApi.listWarehouses(cid)])
      setOrgs(orgRes || [])
      setWarehouses(whRes || [])
    } catch (e: any) {
      message.error(getApiErrorMessage(e, 'Failed to load lookups'))
      setOrgs([])
      setWarehouses([])
    } finally {
      setLookupLoading(false)
    }
  }

  const load = async (cid: number, whId?: number) => {
    setLoading(true)
    try {
      const params = whId ? { warehouseId: whId } : undefined
      const res = await inventoryApi.listLocators(cid, params)
      setRows(res || [])
    } catch (e: any) {
      message.error(getApiErrorMessage(e, 'Failed to load locators'))
      setRows([])
    } finally {
      setLoading(false)
    }
  }

  useEffect(() => {
    void loadCompanies()
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [])

  useEffect(() => {
    if (!companyId) return
    void loadLookups(companyId)
    void load(companyId, warehouseFilterId)
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [companyId])

  useEffect(() => {
    if (!companyId) return
    void load(companyId, warehouseFilterId)
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [warehouseFilterId])

  const companyOptions = useMemo(
    () => companies.map((c) => ({ value: c.id, label: `${c.code || c.id} - ${c.name || ''}` })),
    [companies]
  )

  const orgOptions = useMemo(
    () => orgs.map((o) => ({ value: o.id, label: `${o.code || o.id} - ${o.name || ''}` })),
    [orgs]
  )

  const warehouseOptions = useMemo(
    () => warehouses.map((w: any) => ({ value: w.id, label: `${w.code || w.id} - ${w.name || ''}` })),
    [warehouses]
  )

  const columns: ColumnsType<LocatorRow> = [
    { title: 'ID', dataIndex: 'id', width: 90 },
    { title: 'Code', dataIndex: 'code', width: 160 },
    { title: 'Name', dataIndex: 'name' },
    {
      title: 'Warehouse',
      dataIndex: 'warehouse',
      width: 260,
      render: (w: any) => (w?.code ? `${w.code} - ${w.name || ''}` : w?.id || '-')
    },
    {
      title: 'Org',
      dataIndex: 'org',
      width: 220,
      render: (o: any) => (o?.code ? `${o.code} - ${o.name || ''}` : o?.id || '-')
    },
    {
      title: 'Active',
      dataIndex: 'active',
      width: 100,
      render: (v: any) => (v ? <Tag color="green">YES</Tag> : <Tag color="red">NO</Tag>)
    }
  ]

  return (
    <Space direction="vertical" size={16} style={{ width: '100%' }}>
      <Card>
        <Space style={{ width: '100%', justifyContent: 'space-between' }}>
          <Typography.Title level={4} style={{ margin: 0 }}>
            Locators
          </Typography.Title>
          <Space>
            <Button onClick={() => companyId && loadLookups(companyId)} disabled={!companyId} loading={lookupLoading}>
              Refresh Lookups
            </Button>
            <Button onClick={() => companyId && load(companyId, warehouseFilterId)} disabled={!companyId} loading={loading}>
              Refresh
            </Button>
            <Button
              type="primary"
              disabled={!companyId}
              onClick={() => {
                form.resetFields()
                form.setFieldsValue({ orgId: null, warehouseId: warehouseFilterId })
                setOpen(true)
              }}
            >
              New Locator
            </Button>
          </Space>
        </Space>
      </Card>

      <Card>
        <Space wrap>
          <div style={{ minWidth: 320 }}>
            <Typography.Text strong>Company</Typography.Text>
            <Select
              style={{ width: '100%' }}
              loading={companyLoading}
              value={companyId ?? undefined}
              placeholder="Select company"
              options={companyOptions}
              onChange={(v) => setCompanyId(v)}
            />
          </div>

          <div style={{ minWidth: 320 }}>
            <Typography.Text strong>Warehouse Filter</Typography.Text>
            <Select
              style={{ width: '100%' }}
              allowClear
              loading={lookupLoading}
              value={warehouseFilterId}
              placeholder="All warehouses"
              options={warehouseOptions}
              onChange={(v) => setWarehouseFilterId(v)}
            />
          </div>
        </Space>
      </Card>

      <Card>
        <Table rowKey="id" loading={loading} columns={columns} dataSource={rows} pagination={{ pageSize: 10 }} />
      </Card>

      <Modal
        open={open}
        title="Create Locator"
        onCancel={() => setOpen(false)}
        onOk={async () => {
          if (!companyId) return
          try {
            const values = await form.validateFields()
            const payload: any = {
              warehouseId: values.warehouseId,
              orgId: values.orgId ?? null,
              code: values.code,
              name: values.name
            }
            if (!payload.orgId) delete payload.orgId

            await inventoryApi.createLocator(companyId, payload)
            message.success('Created')
            setOpen(false)
            await load(companyId, warehouseFilterId)
          } catch (e: any) {
            if (e?.errorFields) return
            message.error(getApiErrorMessage(e, 'Failed to create locator'))
          }
        }}
        okText="Create"
      >
        <Form form={form} layout="vertical" initialValues={{ orgId: null }}>
          <Form.Item name="warehouseId" label="Warehouse" rules={[{ required: true }]}>
            <Select showSearch optionFilterProp="label" loading={lookupLoading} options={warehouseOptions} />
          </Form.Item>

          <Form.Item name="orgId" label="Org (optional)">
            <Select allowClear showSearch optionFilterProp="label" loading={lookupLoading} options={orgOptions} />
          </Form.Item>

          <Form.Item name="code" label="Code" rules={[{ required: true }]}>
            <Input />
          </Form.Item>

          <Form.Item name="name" label="Name" rules={[{ required: true }]}>
            <Input />
          </Form.Item>
        </Form>
      </Modal>
    </Space>
  )
}
