// frontend/src/views/modules/hr/DepartmentsView.vue
<template>
  <div style="display: flex; flex-direction: column; gap: 12px">
    <el-card>
      <div style="display: flex; align-items: center; justify-content: space-between; gap: 12px">
        <div>
          <div style="font-size: 18px; font-weight: 600">Departments</div>
          <div style="color: #606266; margin-top: 6px">Setup department untuk struktur organisasi & filter employee.</div>
        </div>
        <div style="display: flex; gap: 8px; align-items: center">
          <el-button @click="load">Refresh</el-button>
          <el-button type="primary" @click="openCreate">Create Department</el-button>
        </div>
      </div>
    </el-card>

    <el-card>
      <el-table :data="rows" style="width: 100%" size="small" v-loading="loading">
        <el-table-column prop="id" label="ID" width="90" />
        <el-table-column prop="name" label="Name" min-width="240" />
        <el-table-column label="Action" width="220">
          <template #default="scope">
            <div style="display: flex; gap: 8px">
              <el-button size="small" @click="openEdit(scope.row)">Edit</el-button>
              <el-button size="small" type="danger" plain @click="onDelete(scope.row)">Delete</el-button>
            </div>
          </template>
        </el-table-column>
      </el-table>
    </el-card>

    <el-dialog v-model="editOpen" :title="editMode === 'create' ? 'Create Department' : 'Edit Department'" width="520px">
      <el-form label-width="120px">
        <el-form-item label="Name" required>
          <el-input v-model="form.name" placeholder="e.g. Production" />
        </el-form-item>
      </el-form>
      <template #footer>
        <div style="display: flex; justify-content: flex-end; gap: 8px">
          <el-button @click="editOpen = false">Cancel</el-button>
          <el-button type="primary" :disabled="!canSave" :loading="saving" @click="onSave">Save</el-button>
        </div>
      </template>
    </el-dialog>
  </div>
</template>

<script setup>
import { computed, onMounted, ref } from 'vue'
import { ElMessage, ElMessageBox } from 'element-plus'
import { hrApi } from '@/utils/api'

const loading = ref(false)
const saving = ref(false)
const rows = ref([])

const editOpen = ref(false)
const editMode = ref('create')
const editingId = ref(null)

const form = ref({
  name: ''
})

const canSave = computed(() => {
  if (!String(form.value.name || '').trim()) return false
  return true
})

async function load() {
  loading.value = true
  try {
    rows.value = await hrApi.listDepartments()
  } catch (e) {
    ElMessage.error(e?.response?.data?.message || e?.message || 'Failed to load departments')
  } finally {
    loading.value = false
  }
}

function openCreate() {
  editMode.value = 'create'
  editingId.value = null
  form.value.name = ''
  editOpen.value = true
}

function openEdit(row) {
  editMode.value = 'edit'
  editingId.value = row.id
  form.value.name = row.name
  editOpen.value = true
}

async function onSave() {
  saving.value = true
  try {
    if (editMode.value === 'create') {
      await hrApi.createDepartment({ name: form.value.name })
      ElMessage.success('Department created')
    } else {
      await hrApi.updateDepartment(editingId.value, { id: editingId.value, name: form.value.name })
      ElMessage.success('Department updated')
    }
    editOpen.value = false
    await load()
  } catch (e) {
    ElMessage.error(e?.response?.data?.message || e?.message || 'Failed to save department')
  } finally {
    saving.value = false
  }
}

async function onDelete(row) {
  try {
    await ElMessageBox.confirm(`Delete department "${row.name}"?`, 'Confirm', {
      type: 'warning',
      confirmButtonText: 'Delete',
      cancelButtonText: 'Cancel'
    })
    await hrApi.deleteDepartment(row.id)
    ElMessage.success('Department deleted')
    await load()
  } catch (e) {
    if (e === 'cancel' || e === 'close') return
    ElMessage.error(e?.response?.data?.message || e?.message || 'Failed to delete department')
  }
}

onMounted(load)
</script>

// frontend2_new/src/views/modules/hr/DepartmentsView.tsx
import { Button, Card, Form, Input, Modal, Popconfirm, Space, Table, Typography, message } from 'antd'
import type { ColumnsType } from 'antd/es/table'
import { useEffect, useMemo, useState } from 'react'
import { hrApi } from '@/utils/api'
import { getApiErrorMessage } from '@/utils/error'

type DepartmentRow = {
  id: number
  name?: string
}

export default function DepartmentsView() {
  const [loading, setLoading] = useState(false)
  const [rows, setRows] = useState<DepartmentRow[]>([])

  const [q, setQ] = useState('')

  const [createOpen, setCreateOpen] = useState(false)
  const [saving, setSaving] = useState(false)
  const [createForm] = Form.useForm()

  const [editOpen, setEditOpen] = useState(false)
  const [editSaving, setEditSaving] = useState(false)
  const [editingId, setEditingId] = useState<number | null>(null)
  const [editForm] = Form.useForm()

  async function load() {
    setLoading(true)
    try {
      setRows((await hrApi.listDepartments()) || [])
    } catch (e: any) {
      message.error(getApiErrorMessage(e, 'Failed to load departments'))
      setRows([])
    } finally {
      setLoading(false)
    }
  }

  useEffect(() => {
    void load()
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [])

  const filtered = useMemo(() => {
    const qq = q.trim().toLowerCase()
    return (rows || []).filter((r) => {
      if (!qq) return true
      return String(r.name || '').toLowerCase().includes(qq)
    })
  }, [q, rows])

  const columns: ColumnsType<DepartmentRow> = [
    { title: 'ID', dataIndex: 'id', width: 90 },
    { title: 'Name', dataIndex: 'name' },
    {
      title: 'Actions',
      key: 'actions',
      width: 200,
      render: (_, r) => (
        <Space>
          <Button
            size="small"
            onClick={() => {
              setEditingId(r.id)
              editForm.setFieldsValue({ name: r.name || '' })
              setEditOpen(true)
            }}
          >
            Edit
          </Button>
          <Popconfirm
            title="Delete department?"
            okText="Delete"
            okButtonProps={{ danger: true }}
            onConfirm={async () => {
              try {
                await hrApi.deleteDepartment(r.id)
                message.success('Deleted')
                await load()
              } catch (e: any) {
                message.error(getApiErrorMessage(e, 'Failed to delete department'))
              }
            }}
          >
            <Button size="small" danger>
              Delete
            </Button>
          </Popconfirm>
        </Space>
      )
    }
  ]

  return (
    <Space direction="vertical" size={16} style={{ width: '100%' }}>
      <Card>
        <Space style={{ width: '100%', justifyContent: 'space-between' }}>
          <div>
            <Typography.Title level={4} style={{ margin: 0 }}>
              Departments
            </Typography.Title>
            <Typography.Text type="secondary">Master data department untuk employee.</Typography.Text>
          </div>
          <Space>
            <Button onClick={() => void load()} loading={loading}>
              Refresh
            </Button>
            <Button
              type="primary"
              onClick={() => {
                createForm.resetFields()
                setCreateOpen(true)
              }}
            >
              New Department
            </Button>
          </Space>
        </Space>
      </Card>

      <Card>
        <Space style={{ marginBottom: 12 }} wrap>
          <Input placeholder="Search name" value={q} onChange={(e) => setQ(e.target.value)} style={{ width: 260 }} />
        </Space>
        <Table<DepartmentRow> rowKey="id" loading={loading} columns={columns} dataSource={filtered} pagination={{ pageSize: 10 }} />
      </Card>

      <Modal
        open={createOpen}
        title="Create Department"
        okText="Create"
        confirmLoading={saving}
        onCancel={() => setCreateOpen(false)}
        onOk={async () => {
          try {
            const v = await createForm.validateFields()
            setSaving(true)
            await hrApi.createDepartment({ name: v.name })
            message.success('Created')
            setCreateOpen(false)
            await load()
          } catch (e: any) {
            if (e?.errorFields) {
              message.error('Please complete required fields')
              return
            }
            message.error(getApiErrorMessage(e, 'Failed to create department'))
          } finally {
            setSaving(false)
          }
        }}
      >
        <Form form={createForm} layout="vertical">
          <Form.Item name="name" label="Name" rules={[{ required: true }]}>
            <Input />
          </Form.Item>
        </Form>
      </Modal>

      <Modal
        open={editOpen}
        title="Edit Department"
        okText="Save"
        confirmLoading={editSaving}
        onCancel={() => {
          setEditOpen(false)
          setEditingId(null)
        }}
        onOk={async () => {
          if (editingId == null) {
            message.error('Department id is missing')
            return
          }
          try {
            const v = await editForm.validateFields()
            setEditSaving(true)
            await hrApi.updateDepartment(editingId, { name: v.name })
            message.success('Saved')
            setEditOpen(false)
            setEditingId(null)
            await load()
          } catch (e: any) {
            if (e?.errorFields) {
              message.error('Please complete required fields')
              return
            }
            message.error(getApiErrorMessage(e, 'Failed to update department'))
          } finally {
            setEditSaving(false)
          }
        }}
      >
        <Form form={editForm} layout="vertical">
          <Form.Item name="name" label="Name" rules={[{ required: true }]}>
            <Input />
          </Form.Item>
        </Form>
      </Modal>
    </Space>
  )
}
