// frontend/src/views/modules/hr/EmployeesView.vue
<template>
  <div style="display: flex; flex-direction: column; gap: 12px">
    <el-card>
      <div style="display: flex; align-items: flex-start; justify-content: space-between; gap: 12px">
        <div>
          <div style="font-size: 18px; font-weight: 600">Employees</div>
          <div style="color: #606266; margin-top: 6px">Manage employee master data (role, department, salary, active).</div>
        </div>
        <div style="display: flex; gap: 8px; align-items: center">
          <el-button @click="load">Refresh</el-button>
          <el-button type="primary" :disabled="!hasDepartments" @click="openCreate">Create Employee</el-button>
        </div>
      </div>
    </el-card>

    <el-card>
      <div style="display: flex; gap: 10px; align-items: center; flex-wrap: wrap; margin-bottom: 10px">
        <el-input v-model="q" placeholder="Search name/email..." clearable style="max-width: 260px" />
        <el-select v-model="deptFilter" clearable filterable placeholder="Filter department" style="min-width: 220px">
          <el-option v-for="d in departments" :key="d.id" :label="d.name" :value="d.id" />
        </el-select>
        <el-select v-model="activeFilter" clearable placeholder="Filter status" style="min-width: 180px">
          <el-option label="Active" :value="true" />
          <el-option label="Inactive" :value="false" />
        </el-select>
      </div>

      <el-table :data="filtered" style="width: 100%" size="small" v-loading="loading">
        <el-table-column prop="id" label="ID" width="80" />
        <el-table-column prop="name" label="Name" min-width="180" />
        <el-table-column prop="email" label="Email" min-width="200" />
        <el-table-column prop="phone" label="Phone" width="140" />
        <el-table-column prop="departmentName" label="Department" width="160" />
        <el-table-column prop="role" label="Role" width="120">
          <template #default="scope">
            <el-tag size="small" type="info">{{ scope.row.role }}</el-tag>
          </template>
        </el-table-column>
        <el-table-column prop="active" label="Status" width="110">
          <template #default="scope">
            <el-tag size="small" :type="scope.row.active ? 'success' : 'danger'">{{ scope.row.active ? 'Active' : 'Inactive' }}</el-tag>
          </template>
        </el-table-column>
        <el-table-column label="Action" width="320">
          <template #default="scope">
            <div style="display: flex; gap: 8px; flex-wrap: wrap">
              <el-button size="small" @click="openEdit(scope.row)">Edit</el-button>
              <el-button size="small" :type="scope.row.active ? 'warning' : 'success'" plain @click="onToggle(scope.row)">
                {{ scope.row.active ? 'Deactivate' : 'Activate' }}
              </el-button>
              <el-button size="small" type="danger" plain @click="onDelete(scope.row)">Delete</el-button>
            </div>
          </template>
        </el-table-column>
      </el-table>
    </el-card>

    <el-dialog v-model="editOpen" :title="editMode === 'create' ? 'Create Employee' : 'Edit Employee'" width="760px">
      <el-alert
        v-if="editMode === 'create' && !hasDepartments"
        title="Department belum ada. Buat Department dulu sebelum membuat Employee."
        type="warning"
        show-icon
        style="margin-bottom: 12px"
      />
      <el-alert v-if="saveIssues.length" type="warning" show-icon style="margin-bottom: 12px">
        <template #title>
          <div style="display: flex; flex-direction: column; gap: 6px">
            <div>Lengkapi data berikut agar bisa Save:</div>
            <div>
              <div v-for="(s, idx) in saveIssues" :key="idx">- {{ s }}</div>
            </div>
          </div>
        </template>
      </el-alert>
      <el-form label-width="140px">
        <el-form-item label="Name" required>
          <el-input v-model="form.name" placeholder="Employee name" />
        </el-form-item>

        <el-form-item label="Email" required>
          <el-input v-model="form.email" placeholder="name@company.com" />
        </el-form-item>

        <el-form-item label="Phone">
          <el-input v-model="form.phone" placeholder="08xxxxxxxx" />
        </el-form-item>

        <el-form-item label="Department" required>
          <el-select v-model="form.departmentId" filterable placeholder="Select department" style="width: 100%">
            <el-option v-for="d in departments" :key="d.id" :label="d.name" :value="d.id" />
          </el-select>
        </el-form-item>

        <el-form-item label="Role" required>
          <el-select v-model="form.role" placeholder="Select role" style="width: 100%">
            <el-option v-for="r in roles" :key="r" :label="r" :value="r" />
          </el-select>
        </el-form-item>

        <el-form-item label="Active">
          <el-switch v-model="form.active" />
        </el-form-item>

        <el-divider />

        <el-form-item label="Base Salary">
          <el-input v-model="form.baseSalary" placeholder="e.g. 5000000" />
        </el-form-item>

        <el-form-item label="Bonus">
          <el-input v-model="form.bonus" placeholder="e.g. 0" />
        </el-form-item>

        <el-form-item label="Deduction">
          <el-input v-model="form.deduction" placeholder="e.g. 0" />
        </el-form-item>

        <el-form-item label="Performance Rating">
          <el-input v-model="form.performanceRating" placeholder="e.g. 4.5" />
        </el-form-item>

        <el-divider />

        <el-form-item :label="editMode === 'create' ? 'Password' : 'New Password'" :required="editMode === 'create'">
          <el-input v-model="form.password" type="password" show-password placeholder="Leave blank to keep unchanged" />
        </el-form-item>
      </el-form>

      <template #footer>
        <div style="display: flex; justify-content: flex-end; gap: 8px">
          <el-button @click="editOpen = false">Cancel</el-button>
          <el-button type="primary" :disabled="!canSave" :loading="saving" @click="onSave">Save</el-button>
        </div>
      </template>
    </el-dialog>
  </div>
</template>

<script setup>
import { computed, onMounted, ref } from 'vue'
import { ElMessage, ElMessageBox } from 'element-plus'
import { hrApi } from '@/utils/api'

const roles = ['ADMIN', 'HR', 'FINANCE', 'INVENTORY', 'EMPLOYEE']

const loading = ref(false)
const saving = ref(false)
const rows = ref([])
const departments = ref([])

const q = ref('')
const deptFilter = ref(null)
const activeFilter = ref(null)

const hasDepartments = computed(() => (departments.value || []).length > 0)

const editOpen = ref(false)
const editMode = ref('create')
const editingId = ref(null)

const form = ref({
  name: '',
  email: '',
  phone: '',
  role: 'EMPLOYEE',
  departmentId: null,
  baseSalary: '',
  bonus: '',
  deduction: '',
  performanceRating: '',
  active: true,
  password: ''
})

function isValidEmail(v) {
  const s = String(v ?? '').trim()
  if (!s) return false
  return /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(s)
}

const canSave = computed(() => {
  if (!String(form.value.name || '').trim()) return false
  if (!isValidEmail(form.value.email)) return false
  if (!String(form.value.role || '').trim()) return false
  if (!form.value.departmentId) return false
  if (editMode.value === 'create' && !String(form.value.password || '').trim()) return false
  return true
})

const saveIssues = computed(() => {
  const issues = []
  if (!String(form.value.name || '').trim()) issues.push('Name wajib diisi')
  if (!isValidEmail(form.value.email)) issues.push('Email tidak valid (contoh: nama@company.com)')
  if (!form.value.departmentId) issues.push('Department wajib dipilih')
  if (!String(form.value.role || '').trim()) issues.push('Role wajib dipilih')
  if (editMode.value === 'create' && !String(form.value.password || '').trim()) issues.push('Password wajib diisi untuk Create')
  return issues
})

const filtered = computed(() => {
  const qq = q.value.trim().toLowerCase()
  return rows.value.filter((r) => {
    if (qq) {
      const hay = `${r.name || ''} ${r.email || ''}`.toLowerCase()
      if (!hay.includes(qq)) return false
    }
    if (deptFilter.value && r.departmentId !== deptFilter.value) return false
    if (activeFilter.value !== null && activeFilter.value !== undefined) {
      if (Boolean(r.active) !== Boolean(activeFilter.value)) return false
    }
    return true
  })
})

function normalizeNumber(v) {
  const s = String(v ?? '').trim()
  if (!s) return null
  const n = Number(s)
  if (Number.isNaN(n)) return null
  return n
}

async function load() {
  loading.value = true
  try {
    const [depts, emps] = await Promise.all([hrApi.listDepartments(), hrApi.listEmployees()])
    departments.value = depts
    rows.value = emps

    if (!deptFilter.value && (departments.value || []).length === 1) {
      deptFilter.value = departments.value[0].id
    }

    if (editOpen.value && editMode.value === 'create' && !form.value.departmentId && hasDepartments.value) {
      form.value.departmentId = departments.value[0].id
    }
  } catch (e) {
    ElMessage.error(e?.response?.data?.message || e?.message || 'Failed to load employees')
  } finally {
    loading.value = false
  }
}

function openCreate() {
  if (!hasDepartments.value) {
    ElMessage.warning('Department belum ada. Buat Department dulu.')
    return
  }
  editMode.value = 'create'
  editingId.value = null
  form.value = {
    name: '',
    email: '',
    phone: '',
    role: 'EMPLOYEE',
    departmentId: departments.value[0]?.id || null,
    baseSalary: '',
    bonus: '',
    deduction: '',
    performanceRating: '',
    active: true,
    password: ''
  }
  editOpen.value = true
}

function openEdit(row) {
  editMode.value = 'edit'
  editingId.value = row.id
  form.value = {
    name: row.name || '',
    email: row.email || '',
    phone: row.phone || '',
    role: row.role || 'EMPLOYEE',
    departmentId: row.departmentId || null,
    baseSalary: row.baseSalary ?? '',
    bonus: row.bonus ?? '',
    deduction: row.deduction ?? '',
    performanceRating: row.performanceRating ?? '',
    active: Boolean(row.active),
    password: ''
  }
  editOpen.value = true
}

async function onSave() {
  saving.value = true
  try {
    const payload = {
      name: String(form.value.name || '').trim(),
      email: String(form.value.email || '').trim().toLowerCase(),
      phone: String(form.value.phone || '').trim() || null,
      role: form.value.role,
      departmentId: form.value.departmentId,
      baseSalary: normalizeNumber(form.value.baseSalary),
      bonus: normalizeNumber(form.value.bonus) ?? 0,
      deduction: normalizeNumber(form.value.deduction) ?? 0,
      performanceRating: String(form.value.performanceRating || '').trim() || null,
      active: Boolean(form.value.active),
      password: String(form.value.password || '').trim() || null
    }

    if (!isValidEmail(payload.email)) {
      ElMessage.error('Email tidak valid. Contoh: nama@company.com')
      return
    }

    if (editMode.value === 'create') {
      await hrApi.createEmployee(payload)
      ElMessage.success('Employee created')
    } else {
      if (!payload.password) delete payload.password
      await hrApi.updateEmployee(editingId.value, payload)
      ElMessage.success('Employee updated')
    }

    editOpen.value = false
    await load()
  } catch (e) {
    ElMessage.error(e?.response?.data?.message || e?.message || 'Failed to save employee')
  } finally {
    saving.value = false
  }
}

async function onToggle(row) {
  try {
    await hrApi.toggleEmployeeStatus(row.id)
    ElMessage.success('Status updated')
    await load()
  } catch (e) {
    ElMessage.error(e?.response?.data?.message || e?.message || 'Failed to toggle status')
  }
}

async function onDelete(row) {
  try {
    await ElMessageBox.confirm(`Delete employee "${row.name}"?`, 'Confirm', {
      type: 'warning',
      confirmButtonText: 'Delete',
      cancelButtonText: 'Cancel'
    })
    await hrApi.deleteEmployee(row.id)
    ElMessage.success('Employee deleted')
    await load()
  } catch (e) {
    if (e === 'cancel' || e === 'close') return
    ElMessage.error(e?.response?.data?.message || e?.message || 'Failed to delete employee')
  }
}

onMounted(load)
</script>

// frontend2_new/src/views/modules/hr/EmployeesView.tsx
import { Button, Card, Input, InputNumber, Modal, Popconfirm, Select, Space, Switch, Table, Tag, Typography, message } from 'antd'
import type { ColumnsType } from 'antd/es/table'
import { useEffect, useMemo, useState } from 'react'
import { hrApi } from '@/utils/api'
import { getApiErrorMessage } from '@/utils/error'

type DepartmentRow = { id: number; name?: string }

type EmployeeRow = {
  id: number
  name?: string
  email?: string
  phone?: string
  role?: string
  departmentId?: number
  departmentName?: string
  baseSalary?: number
  bonus?: number
  deduction?: number
  performanceRating?: string
  active?: boolean
}

type EmployeeFormState = {
  name: string
  email: string
  phone: string
  role: string
  departmentId: number | null
  baseSalary: number
  bonus: number
  deduction: number
  performanceRating: string
  active: boolean
  password: string
}

function emptyEmployeeForm(): EmployeeFormState {
  return {
    name: '',
    email: '',
    phone: '',
    role: 'HR',
    departmentId: null,
    baseSalary: 0,
    bonus: 0,
    deduction: 0,
    performanceRating: '',
    active: true,
    password: ''
  }
}

export default function EmployeesView() {
  const [loading, setLoading] = useState(false)
  const [rows, setRows] = useState<EmployeeRow[]>([])

  const [deptOptions, setDeptOptions] = useState<DepartmentRow[]>([])

  const [q, setQ] = useState('')
  const [deptFilter, setDeptFilter] = useState<number | undefined>(undefined)

  const [open, setOpen] = useState(false)
  const [saving, setSaving] = useState(false)
  const [editMode, setEditMode] = useState<'create' | 'edit'>('create')
  const [editingId, setEditingId] = useState<number | null>(null)
  const [form, setForm] = useState<EmployeeFormState>(() => emptyEmployeeForm())

  async function loadDepartments() {
    try {
      setDeptOptions((await hrApi.listDepartments()) || [])
    } catch {
      setDeptOptions([])
    }
  }

  async function loadEmployees() {
    setLoading(true)
    try {
      setRows((await hrApi.listEmployees()) || [])
    } catch (e: any) {
      message.error(getApiErrorMessage(e, 'Failed to load employees'))
      setRows([])
    } finally {
      setLoading(false)
    }
  }

  async function load() {
    await Promise.all([loadDepartments(), loadEmployees()])
  }

  useEffect(() => {
    void load()
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [])

  const deptSelectOptions = useMemo(
    () =>
      (deptOptions || []).map((d) => ({
        value: d.id,
        label: d.name ? `${d.name}` : String(d.id)
      })),
    [deptOptions]
  )

  const filtered = useMemo(() => {
    const qq = q.trim().toLowerCase()
    return (rows || []).filter((r) => {
      if (deptFilter && Number(r.departmentId) !== Number(deptFilter)) return false
      if (!qq) return true
      return (
        String(r.name || '').toLowerCase().includes(qq) ||
        String(r.email || '').toLowerCase().includes(qq) ||
        String(r.phone || '').toLowerCase().includes(qq) ||
        String(r.departmentName || '').toLowerCase().includes(qq)
      )
    })
  }, [deptFilter, q, rows])

  const columns: ColumnsType<EmployeeRow> = [
    { title: 'Name', dataIndex: 'name', width: 200 },
    { title: 'Email', dataIndex: 'email', width: 220 },
    { title: 'Phone', dataIndex: 'phone', width: 160 },
    { title: 'Role', dataIndex: 'role', width: 120 },
    { title: 'Department', dataIndex: 'departmentName', width: 200 },
    {
      title: 'Active',
      dataIndex: 'active',
      width: 110,
      render: (v: any) => (v ? <Tag color="green">Yes</Tag> : <Tag color="red">No</Tag>)
    },
    {
      title: 'Actions',
      key: 'actions',
      width: 280,
      render: (_, r) => (
        <Space>
          <Button
            size="small"
            onClick={() => {
              setEditMode('edit')
              setEditingId(r.id)
              setForm({
                name: r.name || '',
                email: r.email || '',
                phone: r.phone || '',
                role: r.role || 'HR',
                departmentId: r.departmentId ?? null,
                baseSalary: Number(r.baseSalary ?? 0),
                bonus: Number(r.bonus ?? 0),
                deduction: Number(r.deduction ?? 0),
                performanceRating: r.performanceRating || '',
                active: Boolean(r.active),
                password: ''
              })
              setOpen(true)
            }}
          >
            Edit
          </Button>
          <Button
            size="small"
            onClick={async () => {
              try {
                await hrApi.toggleEmployeeStatus(r.id)
                message.success('Updated status')
                await loadEmployees()
              } catch (e: any) {
                message.error(getApiErrorMessage(e, 'Failed to toggle status'))
              }
            }}
          >
            Toggle Status
          </Button>
          <Popconfirm
            title="Delete employee?"
            okText="Delete"
            okButtonProps={{ danger: true }}
            onConfirm={async () => {
              try {
                await hrApi.deleteEmployee(r.id)
                message.success('Deleted')
                await loadEmployees()
              } catch (e: any) {
                message.error(getApiErrorMessage(e, 'Failed to delete employee'))
              }
            }}
          >
            <Button size="small" danger>
              Delete
            </Button>
          </Popconfirm>
        </Space>
      )
    }
  ]

  return (
    <Space direction="vertical" size={16} style={{ width: '100%' }}>
      <Card>
        <Space style={{ width: '100%', justifyContent: 'space-between' }}>
          <div>
            <Typography.Title level={4} style={{ margin: 0 }}>
              Employees
            </Typography.Title>
            <Typography.Text type="secondary">Create, update, and manage employee status.</Typography.Text>
          </div>
          <Space>
            <Button onClick={() => void load()} loading={loading}>
              Refresh
            </Button>
            <Button
              type="primary"
              onClick={() => {
                setEditMode('create')
                setEditingId(null)
                setForm(emptyEmployeeForm())
                setOpen(true)
              }}
            >
              New Employee
            </Button>
          </Space>
        </Space>
      </Card>

      <Card>
        <Space wrap style={{ marginBottom: 12 }}>
          <Input placeholder="Search name/email/phone" value={q} onChange={(e) => setQ(e.target.value)} style={{ width: 260 }} />
          <Select
            allowClear
            placeholder="Department"
            style={{ width: 240 }}
            value={deptFilter}
            options={deptSelectOptions}
            onChange={(v) => setDeptFilter(v ?? undefined)}
          />
        </Space>
        <Table<EmployeeRow> rowKey="id" loading={loading} columns={columns} dataSource={filtered} pagination={{ pageSize: 10 }} />
      </Card>

      <Modal
        open={open}
        title={editMode === 'create' ? 'Create Employee' : 'Edit Employee'}
        okText={editMode === 'create' ? 'Create' : 'Save'}
        confirmLoading={saving}
        onCancel={() => {
          setOpen(false)
          setSaving(false)
        }}
        onOk={async () => {
          try {
            if (!form.name.trim()) {
              message.error('Name is required')
              return
            }
            if (!form.role.trim()) {
              message.error('Role is required')
              return
            }
            if (!form.departmentId) {
              message.error('Department is required')
              return
            }
            setSaving(true)
            const payload: any = {
              name: form.name,
              email: form.email,
              phone: form.phone,
              role: form.role,
              departmentId: form.departmentId,
              baseSalary: Number(form.baseSalary || 0),
              bonus: Number(form.bonus || 0),
              deduction: Number(form.deduction || 0),
              performanceRating: form.performanceRating || null,
              active: Boolean(form.active)
            }
            if (form.password && form.password.trim()) payload.password = form.password

            if (editMode === 'create') {
              await hrApi.createEmployee(payload)
              message.success('Created')
            } else {
              if (editingId == null) {
                message.error('Employee id is missing')
                return
              }
              await hrApi.updateEmployee(editingId, payload)
              message.success('Saved')
            }

            setOpen(false)
            await loadEmployees()
          } catch (e: any) {
            message.error(getApiErrorMessage(e, 'Failed'))
          } finally {
            setSaving(false)
          }
        }}
      >
        <Space direction="vertical" style={{ width: '100%' }} size={12}>
          <Input value={form.name} onChange={(e) => setForm((s) => ({ ...s, name: e.target.value }))} placeholder="Name" />
          <Input value={form.email} onChange={(e) => setForm((s) => ({ ...s, email: e.target.value }))} placeholder="Email" />
          <Input value={form.phone} onChange={(e) => setForm((s) => ({ ...s, phone: e.target.value }))} placeholder="Phone" />
          <Select
            placeholder="Role"
            value={form.role}
            onChange={(v) => setForm((s) => ({ ...s, role: v }))}
            options={[
              { value: 'ADMIN', label: 'ADMIN' },
              { value: 'HR', label: 'HR' },
              { value: 'INVENTORY', label: 'INVENTORY' },
              { value: 'FINANCE', label: 'FINANCE' }
            ]}
          />
          <Select
            placeholder="Department"
            value={form.departmentId ?? undefined}
            onChange={(v) => setForm((s) => ({ ...s, departmentId: v ?? null }))}
            options={deptSelectOptions}
          />

          <Space style={{ width: '100%', justifyContent: 'space-between' }}>
            <Typography.Text type="secondary">Active</Typography.Text>
            <Switch checked={form.active} onChange={(v) => setForm((s) => ({ ...s, active: v }))} />
          </Space>

          <InputNumber
            style={{ width: '100%' }}
            value={form.baseSalary}
            onChange={(v) => setForm((s) => ({ ...s, baseSalary: Number(v ?? 0) }))}
            placeholder="Base Salary"
          />
          <InputNumber
            style={{ width: '100%' }}
            value={form.bonus}
            onChange={(v) => setForm((s) => ({ ...s, bonus: Number(v ?? 0) }))}
            placeholder="Bonus"
          />
          <InputNumber
            style={{ width: '100%' }}
            value={form.deduction}
            onChange={(v) => setForm((s) => ({ ...s, deduction: Number(v ?? 0) }))}
            placeholder="Deduction"
          />
          <Input value={form.performanceRating} onChange={(e) => setForm((s) => ({ ...s, performanceRating: e.target.value }))} placeholder="Performance Rating" />
          <Input.Password
            value={form.password}
            onChange={(e) => setForm((s) => ({ ...s, password: e.target.value }))}
            placeholder={editMode === 'create' ? 'Password (optional)' : 'Password (set to change)'}
          />
        </Space>
      </Modal>
    </Space>
  )
}
