// frontend2_new/src/views/modules/inventory/MovementsView.tsx
import { Button, Card, DatePicker, Form, Input, InputNumber, Modal, Select, Space, Table, Tag, Typography, message } from 'antd'
import type { ColumnsType } from 'antd/es/table'
import dayjs from 'dayjs'
import { useEffect, useMemo, useState } from 'react'
import { coreApi, inventoryApi, masterDataApi } from '@/utils/api'
import { useContextStore } from '@/stores/context'
import { getApiErrorMessage } from '@/utils/error'

type CompanyRow = { id: number; code?: string; name?: string }

type OrgRow = { id: number; code?: string; name?: string }

type LocatorRow = { id: number; code?: string; name?: string }

type ProductRow = { id: number; code?: string; name?: string }

type MovementRow = {
  id: number
  documentNo?: string
  status?: string
  movementType?: 'IN' | 'OUT' | 'TRANSFER'
  movementDate?: string
  description?: string
  lines?: any[]
}

function toLocalDateString(d: any): string {
  if (!d) return ''
  return dayjs(d).format('YYYY-MM-DD')
}

export default function MovementsView() {
  const companyId = useContextStore((s) => s.companyId)
  const setCompanyId = useContextStore((s) => s.setCompanyId)

  const [companyLoading, setCompanyLoading] = useState(false)
  const [companies, setCompanies] = useState<CompanyRow[]>([])

  const [lookupLoading, setLookupLoading] = useState(false)
  const [orgs, setOrgs] = useState<OrgRow[]>([])
  const [locators, setLocators] = useState<LocatorRow[]>([])
  const [products, setProducts] = useState<ProductRow[]>([])

  const [loading, setLoading] = useState(false)
  const [rows, setRows] = useState<MovementRow[]>([])

  const [open, setOpen] = useState(false)
  const [form] = Form.useForm()

  const loadCompanies = async () => {
    setCompanyLoading(true)
    try {
      const res = await coreApi.listCompanies()
      setCompanies(res || [])
      if (!companyId && Array.isArray(res) && res.length > 0) setCompanyId(res[0]?.id)
    } catch (e: any) {
      message.error(getApiErrorMessage(e, 'Failed to load companies'))
    } finally {
      setCompanyLoading(false)
    }
  }

  const loadLookups = async (cid: number) => {
    setLookupLoading(true)
    try {
      const [orgRes, locRes, prodRes] = await Promise.all([
        coreApi.listOrgs(cid),
        inventoryApi.listLocators(cid),
        masterDataApi.listProducts(cid)
      ])
      setOrgs(orgRes || [])
      setLocators(locRes || [])
      setProducts(prodRes || [])
    } catch (e: any) {
      message.error(getApiErrorMessage(e, 'Failed to load lookups'))
      setOrgs([])
      setLocators([])
      setProducts([])
    } finally {
      setLookupLoading(false)
    }
  }

  const load = async (cid: number) => {
    setLoading(true)
    try {
      const res = await inventoryApi.listMovements(cid)
      setRows(res || [])
    } catch (e: any) {
      message.error(getApiErrorMessage(e, 'Failed to load movements'))
      setRows([])
    } finally {
      setLoading(false)
    }
  }

  useEffect(() => {
    void loadCompanies()
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [])

  useEffect(() => {
    if (!companyId) return
    void loadLookups(companyId)
    void load(companyId)
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [companyId])

  const companyOptions = useMemo(
    () => companies.map((c) => ({ value: c.id, label: `${c.code || c.id} - ${c.name || ''}` })),
    [companies]
  )

  const orgOptions = useMemo(
    () => orgs.map((o) => ({ value: o.id, label: `${o.code || o.id} - ${o.name || ''}` })),
    [orgs]
  )

  const locatorOptions = useMemo(
    () => locators.map((l) => ({ value: l.id, label: `${l.code || l.id} - ${l.name || ''}` })),
    [locators]
  )

  const productOptions = useMemo(
    () => products.map((p) => ({ value: p.id, label: `${p.code || p.id} - ${p.name || ''}` })),
    [products]
  )

  const columns: ColumnsType<MovementRow> = [
    { title: 'Doc No', dataIndex: 'documentNo', width: 180 },
    {
      title: 'Status',
      dataIndex: 'status',
      width: 140,
      render: (v: any) => {
        const s = String(v || '')
        if (s === 'DRAFTED') return <Tag>Drafted</Tag>
        if (s === 'COMPLETED') return <Tag color="green">Completed</Tag>
        if (s === 'VOIDED') return <Tag color="red">Voided</Tag>
        return <Tag>{s}</Tag>
      }
    },
    { title: 'Type', dataIndex: 'movementType', width: 120 },
    { title: 'Date', dataIndex: 'movementDate', width: 130 },
    { title: 'Description', dataIndex: 'description' }
  ]

  const lineColumns: ColumnsType<any> = [
    {
      title: 'Product',
      dataIndex: 'product',
      render: (p: any) => (p?.code ? `${p.code} - ${p.name || ''}` : p?.id || '-')
    },
    { title: 'Qty', dataIndex: 'qty', width: 120 },
    {
      title: 'From',
      dataIndex: 'fromLocator',
      render: (l: any) => (l?.code ? `${l.code} - ${l.name || ''}` : l?.id || '-')
    },
    {
      title: 'To',
      dataIndex: 'toLocator',
      render: (l: any) => (l?.code ? `${l.code} - ${l.name || ''}` : l?.id || '-')
    }
  ]

  return (
    <Space direction="vertical" size={16} style={{ width: '100%' }}>
      <Card>
        <Space style={{ width: '100%', justifyContent: 'space-between' }}>
          <Typography.Title level={4} style={{ margin: 0 }}>
            Inventory Movements
          </Typography.Title>
          <Space>
            <Button onClick={() => companyId && loadLookups(companyId)} disabled={!companyId} loading={lookupLoading}>
              Refresh Lookups
            </Button>
            <Button onClick={() => companyId && load(companyId)} disabled={!companyId} loading={loading}>
              Refresh
            </Button>
            <Button
              type="primary"
              disabled={!companyId}
              onClick={() => {
                form.resetFields()
                form.setFieldsValue({
                  movementType: 'IN',
                  movementDate: dayjs(),
                  orgId: null,
                  lines: [{ productId: products[0]?.id ?? null, qty: 1, fromLocatorId: null, toLocatorId: null }]
                })
                setOpen(true)
              }}
            >
              New Movement
            </Button>
          </Space>
        </Space>
      </Card>

      <Card>
        <Space wrap style={{ width: '100%' }}>
          <div style={{ minWidth: 320 }}>
            <Typography.Text strong>Company</Typography.Text>
            <Select
              style={{ width: '100%' }}
              loading={companyLoading}
              value={companyId ?? undefined}
              placeholder="Select company"
              options={companyOptions}
              onChange={(v) => setCompanyId(v)}
            />
          </div>
        </Space>
      </Card>

      <Card>
        <Table<MovementRow>
          rowKey="id"
          loading={loading}
          columns={columns}
          dataSource={rows}
          pagination={{ pageSize: 10 }}
          expandable={{
            expandedRowRender: (r) => (
              <Table
                size="small"
                rowKey={(x: any, idx) => String(x?.id || idx)}
                pagination={false}
                columns={lineColumns}
                dataSource={r.lines || []}
              />
            )
          }}
        />
      </Card>

      <Modal
        open={open}
        title="Create Inventory Movement"
        width={980}
        onCancel={() => setOpen(false)}
        onOk={async () => {
          if (!companyId) return
          try {
            const values = await form.validateFields()
            const movementType = values.movementType

            const payload: any = {
              movementType,
              movementDate: toLocalDateString(values.movementDate),
              description: values.description || null,
              orgId: values.orgId ?? null,
              lines: (values.lines || []).map((l: any) => ({
                productId: l.productId,
                qty: l.qty,
                fromLocatorId: l.fromLocatorId ?? null,
                toLocatorId: l.toLocatorId ?? null
              }))
            }
            if (!payload.orgId) delete payload.orgId

            await inventoryApi.createMovement(companyId, payload)
            message.success('Created')
            setOpen(false)
            await load(companyId)
          } catch (e: any) {
            if (e?.errorFields) return
            message.error(getApiErrorMessage(e, 'Failed to create movement'))
          }
        }}
        okText="Create"
      >
        <Form layout="vertical" form={form}>
          <Space wrap style={{ width: '100%' }}>
            <Form.Item name="orgId" label="Org (optional)" style={{ width: 260 }}>
              <Select allowClear showSearch optionFilterProp="label" loading={lookupLoading} options={orgOptions} />
            </Form.Item>

            <Form.Item name="movementType" label="Movement Type" rules={[{ required: true }]} style={{ width: 220 }}>
              <Select
                options={[
                  { value: 'IN', label: 'IN' },
                  { value: 'OUT', label: 'OUT' },
                  { value: 'TRANSFER', label: 'TRANSFER' }
                ]}
              />
            </Form.Item>

            <Form.Item name="movementDate" label="Movement Date" rules={[{ required: true }]} style={{ width: 220 }}>
              <DatePicker style={{ width: '100%' }} />
            </Form.Item>

            <Form.Item name="description" label="Description" style={{ width: 420 }}>
              <Input />
            </Form.Item>
          </Space>

          <Typography.Title level={5}>Lines</Typography.Title>
          <Form.List name="lines">
            {(fields, { add, remove }) => (
              <Space direction="vertical" style={{ width: '100%' }} size={8}>
                {fields.map((field) => (
                  <Space key={field.key} align="baseline" wrap style={{ width: '100%' }}>
                    <Form.Item
                      {...field}
                      name={[field.name, 'productId']}
                      label="Product"
                      rules={[{ required: true }]}
                      style={{ width: 360 }}
                    >
                      <Select showSearch optionFilterProp="label" loading={lookupLoading} options={productOptions} />
                    </Form.Item>

                    <Form.Item {...field} name={[field.name, 'qty']} label="Qty" rules={[{ required: true }]} style={{ width: 140 }}>
                      <InputNumber style={{ width: '100%' }} min={0.0001} />
                    </Form.Item>

                    <Form.Item shouldUpdate noStyle>
                      {() => {
                        const mt = form.getFieldValue('movementType')
                        const needFrom = mt === 'OUT' || mt === 'TRANSFER'
                        const needTo = mt === 'IN' || mt === 'TRANSFER'

                        return (
                          <>
                            <Form.Item
                              {...field}
                              name={[field.name, 'fromLocatorId']}
                              label="From Locator"
                              rules={needFrom ? [{ required: true }] : []}
                              style={{ width: 240 }}
                            >
                              <Select
                                allowClear={!needFrom}
                                showSearch
                                optionFilterProp="label"
                                loading={lookupLoading}
                                options={locatorOptions}
                                disabled={!needFrom}
                              />
                            </Form.Item>

                            <Form.Item
                              {...field}
                              name={[field.name, 'toLocatorId']}
                              label="To Locator"
                              rules={needTo ? [{ required: true }] : []}
                              style={{ width: 240 }}
                            >
                              <Select
                                allowClear={!needTo}
                                showSearch
                                optionFilterProp="label"
                                loading={lookupLoading}
                                options={locatorOptions}
                                disabled={!needTo}
                              />
                            </Form.Item>
                          </>
                        )
                      }}
                    </Form.Item>

                    <Button danger onClick={() => remove(field.name)} disabled={fields.length <= 1}>
                      Remove
                    </Button>
                  </Space>
                ))}

                <Button onClick={() => add({ productId: products[0]?.id ?? null, qty: 1 })}>Add Line</Button>
              </Space>
            )}
          </Form.List>
        </Form>
      </Modal>
    </Space>
  )
}

// frontend/src/views/modules/inventory/MovementsView.vue
<template>
  <div style="display: flex; flex-direction: column; gap: 12px">
    <el-card>
      <div style="display: flex; flex-direction: column; gap: 10px">
        <div style="display: flex; align-items: center; justify-content: space-between; gap: 12px">
          <div>
            <div style="font-size: 18px; font-weight: 600">Inventory Movements</div>
            <div style="color: #606266">IN / OUT / TRANSFER untuk update stok.</div>
          </div>
          <el-button type="primary" :disabled="!ctx.companyId" @click="openCreate">Create Movement</el-button>
        </div>

        <CompanyOrgBar />
      </div>
    </el-card>

    <el-card>
      <el-alert v-if="!ctx.companyId" title="Pilih company dulu." type="warning" show-icon style="margin-bottom: 12px" />

      <el-table :data="rows" style="width: 100%" v-loading="loading">
        <el-table-column prop="documentNo" label="Document No" width="180" />
        <el-table-column prop="status" label="Status" width="140" />
        <el-table-column prop="movementType" label="Type" width="140" />
        <el-table-column prop="movementDate" label="Date" width="140" />
        <el-table-column prop="description" label="Description" />
      </el-table>
    </el-card>

    <el-dialog v-model="createOpen" title="Create Inventory Movement" width="980px">
      <el-form label-position="top">
        <div style="display: grid; grid-template-columns: 1fr 1fr 1fr; gap: 12px">
          <el-form-item label="Type">
            <el-select v-model="form.movementType" style="width: 100%">
              <el-option label="IN" value="IN" />
              <el-option label="OUT" value="OUT" />
              <el-option label="TRANSFER" value="TRANSFER" />
            </el-select>
          </el-form-item>
          <el-form-item label="Movement Date">
            <el-date-picker v-model="form.movementDate" type="date" value-format="YYYY-MM-DD" style="width: 220px" />
          </el-form-item>
          <el-form-item label="Org">
            <el-input v-model="form.orgId" placeholder="Auto from context" :disabled="true" />
          </el-form-item>
        </div>

        <el-form-item label="Description">
          <el-input v-model="form.description" placeholder="optional" />
        </el-form-item>

        <div style="display: flex; align-items: center; justify-content: space-between; margin: 12px 0 6px">
          <div style="font-weight: 600">Lines</div>
          <el-button size="small" @click="addLine">Add Line</el-button>
        </div>

        <el-table :data="form.lines" size="small" style="width: 100%">
          <el-table-column label="Product" min-width="300">
            <template #default="scope">
              <el-select v-model="scope.row.productId" filterable placeholder="Select product" style="width: 100%" :disabled="products.length === 0">
                <el-option v-for="p in products" :key="p.id" :label="`${p.code} - ${p.name}`" :value="p.id" />
              </el-select>
            </template>
          </el-table-column>
          <el-table-column label="Qty" width="160">
            <template #default="scope">
              <el-input v-model="scope.row.qty" />
            </template>
          </el-table-column>
          <el-table-column label="From" min-width="220">
            <template #default="scope">
              <el-select v-model="scope.row.fromLocatorId" filterable clearable placeholder="From locator" style="width: 100%" :disabled="locators.length === 0 || form.movementType === 'IN'">
                <el-option v-for="l in locators" :key="l.id" :label="`${l.code} - ${l.name}`" :value="l.id" />
              </el-select>
            </template>
          </el-table-column>
          <el-table-column label="To" min-width="220">
            <template #default="scope">
              <el-select v-model="scope.row.toLocatorId" filterable clearable placeholder="To locator" style="width: 100%" :disabled="locators.length === 0 || form.movementType === 'OUT'">
                <el-option v-for="l in locators" :key="l.id" :label="`${l.code} - ${l.name}`" :value="l.id" />
              </el-select>
            </template>
          </el-table-column>
          <el-table-column label="" width="70">
            <template #default="scope">
              <el-button type="danger" plain size="small" @click="removeLine(scope.$index)">X</el-button>
            </template>
          </el-table-column>
        </el-table>

        <el-alert v-if="products.length === 0" title="Product belum ada. Buat Product dulu di Master Data." type="warning" show-icon style="margin-top: 12px" />
        <el-alert v-if="locators.length === 0" title="Locator belum ada. Buat Locator dulu di Inventory > Locators." type="warning" show-icon style="margin-top: 12px" />
      </el-form>

      <template #footer>
        <el-button @click="createOpen = false">Cancel</el-button>
        <el-button type="primary" :loading="saving" :disabled="!canSave" @click="save">Save</el-button>
      </template>
    </el-dialog>
  </div>
</template>

<script setup>
import { computed, onMounted, reactive, ref, watch } from 'vue'
import { ElMessage } from 'element-plus'
import { inventoryApi, masterDataApi } from '@/utils/api'
import { useContextStore } from '@/stores/context'
import CompanyOrgBar from '@/views/modules/common/CompanyOrgBar.vue'

const ctx = useContextStore()

const rows = ref([])
const loading = ref(false)

const products = ref([])
const locators = ref([])

const createOpen = ref(false)
const saving = ref(false)

const form = reactive({
  movementType: 'IN',
  movementDate: '',
  orgId: null,
  description: '',
  lines: []
})

const canSave = computed(() => {
  if (!ctx.companyId) return false
  if (!form.movementType) return false
  if (!form.movementDate) return false
  if (!Array.isArray(form.lines) || form.lines.length === 0) return false
  if (!form.lines.every((l) => l.productId && String(l.qty).trim())) return false

  if (form.movementType === 'IN') return form.lines.every((l) => l.toLocatorId)
  if (form.movementType === 'OUT') return form.lines.every((l) => l.fromLocatorId)
  // TRANSFER
  return form.lines.every((l) => l.fromLocatorId && l.toLocatorId && l.fromLocatorId !== l.toLocatorId)
})

function addLine() {
  form.lines.push({
    productId: products.value[0]?.id || null,
    qty: '1',
    fromLocatorId: locators.value[0]?.id || null,
    toLocatorId: locators.value[0]?.id || null
  })
}

function removeLine(idx) {
  form.lines.splice(idx, 1)
}

async function loadLookups() {
  if (!ctx.companyId) {
    products.value = []
    locators.value = []
    return
  }
  try {
    ;[products.value, locators.value] = await Promise.all([
      masterDataApi.listProducts(ctx.companyId),
      inventoryApi.listLocators(ctx.companyId)
    ])
  } catch {
    products.value = []
    locators.value = []
  }
}

async function load() {
  if (!ctx.companyId) {
    rows.value = []
    return
  }
  loading.value = true
  try {
    rows.value = await inventoryApi.listMovements(ctx.companyId)
  } catch (e) {
    ElMessage.error(e?.response?.data?.message || e?.message || 'Failed')
  } finally {
    loading.value = false
  }
}

function openCreate() {
  form.movementType = 'IN'
  form.movementDate = new Date().toISOString().slice(0, 10)
  form.orgId = ctx.orgId
  form.description = ''
  form.lines = []
  addLine()
  createOpen.value = true
}

async function save() {
  saving.value = true
  try {
    await inventoryApi.createMovement(ctx.companyId, {
      movementType: form.movementType,
      movementDate: form.movementDate,
      description: form.description,
      orgId: ctx.orgId || null,
      lines: form.lines.map((l) => ({
        productId: l.productId,
        qty: l.qty,
        fromLocatorId: l.fromLocatorId || null,
        toLocatorId: l.toLocatorId || null
      }))
    })
    ElMessage.success('Movement created')
    createOpen.value = false
    await load()
  } catch (e) {
    ElMessage.error(e?.response?.data?.message || e?.message || 'Failed')
  } finally {
    saving.value = false
  }
}

watch(
  () => ctx.companyId,
  async () => {
    await loadLookups()
    await load()
  }
)

watch(
  () => ctx.orgId,
  () => {
    form.orgId = ctx.orgId
  }
)

onMounted(async () => {
  await loadLookups()
  await load()
})
</script>
