// frontend2_new/src/views/modules/admin/UsersView.tsx
import { Button, Card, Form, Input, Modal, Popconfirm, Select, Space, Table, Tag, Typography, message } from 'antd'
import type { ColumnsType, TablePaginationConfig } from 'antd/es/table'
import { useEffect, useMemo, useState } from 'react'
import { adminApi, hrApi } from '@/utils/api'
import { getApiErrorMessage } from '@/utils/error'
import { useAuthStore } from '@/stores/auth'

type UserRole = 'ADMIN' | 'HR' | 'FINANCE' | 'INVENTORY' | 'EMPLOYEE'
type UserStatus = 'ACTIVE' | 'DISABLED'

type UserRow = {
  id: number
  fullName?: string
  email?: string
  role?: UserRole
  status?: UserStatus
  departmentName?: string
}

type UsersApiResponse = {
  users?: UserRow[]
  currentPage?: number
  totalItems?: number
  totalPages?: number
}

type CreateUserForm = {
  fullName: string
  email: string
  password: string
  role: UserRole
  departmentName: string
}

type EditUserForm = {
  fullName: string
  email: string
  role: UserRole
}

type ResetPasswordForm = {
  newPassword: string
}

export default function AdminUsersView() {
  const myRole = useAuthStore((s) => s.role)
  const isAdmin = String(myRole || '').toUpperCase() === 'ADMIN'

  const [loading, setLoading] = useState(false)
  const [rows, setRows] = useState<UserRow[]>([])

  const [page, setPage] = useState(1)
  const [pageSize, setPageSize] = useState(10)
  const [total, setTotal] = useState(0)

  const [q, setQ] = useState('')
  const [roleFilter, setRoleFilter] = useState<UserRole | undefined>(undefined)
  const [statusFilter, setStatusFilter] = useState<UserStatus | undefined>(undefined)

  const [departments, setDepartments] = useState<{ id: number; name?: string }[]>([])

  const [createOpen, setCreateOpen] = useState(false)
  const [createSaving, setCreateSaving] = useState(false)
  const [createForm] = Form.useForm<CreateUserForm>()

  const [editOpen, setEditOpen] = useState(false)
  const [editSaving, setEditSaving] = useState(false)
  const [editingId, setEditingId] = useState<number | null>(null)
  const [editForm] = Form.useForm<EditUserForm>()

  const [resetOpen, setResetOpen] = useState(false)
  const [resetSaving, setResetSaving] = useState(false)
  const [resetUserId, setResetUserId] = useState<number | null>(null)
  const [resetForm] = Form.useForm<ResetPasswordForm>()

  const roleOptions = useMemo(
    () =>
      (['ADMIN', 'HR', 'FINANCE', 'INVENTORY', 'EMPLOYEE'] as UserRole[]).map((r) => ({
        value: r,
        label: r
      })),
    []
  )

  const statusOptions = useMemo(
    () =>
      (['ACTIVE', 'DISABLED'] as UserStatus[]).map((s) => ({
        value: s,
        label: s
      })),
    []
  )

  const deptOptions = useMemo(
    () =>
      (departments || [])
        .filter((d) => Boolean(String(d.name || '').trim()))
        .map((d) => ({
          value: String(d.name),
          label: String(d.name)
        })),
    [departments]
  )

  async function loadDepartments() {
    try {
      setDepartments((await hrApi.listDepartments()) || [])
    } catch {
      setDepartments([])
    }
  }

  async function loadUsers(next?: { page?: number; pageSize?: number; role?: UserRole; status?: UserStatus }) {
    const nextPage = next?.page ?? page
    const nextPageSize = next?.pageSize ?? pageSize
    const nextRole = next?.role ?? roleFilter
    const nextStatus = next?.status ?? statusFilter

    setLoading(true)
    try {
      const res = (await adminApi.listUsers({
        page: Math.max(0, Number(nextPage) - 1),
        size: Number(nextPageSize),
        role: nextRole,
        status: nextStatus
      })) as UsersApiResponse

      setRows(res?.users || [])
      setTotal(Number(res?.totalItems || 0))
    } catch (e: any) {
      message.error(getApiErrorMessage(e, 'Failed to load users'))
      setRows([])
      setTotal(0)
    } finally {
      setLoading(false)
    }
  }

  useEffect(() => {
    void loadDepartments()
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [])

  useEffect(() => {
    void loadUsers({ page, pageSize })
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [page, pageSize, roleFilter, statusFilter])

  const filteredRows = useMemo(() => {
    const qq = q.trim().toLowerCase()
    if (!qq) return rows
    return (rows || []).filter((r) => {
      return (
        String(r.fullName || '').toLowerCase().includes(qq) ||
        String(r.email || '').toLowerCase().includes(qq)
      )
    })
  }, [q, rows])

  const columns: ColumnsType<UserRow> = [
    { title: 'ID', dataIndex: 'id', width: 80 },
    { title: 'Full Name', dataIndex: 'fullName', width: 220 },
    { title: 'Email', dataIndex: 'email', width: 240 },
    { title: 'Department', dataIndex: 'departmentName', width: 160 },
    {
      title: 'Role',
      dataIndex: 'role',
      width: 140,
      render: (v: any) => <Tag>{String(v || '-')}</Tag>
    },
    {
      title: 'Status',
      dataIndex: 'status',
      width: 140,
      render: (v: any) => {
        const s = String(v || '')
        if (s === 'ACTIVE') return <Tag color="green">ACTIVE</Tag>
        if (s === 'DISABLED') return <Tag color="red">DISABLED</Tag>
        return <Tag>{s || '-'}</Tag>
      }
    },
    {
      title: 'Action',
      key: 'action',
      width: 320,
      render: (_, r) => (
        <Space>
          <Button
            size="small"
            disabled={!isAdmin}
            onClick={() => {
              setEditingId(r.id)
              editForm.setFieldsValue({
                fullName: r.fullName || '',
                email: r.email || '',
                role: (r.role || 'EMPLOYEE') as UserRole
              })
              setEditOpen(true)
            }}
          >
            Edit
          </Button>
          <Button
            size="small"
            disabled={!isAdmin}
            onClick={() => {
              setResetUserId(r.id)
              resetForm.resetFields()
              setResetOpen(true)
            }}
          >
            Reset Password
          </Button>
          <Button
            size="small"
            disabled={!isAdmin}
            onClick={async () => {
              try {
                await adminApi.changeStatus(r.id)
                message.success('Status updated')
                await loadUsers()
              } catch (e: any) {
                message.error(getApiErrorMessage(e, 'Failed to change status'))
              }
            }}
          >
            Change Status
          </Button>
          <Popconfirm
            title="Delete user?"
            okText="Delete"
            okButtonProps={{ danger: true }}
            disabled={!isAdmin}
            onConfirm={async () => {
              try {
                await adminApi.deleteUser(r.id)
                message.success('Deleted')
                await loadUsers()
              } catch (e: any) {
                message.error(getApiErrorMessage(e, 'Failed to delete user'))
              }
            }}
          >
            <Button size="small" danger>
              Delete
            </Button>
          </Popconfirm>
        </Space>
      )
    }
  ]

  const pagination: TablePaginationConfig = {
    current: page,
    pageSize,
    total,
    showSizeChanger: true,
    onChange: (p, ps) => {
      setPage(p)
      setPageSize(ps)
    }
  }

  return (
    <Space direction="vertical" size={16} style={{ width: '100%' }}>
      <Card>
        <Space style={{ width: '100%', justifyContent: 'space-between' }} align="start">
          <div>
            <Typography.Title level={4} style={{ margin: 0 }}>
              User Management
            </Typography.Title>
            <Typography.Text type="secondary">Create/update user, reset password, change status, dan delete user (khusus ADMIN).</Typography.Text>
            <div style={{ marginTop: 8 }}>
              <Space wrap>
                <Tag color={isAdmin ? 'green' : 'orange'}>Role: {String(myRole || '-')}</Tag>
                {!isAdmin ? <Typography.Text type="warning">Login sebagai ADMIN untuk memakai fitur ini.</Typography.Text> : null}
              </Space>
            </div>
          </div>
          <Space>
            <Button onClick={() => void loadUsers()} loading={loading}>
              Refresh
            </Button>
            <Button
              type="primary"
              disabled={!isAdmin}
              onClick={() => {
                createForm.resetFields()
                createForm.setFieldsValue({ role: 'EMPLOYEE' })
                void loadDepartments()
                setCreateOpen(true)
              }}
            >
              Create User
            </Button>
          </Space>
        </Space>
      </Card>

      <Card>
        <Space direction="vertical" style={{ width: '100%' }} size={12}>
          <Input placeholder="Search name/email..." value={q} onChange={(e) => setQ(e.target.value)} style={{ maxWidth: 320 }} />
          <Select allowClear placeholder="Filter role" value={roleFilter} options={roleOptions} onChange={(v) => setRoleFilter(v ?? undefined)} />
          <Select allowClear placeholder="Filter status" value={statusFilter} options={statusOptions} onChange={(v) => setStatusFilter(v ?? undefined)} />
        </Space>
      </Card>

      <Card>
        <Table<UserRow> rowKey="id" loading={loading} columns={columns} dataSource={filteredRows} pagination={pagination} />
      </Card>

      <Modal
        open={createOpen}
        title="Create User"
        okText="Create"
        confirmLoading={createSaving}
        onCancel={() => setCreateOpen(false)}
        onOk={async () => {
          try {
            const v = await createForm.validateFields()
            setCreateSaving(true)
            await adminApi.createUser({
              fullName: v.fullName,
              email: v.email,
              password: v.password,
              role: v.role,
              departmentName: v.departmentName
            })
            message.success('Created')
            setCreateOpen(false)
            await loadUsers({ page: 1 })
            setPage(1)
          } catch (e: any) {
            if (e?.errorFields) return
            const status = e?.response?.status
            if (status === 401 || status === 403) {
              message.error('Forbidden. Endpoint /admin/* hanya bisa diakses oleh role ADMIN.')
            } else {
              message.error(getApiErrorMessage(e, 'Failed to create user'))
            }
          } finally {
            setCreateSaving(false)
          }
        }}
      >
        <Form<CreateUserForm> form={createForm} layout="vertical" initialValues={{ role: 'EMPLOYEE' }}>
          <Form.Item name="fullName" label="Full Name" rules={[{ required: true }]}>
            <Input />
          </Form.Item>
          <Form.Item name="email" label="Email" rules={[{ required: true, type: 'email' }]}>
            <Input />
          </Form.Item>
          <Form.Item name="password" label="Password" rules={[{ required: true, min: 8 }]}>
            <Input.Password />
          </Form.Item>
          <Form.Item name="role" label="Role" rules={[{ required: true }]}>
            <Select options={roleOptions} />
          </Form.Item>
          <Form.Item name="departmentName" label="Department" rules={[{ required: true }]}>
            <Select showSearch options={deptOptions} />
          </Form.Item>
        </Form>
      </Modal>

      <Modal
        open={editOpen}
        title="Edit User"
        okText="Save"
        confirmLoading={editSaving}
        onCancel={() => {
          setEditOpen(false)
          setEditingId(null)
        }}
        onOk={async () => {
          if (!editingId) return
          try {
            const v = await editForm.validateFields()
            setEditSaving(true)
            await adminApi.updateUser(editingId, {
              fullName: v.fullName,
              email: v.email,
              role: v.role
            })
            message.success('Saved')
            setEditOpen(false)
            setEditingId(null)
            await loadUsers()
          } catch (e: any) {
            if (e?.errorFields) return
            message.error(getApiErrorMessage(e, 'Failed to update user'))
          } finally {
            setEditSaving(false)
          }
        }}
      >
        <Form<EditUserForm> form={editForm} layout="vertical">
          <Form.Item name="fullName" label="Full Name" rules={[{ required: true }]}>
            <Input />
          </Form.Item>
          <Form.Item name="email" label="Email" rules={[{ required: true, type: 'email' }]}>
            <Input />
          </Form.Item>
          <Form.Item name="role" label="Role" rules={[{ required: true }]}>
            <Select options={roleOptions} />
          </Form.Item>
        </Form>
      </Modal>

      <Modal
        open={resetOpen}
        title="Reset Password"
        okText="Reset"
        confirmLoading={resetSaving}
        onCancel={() => {
          setResetOpen(false)
          setResetUserId(null)
        }}
        onOk={async () => {
          if (!resetUserId) return
          try {
            const v = await resetForm.validateFields()
            setResetSaving(true)
            await adminApi.resetPassword(resetUserId, { newPassword: v.newPassword })
            message.success('Password reset')
            setResetOpen(false)
            setResetUserId(null)
          } catch (e: any) {
            if (e?.errorFields) return
            message.error(getApiErrorMessage(e, 'Failed to reset password'))
          } finally {
            setResetSaving(false)
          }
        }}
      >
        <Form<ResetPasswordForm> form={resetForm} layout="vertical">
          <Form.Item name="newPassword" label="New Password" rules={[{ required: true, min: 8 }]}>
            <Input.Password />
          </Form.Item>
        </Form>
      </Modal>
    </Space>
  )
}

// frontend/src/views/modules/admin/UsersView.vue
<template>
  <div style="display: flex; flex-direction: column; gap: 12px">
    <el-card>
      <div style="display: flex; align-items: flex-start; justify-content: space-between; gap: 12px">
        <div>
          <div style="font-size: 18px; font-weight: 600">User Management</div>
          <div style="color: #606266; margin-top: 6px">Create/update user, reset password, change status, dan delete user (khusus ADMIN).</div>
        </div>
        <div style="display: flex; gap: 8px; align-items: center">
          <el-button @click="load">Refresh</el-button>
          <el-button type="primary" @click="openCreate">Create User</el-button>
        </div>
      </div>
    </el-card>

    <el-card>
      <div style="display: flex; gap: 10px; align-items: center; flex-wrap: wrap; margin-bottom: 10px">
        <el-input v-model="q" placeholder="Search name/email..." clearable style="max-width: 260px" />
        <el-select v-model="roleFilter" clearable placeholder="Filter role" style="min-width: 180px" @change="onFilterChange">
          <el-option v-for="r in roles" :key="r" :label="r" :value="r" />
        </el-select>
        <el-select v-model="statusFilter" clearable placeholder="Filter status" style="min-width: 180px" @change="onFilterChange">
          <el-option label="ACTIVE" value="ACTIVE" />
          <el-option label="DISABLED" value="DISABLED" />
        </el-select>
      </div>

      <el-table :data="filtered" style="width: 100%" size="small" v-loading="loading">
        <el-table-column prop="id" label="ID" width="80" />
        <el-table-column prop="fullName" label="Full Name" min-width="200" />
        <el-table-column prop="email" label="Email" min-width="220" />
        <el-table-column prop="department" label="Department" width="160" />
        <el-table-column prop="role" label="Role" width="120">
          <template #default="scope">
            <el-tag size="small" type="info">{{ scope.row.role }}</el-tag>
          </template>
        </el-table-column>
        <el-table-column prop="status" label="Status" width="120">
          <template #default="scope">
            <el-tag size="small" :type="scope.row.status === 'ACTIVE' ? 'success' : 'danger'">{{ scope.row.status }}</el-tag>
          </template>
        </el-table-column>
        <el-table-column label="Action" width="420">
          <template #default="scope">
            <div style="display: flex; gap: 8px; flex-wrap: wrap">
              <el-button size="small" @click="openEdit(scope.row)">Edit</el-button>
              <el-button size="small" type="warning" plain @click="openReset(scope.row)">Reset Password</el-button>
              <el-button size="small" :type="scope.row.status === 'ACTIVE' ? 'warning' : 'success'" plain @click="onToggleStatus(scope.row)">
                {{ scope.row.status === 'ACTIVE' ? 'Disable' : 'Activate' }}
              </el-button>
              <el-button size="small" type="danger" plain @click="onDelete(scope.row)">Delete</el-button>
            </div>
          </template>
        </el-table-column>
      </el-table>

      <div style="display: flex; justify-content: flex-end; margin-top: 10px">
        <el-pagination
          v-model:current-page="page"
          :page-size="size"
          :total="total"
          layout="prev, pager, next, jumper"
          @current-change="load"
        />
      </div>
    </el-card>

    <el-dialog v-model="userOpen" :title="userMode === 'create' ? 'Create User' : 'Edit User'" width="720px">
      <el-alert
        v-if="userMode === 'create' && !departments.length"
        title="Department belum ada. Buat Department dulu di modul HR (Departments)."
        type="warning"
        show-icon
        style="margin-bottom: 12px"
      />
      <el-form label-width="140px">
        <el-form-item label="Full Name" required>
          <el-input v-model="userForm.fullName" placeholder="Full name" />
        </el-form-item>
        <el-form-item label="Email" required>
          <el-input v-model="userForm.email" placeholder="name@company.com" />
        </el-form-item>
        <el-form-item label="Role" required>
          <el-select v-model="userForm.role" placeholder="Select role" style="width: 100%">
            <el-option v-for="r in roles" :key="r" :label="r" :value="r" />
          </el-select>
        </el-form-item>

        <el-form-item v-if="userMode === 'create'" label="Department" required>
          <el-select v-model="userForm.departmentName" filterable placeholder="Select department" style="width: 100%" :disabled="!departments.length">
            <el-option v-for="d in departments" :key="d.id" :label="d.name" :value="d.name" />
          </el-select>
        </el-form-item>

        <el-form-item v-if="userMode === 'create'" label="Password" required>
          <el-input v-model="userForm.password" type="password" show-password placeholder="Min 8 chars" />
        </el-form-item>
      </el-form>

      <template #footer>
        <div style="display: flex; justify-content: flex-end; gap: 8px">
          <el-button @click="userOpen = false">Cancel</el-button>
          <el-button type="primary" :disabled="!canSaveUser" :loading="saving" @click="onSaveUser">Save</el-button>
        </div>
      </template>
    </el-dialog>

    <el-dialog v-model="resetOpen" title="Reset Password" width="520px">
      <el-form label-width="140px">
        <el-form-item label="User">
          <div style="font-weight: 600">{{ resetTarget?.fullName }} ({{ resetTarget?.email }})</div>
        </el-form-item>
        <el-form-item label="New Password" required>
          <el-input v-model="resetForm.newPassword" type="password" show-password placeholder="Min 8 chars" />
        </el-form-item>
      </el-form>
      <template #footer>
        <div style="display: flex; justify-content: flex-end; gap: 8px">
          <el-button @click="resetOpen = false">Cancel</el-button>
          <el-button type="primary" :disabled="!canReset" :loading="saving" @click="onResetPassword">Reset</el-button>
        </div>
      </template>
    </el-dialog>
  </div>
</template>

<script setup>
import { computed, onMounted, ref } from 'vue'
import { ElMessage, ElMessageBox } from 'element-plus'
import { adminApi, hrApi } from '@/utils/api'

const roles = ['ADMIN', 'HR', 'FINANCE', 'INVENTORY', 'EMPLOYEE']

const loading = ref(false)
const saving = ref(false)

const q = ref('')
const roleFilter = ref(null)
const statusFilter = ref(null)

const page = ref(1)
const size = ref(10)
const total = ref(0)

const rows = ref([])
const departments = ref([])

const userOpen = ref(false)
const userMode = ref('create')
const editingId = ref(null)
const userForm = ref({
  fullName: '',
  email: '',
  role: 'EMPLOYEE',
  departmentName: '',
  password: ''
})

const resetOpen = ref(false)
const resetTarget = ref(null)
const resetForm = ref({ newPassword: '' })

function isValidEmail(v) {
  const s = String(v ?? '').trim()
  if (!s) return false
  return /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(s)
}

const filtered = computed(() => {
  const qq = q.value.trim().toLowerCase()
  if (!qq) return rows.value
  return rows.value.filter((r) => {
    const hay = `${r.fullName || ''} ${r.email || ''}`.toLowerCase()
    return hay.includes(qq)
  })
})

const canSaveUser = computed(() => {
  if (!String(userForm.value.fullName || '').trim()) return false
  if (!isValidEmail(userForm.value.email)) return false
  if (!String(userForm.value.role || '').trim()) return false

  if (userMode.value === 'create') {
    if (!String(userForm.value.departmentName || '').trim()) return false
    if (!String(userForm.value.password || '').trim()) return false
    if (String(userForm.value.password).trim().length < 8) return false
  }

  return true
})

const canReset = computed(() => {
  const p = String(resetForm.value.newPassword || '').trim()
  if (p.length < 8) return false
  return true
})

function onFilterChange() {
  page.value = 1
  load()
}

async function loadDepartments() {
  try {
    departments.value = await hrApi.listDepartments()
  } catch {
    departments.value = []
  }
}

async function load() {
  loading.value = true
  try {
    const params = {
      page: page.value - 1,
      size: size.value
    }
    if (roleFilter.value) params.role = roleFilter.value
    if (statusFilter.value) params.status = statusFilter.value

    const res = await adminApi.listUsers(params)
    rows.value = res?.users || []
    total.value = Number(res?.totalItems ?? 0)
  } catch (e) {
    ElMessage.error(e?.response?.data?.message || e?.message || 'Failed to load users')
  } finally {
    loading.value = false
  }
}

function openCreate() {
  userMode.value = 'create'
  editingId.value = null
  userForm.value = {
    fullName: '',
    email: '',
    role: 'EMPLOYEE',
    departmentName: departments.value[0]?.name || '',
    password: ''
  }
  userOpen.value = true
}

function openEdit(row) {
  userMode.value = 'edit'
  editingId.value = row.id
  userForm.value = {
    fullName: row.fullName || '',
    email: row.email || '',
    role: row.role || 'EMPLOYEE',
    departmentName: row.department || '',
    password: ''
  }
  userOpen.value = true
}

async function onSaveUser() {
  saving.value = true
  try {
    if (userMode.value === 'create') {
      const payload = {
        fullName: String(userForm.value.fullName || '').trim(),
        email: String(userForm.value.email || '').trim().toLowerCase(),
        password: String(userForm.value.password || '').trim(),
        role: userForm.value.role,
        departmentName: String(userForm.value.departmentName || '').trim()
      }
      await adminApi.createUser(payload)
      ElMessage.success('User created')
    } else {
      const payload = {
        fullName: String(userForm.value.fullName || '').trim(),
        email: String(userForm.value.email || '').trim().toLowerCase(),
        role: userForm.value.role
      }
      await adminApi.updateUser(editingId.value, payload)
      ElMessage.success('User updated')
    }

    userOpen.value = false
    await load()
  } catch (e) {
    ElMessage.error(e?.response?.data?.message || e?.message || 'Failed to save user')
  } finally {
    saving.value = false
  }
}

function openReset(row) {
  resetTarget.value = row
  resetForm.value.newPassword = ''
  resetOpen.value = true
}

async function onResetPassword() {
  saving.value = true
  try {
    await adminApi.resetPassword(resetTarget.value.id, { newPassword: String(resetForm.value.newPassword || '').trim() })
    ElMessage.success('Password reset')
    resetOpen.value = false
  } catch (e) {
    ElMessage.error(e?.response?.data?.message || e?.message || 'Failed to reset password')
  } finally {
    saving.value = false
  }
}

async function onToggleStatus(row) {
  try {
    await adminApi.changeStatus(row.id)
    ElMessage.success('Status updated')
    await load()
  } catch (e) {
    ElMessage.error(e?.response?.data?.message || e?.message || 'Failed to change status')
  }
}

async function onDelete(row) {
  try {
    await ElMessageBox.confirm(`Delete user "${row.fullName}"?`, 'Confirm', {
      type: 'warning',
      confirmButtonText: 'Delete',
      cancelButtonText: 'Cancel'
    })
    await adminApi.deleteUser(row.id)
    ElMessage.success('User deleted')
    await load()
  } catch (e) {
    if (e === 'cancel' || e === 'close') return
    ElMessage.error(e?.response?.data?.message || e?.message || 'Failed to delete user')
  }
}

onMounted(async () => {
  await loadDepartments()
  await load()
})
</script>
